#!/usr/bin/env python3
"""
Build parallaxx-home-men.js from "Parallaxx Home Men.dc.html".

This is the MEN'S avatar page. It was called "Parallaxx Home" while it was
the only one on the site.
  Bundle : parallaxx-home-men.js
  Tag    : parallaxx-home-men
  Sister : "Parallaxx Home Women.dc.html"
Both of those are AVATAR pages. The programme pages are separate:
"The Reconnected Man v4" and "The Reconnected Woman v4".

The .dc.html is the SOURCE OF RECORD. This script converts it into the
self-contained shadow-DOM custom element that Wix loads. Never hand-edit
parallaxx-home-men.js -- it is overwritten every run.

    python3 build-home-men-bundle.py

WHY A BUILD STEP AT ALL
The .dc.html runs inside Wix's Design Code runtime, where the component is
in the light DOM. The deployed bundle runs inside a shadow root. Three
things differ, and all three fail SILENTLY rather than throwing:

  1. document.getElementById() returns null inside a shadow root.
  2. GSAP resolves STRING selectors ('#px-hero') against document, so any
     ScrollTrigger keyed to a string gets a null trigger and never scrubs.
     This is what left every phone behind permanently dirty glass.
  3. @font-face declared inside a shadow tree is ignored by Chrome, so
     fonts have to be injected into document.head separately.

The guards below fail the build rather than shipping any of those.
"""
import re, sys, pathlib

HERE = pathlib.Path(__file__).parent
SRC  = HERE / "Parallaxx Home Men.dc.html"
OUT  = HERE / "parallaxx-home-men.js"

src = SRC.read_text(encoding="utf-8")

# ---- guards on the SOURCE -------------------------------------------------
lines = src.split("\n")

def style_block(open_line_idx):
    close = next(k for k in range(open_line_idx + 1, len(lines))
                 if lines[k].strip() == "</style>")
    return "\n".join(lines[open_line_idx + 1:close])

opens = [i for i, l in enumerate(lines) if l.strip() == "<style>"]
if len(opens) < 2:
    sys.exit("FAIL: expected a @font-face <style> and at least one page <style>.")
# Block 0 is the @font-face, which has to go into document.head separately.
# EVERY other block is page CSS and gets concatenated: the page sheet, then
# the baked-in site chrome. This used to read opens[1] only, which silently
# dropped the chrome stylesheet the moment it was added.
FONTFACE = style_block(opens[0])
CSS = "\n\n".join(style_block(i) for i in opens[1:])

h0 = next(i for i, l in enumerate(lines) if l.startswith('<div id="px-root">'))
h1 = next(i for i, l in enumerate(lines) if l.rstrip() == "</x-dc>")
HTML = "\n".join(lines[h0:h1]).rstrip()

# Only CSS and HTML are embedded in template literals, so only they can be
# broken by a backtick. The JS body is emitted as raw source, where a
# backtick inside a comment is harmless. Checking the whole file rejected
# this page the moment the nav was baked in, for the word `active` in one
# of PtNav's explanatory comments.
for _label, _chunk in (("CSS", CSS), ("HTML", HTML)):
    if "`" in _chunk:
        sys.exit(f"FAIL: backtick inside the {_label}. It would terminate the "
                 f"template literal and destroy the block.")
    if "${" in _chunk:
        sys.exit(f"FAIL: '${{' inside the {_label} would interpolate.")
if re.search(r"trigger:\s*'#", src):
    sys.exit("FAIL: GSAP ScrollTrigger keyed to a string selector. Inside a "
             "shadow root that resolves to null and the tween never runs.")

js = src[src.index('<script type="text/x-dc"'):]
js = js[js.index(">") + 1:js.index("</script>")]
body = js[js.index("componentDidMount(){") + len("componentDidMount(){"):]
body = body[:body.rindex("renderVals()")].rstrip()
body = body[:body.rindex("}")].rstrip()          # drop componentDidMount's closer

body = body.replace(
    "    const root = document.getElementById('px-root');\n    if(!root) return;\n", "")
body = body.replace("document.getElementById(", "root.getElementById(")

# ---- guards on the OUTPUT -------------------------------------------------
if "const root =" in body:
    sys.exit("FAIL: local root binding survived; it would shadow boot()'s parameter.")
if "document.getElementById" in body:
    sys.exit("FAIL: a document.getElementById survived the rewrite.")

font_links = re.findall(r'<link href="([^"]+)" rel="stylesheet">',
                        "\n".join(lines[:opens[0] + 30]))
fonts = "\n".join(
    "    var f%d=document.createElement('link'); f%d.rel='stylesheet'; f%d.href=%r; "
    "document.head.appendChild(f%d);" % (i, i, i, u, i)
    for i, u in enumerate(font_links))

OUT.write_text("""/* PARALLAXX TRANSFORMATIONS - Home page Wix Custom Element. Tag: parallaxx-home-men.
   GENERATED by build-home-men-bundle.py from "Parallaxx Home Men.dc.html".
   DO NOT EDIT THIS FILE - edit the .dc.html and rerun the build.
   In the Wix editor: turn the site Header + Footer OFF for this page. */
(function(){
  if (customElements.get('parallaxx-home-men')) return;

  var CSS = `%s`;

  var HTML = `%s`;

  function addFonts(){
    if (document.getElementById('px-fonts')) return;
    var p1=document.createElement('link'); p1.rel='preconnect'; p1.href='https://fonts.googleapis.com'; document.head.appendChild(p1);
    var p2=document.createElement('link'); p2.rel='preconnect'; p2.href='https://fonts.gstatic.com'; p2.crossOrigin=''; document.head.appendChild(p2);
%s
    /* @font-face has to live in the DOCUMENT, not the shadow root. Chrome
       ignores font-face rules declared inside a shadow tree. */
    var ff=document.createElement('style'); ff.id='px-fonts'; ff.textContent=`%s`; document.head.appendChild(ff);
  }

  function loadScript(src){
    return new Promise(function(res,rej){
      var ex=document.querySelector('script[data-px="'+src+'"]');
      if(ex){ if(ex.getAttribute('data-loaded')){res();} else { ex.addEventListener('load',function(){res();}); ex.addEventListener('error',rej);} return; }
      var s=document.createElement('script'); s.src=src; s.async=false; s.setAttribute('data-px',src);
      s.addEventListener('load',function(){ s.setAttribute('data-loaded','1'); res(); });
      s.addEventListener('error',rej);
      document.head.appendChild(s);
    });
  }

  function loadLibs(){
    var g=loadScript('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js')
      .then(function(){ return loadScript('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js'); });
    var l=loadScript('https://unpkg.com/lenis@1.1.13/dist/lenis.min.js');
    return Promise.all([ g.catch(function(){}), l.catch(function(){}) ]);
  }

  /* ══════════════ ANCESTOR COLLAPSE ══════════════
     Wix wraps a custom element in containers with fixed heights, so the page
     renders inside a short box with its own scrollbar. This walks up and
     releases them.

     IT MUST ONLY EVER RUN ONCE PER ELEMENT. The first version re-ran on
     every resize and called ScrollTrigger.refresh() whenever it changed
     anything. If Wix re-applied its own height after we set auto -- which it
     does -- "changed" was true on every pass, so:
         resize -> collapse -> refresh -> layout mutates -> resize -> ...
     That loop grew the document until Chrome clamped it at 2^24, which is
     16,777,216px of empty scroll. A WeakSet makes each element a one-shot,
     which is enough on its own to break the cycle.

     Three further belts, because a runaway here is invisible in the editor
     and catastrophic on the live page:
       - resize is debounced, so a drag is one pass and not sixty
       - refreshes are capped
       - a sanity check bails out entirely if the document is already absurd,
         so a loop that starts for some other reason cannot be fed by us
     ══════════════════════════════════════════════ */
  var PX_SANE_MAX = 200000;              // taller than any real page here
  var pxCollapsed = new WeakSet();
  var pxRefreshes = 0;

  /* Sums the real content inside the shadow root. A fixed-position child (a
     baked-in site nav) takes no space in flow, so summing children and
     skipping fixed ones is the only honest number. */
  function contentHeight(host){
    var total = 0;
    try{
      var kids = host.shadowRoot ? host.shadowRoot.children : [];
      for (var i=0;i<kids.length;i++){
        var c = kids[i];
        if (c.tagName === 'STYLE') continue;
        var cs = window.getComputedStyle(c);
        if (cs.position === 'fixed' || cs.display === 'none') continue;
        total += c.getBoundingClientRect().height;
      }
    }catch(e){}
    return total;
  }

  /* WHAT THIS IS ACTUALLY FIXING, measured on the live About page 5 Aug.
     59851px of page with 5790px of content in it: fifty thousand pixels of
     empty section under the footer. Wix writes the widget height the editor
     last recorded into an INLINE STYLESHEET RULE, not an inline style:

         #comp-msfv7drl { height: 59851px }
         #comp-msfv7drl { --custom-element-height: 59851px }

     Two consequences, and the previous version of this function missed both.

     1. A plain host.style.height = 'auto' LOSES to that rule. Every write
        here has to be setProperty with 'important' or nothing moves.
     2. The rule sits on the PARENT and the host stretches to match, so host
        and parent measure identically. Comparing each ancestor against the
        HOST and asking for a 600px difference therefore compares a number
        with itself. It never fired, on any page, for the exact case it was
        written for. Everything is measured against the CONTENT now.

     Verified in the browser before shipping: 59851 -> 5790, and it held.

     THE RUNAWAY GUARDS STAY. They are not paranoia: this loop once grew a
     document to Chrome's 2^24 clamp. Every element is one-shot via the
     WeakSet, and the whole thing bails if the page is already absurd. */
  function collapseAncestors(host){
    var changed = false;
    try{
      if (document.documentElement.scrollHeight > PX_SANE_MAX) return false;
      var content = contentHeight(host);
      if (content < 50) return false;

      if (!pxCollapsed.has(host) && host.getBoundingClientRect().height > content + 24){
        pxCollapsed.add(host);
        if (window.getComputedStyle(host).display === 'inline') host.style.setProperty('display','block','important');
        host.style.setProperty('height','auto','important');
        host.style.setProperty('min-height','0px','important');
        host.style.setProperty('max-height','none','important');
        changed = true;
      }

      var n = host.parentElement, guard = 0;
      while(n && n !== document.body && guard++ < 14){
        if(!pxCollapsed.has(n) && n.getBoundingClientRect().height > content + 240){
          pxCollapsed.add(n);
          n.style.setProperty('height','auto','important');
          n.style.setProperty('min-height','0px','important');
          n.style.setProperty('max-height','none','important');
          n.style.setProperty('--custom-element-height','auto','important');
          changed = true;
        }
        n = n.parentElement;
      }
    }catch(e){}
    return changed;
  }

  function collapseAndRefresh(host){
    if (!collapseAncestors(host)) return;
    if (pxRefreshes >= 4) return;
    pxRefreshes++;
    if (window.ScrollTrigger) { try{ window.ScrollTrigger.refresh(); }catch(e){} }
  }

  function boot(root){
    if(!root || !root.getElementById('px-root')) return;
%s
  }

  class ParallaxxHomeMen extends HTMLElement {
    connectedCallback(){
      if (this._mounted) return; this._mounted = true;
      addFonts();
      var shadow = this.attachShadow({mode:'open'});
      shadow.innerHTML = '<style>'+CSS+'</style>'+HTML;
      var host = this;
      /* THE HOST ITSELF, NOT JUST ITS ANCESTORS.
         collapseAndRefresh only walks upward. If the Wix editor has given
         the widget its own fixed height -- which it does by default -- the
         element keeps it and the surplus renders as empty page background
         under the content. Clearing it here is the difference between a
         page and a page followed by a white cliff. Added 4 Aug 2026. */
      try{ host.style.height='auto'; host.style.minHeight='0px'; }catch(e){}
      loadLibs().then(function(){ try{ boot(shadow); }catch(e){ console.error('[px] boot failed:', e); } })
        .catch(function(){ try{ boot(shadow); }catch(e){} });
      requestAnimationFrame(function(){ collapseAndRefresh(host); });
      [400,1200,2500,4000,6000].forEach(function(t){ setTimeout(function(){ collapseAndRefresh(host); }, t); });
      /* Images arriving late change the content height, and Wix can re-apply
         its stored height after its own layout settles. Watching the host is
         cheaper and far more reliable than guessing more timeouts. */
      if (window.ResizeObserver){
        try{ new ResizeObserver(function(){ collapseAndRefresh(host); }).observe(host); }catch(e){}
      }
      var pxRT;
      window.addEventListener('resize', function(){
        clearTimeout(pxRT);
        pxRT = setTimeout(function(){ collapseAndRefresh(host); }, 250);
      }, {passive:true});
    }
  }
  customElements.define('parallaxx-home-men', ParallaxxHomeMen);
})();
""" % (CSS, HTML, fonts, FONTFACE, body), encoding="utf-8")

print(f"built {OUT.name}  css={len(CSS)}  html={len(HTML)}  boot={len(body)}  fonts={len(font_links)}")
