#!/usr/bin/env python3
"""
Build parallaxx-quiz.js from "protection-archetype-quiz.html".

    python3 build-quiz-bundle.py

    Bundle : parallaxx-quiz.js
    Tag    : parallaxx-quiz
    Page   : parallaxxtransformations.com/the-archetype-quiz

WHY THAT URL AND NOT A NEW ONE
PtNav v3 already routes it. Its table reads:
    [/^\\/(men|the-reconnected-man|the-archetype-quiz)\\b/, 'men']
so /the-archetype-quiz lights the "For Men" item and the nav stays lit for
the whole run. The URL was decided before this file existed.

DIFFERENT SOURCE SHAPE FROM EVERY OTHER BUILD HERE
The pages are Wix Design Code components (<x-dc>, a helmet, a text/x-dc
script). The quiz is a plain standalone HTML document: one <style>, one
<body>, one <script>. So this script splits on those instead, and wraps the
markup in a #pq-root of its own because the quiz has no single wrapper.

THE ONLY TWO THINGS THAT BREAK IN A SHADOW ROOT
The quiz reaches the DOM in exactly two places, which is why this conversion
is safe to automate:
    const $ = (id) => document.getElementById(id);
    document.querySelectorAll('.view')
Both are rewritten to the shadow root. document.createElement,
document.addEventListener and document.title are left alone: they are
document-level on purpose and work unchanged.
"""
import re, sys, pathlib

HERE = pathlib.Path(__file__).parent
SRC  = HERE / "protection-archetype-quiz.html"
OUT  = HERE / "parallaxx-quiz.js"

src = SRC.read_text(encoding="utf-8")

CSS  = src[src.index("<style>") + len("<style>"): src.index("</style>")]

# The <script> lives INSIDE <body>, so the markup is body-open to script-open.
# Slicing to </body> instead swallows the script, and the quiz's own template
# literals then trip the backtick guard below. That is not a false positive
# worth relaxing -- it is the slice that is wrong.
_body_open = src.index(">", src.index("<body")) + 1
_script    = src.index("<script>")
HTML = src[_body_open:_script].strip()
JS   = src[_script + len("<script>"): src.index("</script>")]

# ---- guards: only CSS and HTML go into template literals -------------------
for label, chunk in (("CSS", CSS), ("HTML", HTML)):
    if "`" in chunk:
        sys.exit(f"FAIL: backtick inside the {label}. It would terminate the "
                 f"template literal and destroy the block.")
    if "${" in chunk:
        sys.exit(f"FAIL: '${{' inside the {label} would interpolate.")

# ---- enc_avif is banned across this project --------------------------------
# AVIF can silently fail as a WebGL texture, and one encoder everywhere means
# one less variable when an image does not appear. The logo carried it.
HTML = HTML.replace("enc_avif,quality_auto", "enc_auto")

# ---- shadow-root rewiring ---------------------------------------------------
before = JS
JS = JS.replace("document.getElementById(", "root.getElementById(")
JS = JS.replace("document.querySelectorAll(", "root.querySelectorAll(")
if JS == before:
    sys.exit("FAIL: nothing was rewired. The quiz's DOM access pattern changed.")
if re.search(r"document\.(getElementById|querySelector)\(", JS):
    sys.exit("FAIL: a document-level element lookup survived the rewrite.")

fonts = re.findall(r'<link href="([^"]+)" rel="stylesheet">', src)
font_js = "\n".join(
    "    var f%d=document.createElement('link'); f%d.rel='stylesheet'; f%d.href=%r; "
    "document.head.appendChild(f%d);" % (i, i, i, u, i)
    for i, u in enumerate(fonts))

OUT.write_text("""/* PARALLAXX PROTECTION ARCHETYPE QUIZ - Wix Custom Element.
   GENERATED by build-quiz-bundle.py from "protection-archetype-quiz.html".
   DO NOT EDIT THIS FILE - edit the source HTML and rerun the build.

   Tag        : parallaxx-quiz
   Page       : /the-archetype-quiz
   Site header + footer: the quiz carries its OWN stripped-back header, so
   leave the Wix header OFF. A quiz page wants fewer exits, not more.

   THE RESULT IS NOT GATED. view-result renders the archetype first and the
   lead form sits underneath it, which is the only version of this that is
   honest with the microcopy on the men's page. */
(function(){
  if (customElements.get('parallaxx-quiz')) return;

  var CSS = `%s`;

  var HTML = `%s`;

  var FONT_ID = 'pq-fonts';
  function addFonts(){
    if (document.getElementById(FONT_ID)) return;
    var p1=document.createElement('link'); p1.rel='preconnect'; p1.href='https://fonts.googleapis.com'; document.head.appendChild(p1);
    var p2=document.createElement('link'); p2.rel='preconnect'; p2.href='https://fonts.gstatic.com'; p2.crossOrigin=''; document.head.appendChild(p2);
%s
    var m=document.createElement('meta'); m.id=FONT_ID; document.head.appendChild(m);
  }

  /* The quiz swaps full-height views rather than scrolling, so the host has
     to be able to fill the viewport. Wix wraps a custom element in its own
     container, which otherwise caps it at the placeholder height. */
  function fitHost(host){
    try{
      host.style.display='block'; host.style.width='100%%';
      var n=host.parentElement, guard=0;
      while(n && n!==document.body && guard++<10){ n.style.height='auto'; n.style.minHeight='0px'; n=n.parentElement; }
    }catch(e){}
  }

  function boot(root){
%s
  }

  class ParallaxxQuiz extends HTMLElement {
    connectedCallback(){
      if (this._mounted) return; this._mounted = true;
      addFonts();
      var host = this;
      var shadow = this.attachShadow({mode:'open'});
      shadow.innerHTML = '<style>'+CSS+'</style><div id="pq-root">'+HTML+'</div>';
      fitHost(host);
      requestAnimationFrame(function(){ fitHost(host); });
      try{ boot(shadow); }catch(e){ console.error('[pq] boot failed:', e); }
    }
  }
  customElements.define('parallaxx-quiz', ParallaxxQuiz);
})();
""" % (CSS, HTML, font_js, JS), encoding="utf-8")

print(f"built {OUT.name}  css={len(CSS):,}  html={len(HTML):,}  js={len(JS):,}  fonts={len(fonts)}")
