#!/usr/bin/env python3
"""Wrap the approved v8 preview as the Wix Custom Element the live page loads.

The live page is a Wix Custom Element:
    Source URL  https://parallaxxlifeco.github.io/parallaxx-transformations/parallaxx-reconnected-woman.js
    Tag         parallaxx-reconnected-woman

The approved design is reconnected-woman-v9-preview.html, which is the file
Daniel reviewed and corrected screen by screen. This takes that file as-is and
publishes it through that tag, so what goes live is exactly what was approved.

LIGHT DOM ON PURPOSE. The page's own CSS is scoped to #trw-page and its script
uses document.querySelector throughout. Injecting into the light DOM means
every selector, the FAQ accordion, the modal and the video all keep working
without a single rewrite. A shadow root would need all of it re-pointed and is
where a port loses details.
"""
import re, pathlib

SRC = pathlib.Path("/tmp/rw/reconnected-woman-v9-preview.html")
OUT = pathlib.Path("/tmp/rw/parallaxx-reconnected-woman-v9.js")
TAG = "parallaxx-reconnected-woman"

s = SRC.read_text(encoding="utf-8")

font_links = re.findall(r'<link href="(https://fonts\.googleapis\.com[^"]+)" rel="stylesheet">', s)

styles = re.findall(r'<style>([\s\S]*?)</style>', s)
CSS = "\n".join(styles)

# REVEAL OFF. The .anim classes start at opacity 0 and rely on an
# IntersectionObserver to add .in-view. Inside the Wix custom element container
# that does not fire reliably, which left every section below the hero
# invisible on the live page. Content visible beats a fade-in, so the hidden
# start state is overridden here and nothing can be stranded at opacity 0.
CSS += """
#trw-page .anim, #trw-page .anim-scale, #trw-page .anim-left, #trw-page .anim-right,
#trw-page .hero-kicker, #trw-page #hero h1, #trw-page .hero-tagline,
#trw-page #hero .btn, #trw-page .hero-rule {
  opacity: 1 !important; transform: none !important; animation: none !important;
}

/* THE ENDLESS SCROLL. Wix measures the custom element and writes the result
   back as a min-height on the element itself, so the element's height feeds
   its own measurement and the page grew without bound: 11,456,701px of empty
   navy under the footer. Pinning the host to its content breaks the loop.
   Measured on the live page: 11,456,701px -> 8,710px. */
parallaxx-reconnected-woman {
  display: block !important;
  height: auto !important;
  min-height: 0 !important;
  max-height: none !important;
}
"""

# body: the page root through the end of the apply modal, stopping at the
# first script that follows it
body_start = s.index('<div id="trw-page"')
body_end = s.index('<script src="https://link.msgsndr.com')
HTML = s[body_start:body_end].strip()

# the page's own behaviour script, and the target shim
inline_scripts = re.findall(r'<script>([\s\S]*?)</script>', s)
PAGE_JS = "\n;\n".join(inline_scripts)

CHROME = re.findall(r'<script src="(https://parallaxxlifeco\.github\.io[^"]+)"></script>', s)

# A lone backslash inside a template literal starts an escape sequence, and
# CSS content values like \2014 read as octal, which is a hard syntax error.
# Escape them so the literal carries the characters through untouched.
CSS = CSS.replace("\\", "\\\\")
HTML = HTML.replace("\\", "\\\\")

for name, blob in (("CSS", CSS), ("HTML", HTML), ("PAGE_JS", PAGE_JS)):
    if "`" in blob or "${" in blob:
        raise SystemExit("FAIL: backtick or dollar-brace in %s would break the template literal" % name)

assert "trw-page" in HTML
assert "parallaxx-nav" in HTML and "parallaxx-footer" in HTML, "chrome missing from the body"
assert len(CHROME) == 2, "expected the nav and footer bundle URLs"

bundle = """/* PARALLAXX TRANSFORMATIONS - The Reconnected Woman. Tag: %(tag)s.
   GENERATED by build_bundle_from_preview.py from reconnected-woman-v9-preview.html,
   which is the approved design. DO NOT EDIT THIS FILE, edit that one and rerun.

   Renders into the LIGHT DOM on purpose. The stylesheet is scoped to #trw-page
   and the behaviour script uses document.querySelector, so light DOM keeps the
   accordion, the modal and the video working exactly as approved. */
(function () {
  if (customElements.get('%(tag)s')) return;

  var CSS = `%(css)s`;
  var HTML = `%(html)s`;

  function once(id, make) {
    if (document.getElementById(id)) return;
    var el = make(); el.id = id; document.head.appendChild(el);
  }

  function addHead() {
    once('trw-pre1', function () { var l = document.createElement('link'); l.rel = 'preconnect'; l.href = 'https://fonts.googleapis.com'; return l; });
    once('trw-pre2', function () { var l = document.createElement('link'); l.rel = 'preconnect'; l.href = 'https://fonts.gstatic.com'; l.crossOrigin = ''; return l; });
%(fonts)s
    once('trw-css', function () { var st = document.createElement('style'); st.textContent = CSS; return st; });
    /* The Wix page collapses the site header and footer, so the viewport meta
       has to come from here or the page lays out at 980px on a phone and every
       max-width 760px rule is dead. */
    if (!document.querySelector('meta[name="viewport"]')) {
      var mv = document.createElement('meta'); mv.name = 'viewport';
      mv.content = 'width=device-width, initial-scale=1'; document.head.appendChild(mv);
    }
  }

  function script(src, id) {
    return new Promise(function (res) {
      if (document.getElementById(id)) return res();
      var sc = document.createElement('script'); sc.id = id; sc.src = src; sc.async = false;
      sc.onload = res; sc.onerror = res; document.head.appendChild(sc);
    });
  }

  function boot() {
%(pagejs)s
  }

  var El = function () { return Reflect.construct(HTMLElement, [], El); };
  El.prototype = Object.create(HTMLElement.prototype);
  El.prototype.constructor = El;
  Object.setPrototypeOf(El, HTMLElement);

  El.prototype.connectedCallback = function () {
    if (this._trwUp) return;
    this._trwUp = true;
    addHead();
    this.innerHTML = HTML;
    script('%(nav)s', 'trw-nav-js');
    script('%(foot)s', 'trw-foot-js');
    script('https://link.msgsndr.com/js/form_embed.js', 'trw-ghl-js');
    try { boot(); } catch (e) { /* the page renders fully visible without it */ }
  };

  customElements.define('%(tag)s', El);
})();
""" % dict(
    tag=TAG,
    css=CSS,
    html=HTML,
    pagejs=PAGE_JS,
    fonts="\n".join(
        "    once('trw-font%d', function () { var l = document.createElement('link'); l.rel = 'stylesheet'; l.href = '%s'; return l; });"
        % (i, u) for i, u in enumerate(font_links)),
    nav=CHROME[0],
    foot=CHROME[1],
)

OUT.write_text(bundle, encoding="utf-8")
print("wrote %s  %d bytes  css=%d html=%d js=%d fonts=%d"
      % (OUT.name, len(bundle), len(CSS), len(HTML), len(PAGE_JS), len(font_links)))
