#!/usr/bin/env python3
"""
Build parallaxx-reconnected-woman.js from "The Reconnected Woman.dc.html".

Sibling of build-home-men-bundle.py, deliberately kept parallel rather than
factored into a shared module -- the two pages will drift (this one carries a
GoHighLevel form embed the home page does not) and a shared builder would grow
per-page branches faster than it would save lines. Read that file first; the
WHY of the build step is documented there and is identical here.

    python3 build-reconnected-woman-bundle.py

WHAT THIS PAGE ADDS ON TOP OF THE HOME BUILD

  1. The GHL form_embed.js has to reach the DOCUMENT, not the shadow root, or
     the application iframe never gets its resize messages. loadLibs() pulls
     it in alongside GSAP and Lenis.

  2. boot() is handed the SHADOW ROOT. A shadow root is a DocumentFragment:
     querySelectorAll works on it, classList does not. This page hides all of
     its content behind #prw-root.anim, so a classList call against the
     fragment would throw and leave every element at opacity 0. The source
     resolves a separate `stage` binding for exactly this; the guard below
     fails the build if that binding ever goes missing.
"""
import re, sys, pathlib

HERE = pathlib.Path(__file__).parent
SRC  = HERE / "The Reconnected Woman.dc.html"
OUT  = HERE / "parallaxx-reconnected-woman.js"
TAG  = "parallaxx-reconnected-woman"
ROOT = "prw-root"

src = SRC.read_text(encoding="utf-8")

# ---- guards on the SOURCE -------------------------------------------------
if "`" in src:
    bad = [i + 1 for i, l in enumerate(src.split("\n")) if "`" in l]
    sys.exit(f"FAIL: backtick in source (lines {bad}). CSS and HTML are embedded "
             f"in template literals; a backtick terminates them and silently "
             f"destroys the stylesheet. Use single quotes.")
if "${" in src:
    sys.exit("FAIL: '${' in source would interpolate inside the template literal.")
if re.search(r"trigger:\s*'#", src):
    sys.exit("FAIL: GSAP ScrollTrigger keyed to a string selector. Inside a "
             "shadow root that resolves to null and the tween never runs. "
             "Use document.getElementById('...') so the converter rewrites it.")
if "const stage =" not in src:
    sys.exit("FAIL: no `stage` binding in the source. boot() receives the shadow "
             "root, which has no classList, so #%s.anim could never be removed "
             "and the whole page would stay at opacity 0." % ROOT)

lines = src.split("\n")

def style_block(open_line_idx):
    close = next(k for k in range(open_line_idx + 1, len(lines))
                 if lines[k].strip() == "</style>")
    return "\n".join(lines[open_line_idx + 1:close])

opens = [i for i, l in enumerate(lines) if l.strip() == "<style>"]
if len(opens) < 2:
    sys.exit("FAIL: expected a @font-face <style> and a main <style> in the helmet.")
FONTFACE, CSS = style_block(opens[0]), style_block(opens[1])

h0 = next(i for i, l in enumerate(lines) if l.startswith('<div id="%s"' % ROOT))
h1 = next(i for i, l in enumerate(lines) if l.rstrip() == "</x-dc>")
HTML = "\n".join(lines[h0:h1]).rstrip()

js = src[src.index('<script type="text/x-dc"'):]
js = js[js.index(">") + 1:js.index("</script>")]
body = js[js.index("componentDidMount(){") + len("componentDidMount(){"):]
body = body[:body.rindex("renderVals()")].rstrip()
body = body[:body.rindex("}")].rstrip()          # drop componentDidMount's closer

body = body.replace(
    "    const root = document.getElementById('%s');\n    if(!root) return;\n" % ROOT, "")
body = body.replace("document.getElementById(", "root.getElementById(")

# ---- guards on the OUTPUT -------------------------------------------------
if "const root =" in body:
    sys.exit("FAIL: local root binding survived; it would shadow boot()'s parameter.")
if "document.getElementById" in body:
    sys.exit("FAIL: a document.getElementById survived the rewrite.")
if "root.classList" in body:
    sys.exit("FAIL: classList called on the shadow root. Use `stage`.")

font_links = re.findall(r'<link href="([^"]+)" rel="stylesheet">',
                        "\n".join(lines[:opens[0] + 30]))
fonts = "\n".join(
    "    var f%d=document.createElement('link'); f%d.rel='stylesheet'; f%d.href=%r; "
    "document.head.appendChild(f%d);" % (i, i, i, u, i)
    for i, u in enumerate(font_links))

OUT.write_text("""/* PARALLAXX TRANSFORMATIONS - The Reconnected Woman Wix Custom Element. Tag: %s.
   GENERATED by build-reconnected-woman-bundle.py from "The Reconnected Woman.dc.html".
   DO NOT EDIT THIS FILE - edit the .dc.html and rerun the build.
   In the Wix editor: turn the site Header + Footer OFF for this page and place
   PtNav (active="experiences") and PtFooter around it. */
(function(){
  if (customElements.get('%s')) return;

  var CSS = `%s`;

  var HTML = `%s`;

  function addFonts(){
    if (document.getElementById('prw-fonts')) return;
    var p1=document.createElement('link'); p1.rel='preconnect'; p1.href='https://fonts.googleapis.com'; document.head.appendChild(p1);
    var p2=document.createElement('link'); p2.rel='preconnect'; p2.href='https://fonts.gstatic.com'; p2.crossOrigin=''; document.head.appendChild(p2);
%s
    /* @font-face has to live in the DOCUMENT, not the shadow root. Chrome
       ignores font-face rules declared inside a shadow tree. */
    var ff=document.createElement('style'); ff.id='prw-fonts'; ff.textContent=`%s`; document.head.appendChild(ff);
  }

  function loadScript(src){
    return new Promise(function(res,rej){
      var ex=document.querySelector('script[data-px="'+src+'"]');
      if(ex){ if(ex.getAttribute('data-loaded')){res();} else { ex.addEventListener('load',function(){res();}); ex.addEventListener('error',rej);} return; }
      var s=document.createElement('script'); s.src=src; s.async=false; s.setAttribute('data-px',src);
      s.addEventListener('load',function(){ s.setAttribute('data-loaded','1'); res(); });
      s.addEventListener('error',rej);
      document.head.appendChild(s);
    });
  }

  function loadLibs(){
    var g=loadScript('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js')
      .then(function(){ return loadScript('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js'); });
    var l=loadScript('https://unpkg.com/lenis@1.1.13/dist/lenis.min.js');
    /* GoHighLevel form resizer. Must sit in the document: it talks to the
       application iframe by postMessage and never sees a shadow tree. */
    var f=loadScript('https://link.msgsndr.com/js/form_embed.js');
    return Promise.all([ g.catch(function(){}), l.catch(function(){}), f.catch(function(){}) ]);
  }

  /* This rewrites ancestor heights, which moves every scroll position on the
     page. ScrollTrigger has already cached those positions, so without a
     refresh afterwards its triggers fire at the wrong offsets. Returns
     whether it actually changed anything so the caller can avoid refreshing
     for nothing. */
  /* Runaway guards. This loop once grew a document to Chrome's 2^24 clamp,
     so every element is one-shot and the whole thing bails if the page is
     already absurd. */
  var PX_SANE_MAX = 200000;              // taller than any real page here
  var pxCollapsed = new WeakSet();

  /* Sums the real content inside the shadow root. A fixed-position child (a
     baked-in site nav) takes no space in flow, so summing children and
     skipping fixed ones is the only honest number. */
  function contentHeight(host){
    var total = 0;
    try{
      var kids = host.shadowRoot ? host.shadowRoot.children : [];
      for (var i=0;i<kids.length;i++){
        var c = kids[i];
        if (c.tagName === 'STYLE') continue;
        var cs = window.getComputedStyle(c);
        if (cs.position === 'fixed' || cs.display === 'none') continue;
        total += c.getBoundingClientRect().height;
      }
    }catch(e){}
    return total;
  }

  /* WHAT THIS IS ACTUALLY FIXING, measured on the live About page 5 Aug.
     59851px of page with 5790px of content in it: fifty thousand pixels of
     empty section under the footer. Wix writes the widget height the editor
     last recorded into an INLINE STYLESHEET RULE, not an inline style:

         #comp-msfv7drl { height: 59851px }
         #comp-msfv7drl { --custom-element-height: 59851px }

     Two consequences, and the previous version of this function missed both.

     1. A plain host.style.height = 'auto' LOSES to that rule. Every write
        here has to be setProperty with 'important' or nothing moves.
     2. The rule sits on the PARENT and the host stretches to match, so host
        and parent measure identically. Comparing each ancestor against the
        HOST and asking for a 600px difference therefore compares a number
        with itself. It never fired, on any page, for the exact case it was
        written for. Everything is measured against the CONTENT now.

     Verified in the browser before shipping: 59851 -> 5790, and it held.

     THE RUNAWAY GUARDS STAY. They are not paranoia: this loop once grew a
     document to Chrome's 2^24 clamp. Every element is one-shot via the
     WeakSet, and the whole thing bails if the page is already absurd. */
  function collapseAncestors(host){
    var changed = false;
    try{
      if (document.documentElement.scrollHeight > PX_SANE_MAX) return false;
      var content = contentHeight(host);
      if (content < 50) return false;

      if (!pxCollapsed.has(host) && host.getBoundingClientRect().height > content + 24){
        pxCollapsed.add(host);
        if (window.getComputedStyle(host).display === 'inline') host.style.setProperty('display','block','important');
        host.style.setProperty('height','auto','important');
        host.style.setProperty('min-height','0px','important');
        host.style.setProperty('max-height','none','important');
        changed = true;
      }

      var n = host.parentElement, guard = 0;
      while(n && n !== document.body && guard++ < 14){
        if(!pxCollapsed.has(n) && n.getBoundingClientRect().height > content + 240){
          pxCollapsed.add(n);
          n.style.setProperty('height','auto','important');
          n.style.setProperty('min-height','0px','important');
          n.style.setProperty('max-height','none','important');
          n.style.setProperty('--custom-element-height','auto','important');
          changed = true;
        }
        n = n.parentElement;
      }
    }catch(e){}
    return changed;
  }

  function collapseAndRefresh(host){
    var changed = collapseAncestors(host);
    if (changed && window.ScrollTrigger) {
      try{ window.ScrollTrigger.refresh(); }catch(e){}
    }
  }

  function boot(root){
    if(!root || !root.getElementById('%s')) return;
%s
  }

  class ParallaxxReconnectedWoman extends HTMLElement {
    connectedCallback(){
      if (this._mounted) return; this._mounted = true;
      addFonts();
      var shadow = this.attachShadow({mode:'open'});
      shadow.innerHTML = '<style>'+CSS+'</style>'+HTML;
      var host = this;
      loadLibs().then(function(){ try{ boot(shadow); }catch(e){ console.error('[prw] boot failed:', e); } })
        .catch(function(){ try{ boot(shadow); }catch(e){} });
      requestAnimationFrame(function(){ collapseAndRefresh(host); });
      [400,1200,2500,4000,6000].forEach(function(t){ setTimeout(function(){ collapseAndRefresh(host); }, t); });
      /* Images arriving late change the content height, and Wix can re-apply
         its stored height after its own layout settles. Watching the host is
         cheaper and far more reliable than guessing more timeouts. */
      if (window.ResizeObserver){
        try{ new ResizeObserver(function(){ collapseAndRefresh(host); }).observe(host); }catch(e){}
      }
      window.addEventListener('resize', function(){ collapseAndRefresh(host); }, {passive:true});
    }
  }
  customElements.define('%s', ParallaxxReconnectedWoman);
})();
""" % (TAG, TAG, CSS, HTML, fonts, FONTFACE, ROOT, body, TAG), encoding="utf-8")

print(f"built {OUT.name}  css={len(CSS)}  html={len(HTML)}  boot={len(body)}  fonts={len(font_links)}")
