#!/usr/bin/env python3
"""Wrap the v10 preview as the Wix Custom Element tag the site loads.

    Source URL  /parallaxx-reconnected-woman.js
    Tag         parallaxx-reconnected-woman

Supersedes build_bundle_v9.py, which is kept beside this one so the v9
design can still be rebuilt if v10 has to be rolled back. Both write the
SAME output file, so only one of them is the current build — this one.

WHAT CHANGED FROM v9, AND WHY IT MATTERS HERE
---------------------------------------------
The site is no longer on Wix. Cloudflare Pages builds every route from
migration/build-site.py, and each route is a standalone page whose whole
body is <parallaxx-reconnected-woman> plus this bundle. Three things v9
carried are therefore gone:

  * The reveal-off override. v9 pinned every .anim to opacity:1 because
    IntersectionObserver did not fire reliably inside the Wix custom
    element container. There is no Wix container now, so the reveals are
    left alone and the page animates as designed. The page script still
    carries its own 4-second failsafe, so nothing can strand at opacity 0.
  * The host min-height pin. Wix measured the element and wrote the result
    back as its min-height, feeding its own measurement — 11,456,701px of
    navy under the footer. Cloudflare serves plain HTML and does not.
  * The absolute GitHub Pages URLs for the nav and footer. Those broke on
    preview deploys by pulling chrome from the live site. Relative now.

LIGHT DOM, STILL ON PURPOSE. The stylesheet is scoped to #rw-page and the
behaviour script uses document.querySelector throughout, so the light DOM
keeps the accordion, the modal, the videos and every reveal working with
no rewriting. The nav and footer attach their own shadow roots, so this
page's styles cannot reach into them.
"""
import re, pathlib

HERE = pathlib.Path(__file__).parent
SRC = HERE / "reconnected-woman-v10-preview.html"
OUT = HERE / "parallaxx-reconnected-woman.js"
TAG = "parallaxx-reconnected-woman"

s = SRC.read_text(encoding="utf-8")

font_links = re.findall(
    r'<link[^>]*href="(https://fonts\.googleapis\.com[^"]+)"[^>]*>', s)

CSS = "\n".join(re.findall(r"<style>([\s\S]*?)</style>", s))

body_start = s.index('<div id="rw-page"')
body_end = s.index('<script src="https://link.msgsndr.com')
HTML = s[body_start:body_end].strip()

PAGE_JS = "\n;\n".join(re.findall(r"<script>([\s\S]*?)</script>", s))

# A lone backslash inside a template literal starts an escape sequence, and
# CSS content values like \2014 read as octal, which is a hard syntax error.
CSS = CSS.replace("\\", "\\\\")
HTML = HTML.replace("\\", "\\\\")

for name, blob in (("CSS", CSS), ("HTML", HTML), ("PAGE_JS", PAGE_JS)):
    if "`" in blob or "${" in blob:
        raise SystemExit(
            "FAIL: backtick or dollar-brace in %s would break the template literal" % name)

assert "rw-page" in HTML, "page root missing"
assert "parallaxx-nav" in HTML and "parallaxx-footer" in HTML, "chrome missing from the body"
assert "0RT5EVaTlGxo6QBjyIPT" in HTML, "the application form is missing"
assert HTML.count("0RT5EVaTlGxo6QBjyIPT") == 3, "the form id must appear three times"

# The annotation layer is a build-time thing and must never reach a browser.
for marker in ('class="note"', "noteBtn", 'class="ph"', "IMAGE_SLOT_", "[CLIENT]"):
    if marker in HTML:
        raise SystemExit("FAIL: %s is still in the markup" % marker)

bundle = """/* PARALLAXX TRANSFORMATIONS - The Reconnected Woman. Tag: %(tag)s.
   GENERATED by build_bundle_v10.py from reconnected-woman-v10-preview.html,
   which is the approved design. DO NOT EDIT THIS FILE, edit that one and rerun.

   Renders into the LIGHT DOM on purpose. The stylesheet is scoped to #rw-page
   and the behaviour script uses document.querySelector, so light DOM keeps the
   accordion, the modal, the videos and the reveals working as approved. */
(function () {
  if (customElements.get('%(tag)s')) return;

  var CSS = `%(css)s`;
  var HTML = `%(html)s`;

  function once(id, make) {
    if (document.getElementById(id)) return;
    var el = make(); el.id = id; document.head.appendChild(el);
  }

  function addHead() {
    once('rw-pre1', function () { var l = document.createElement('link'); l.rel = 'preconnect'; l.href = 'https://fonts.googleapis.com'; return l; });
    once('rw-pre2', function () { var l = document.createElement('link'); l.rel = 'preconnect'; l.href = 'https://fonts.gstatic.com'; l.crossOrigin = ''; return l; });
%(fonts)s
    once('rw-css', function () { var st = document.createElement('style'); st.textContent = CSS; return st; });
    if (!document.querySelector('meta[name="viewport"]')) {
      var mv = document.createElement('meta'); mv.name = 'viewport';
      mv.content = 'width=device-width, initial-scale=1'; document.head.appendChild(mv);
    }
  }

  function script(src, id) {
    return new Promise(function (res) {
      if (document.getElementById(id)) return res();
      var sc = document.createElement('script'); sc.id = id; sc.src = src; sc.async = false;
      sc.onload = res; sc.onerror = res; document.head.appendChild(sc);
    });
  }

  function boot() {
%(pagejs)s
  }

  var El = function () { return Reflect.construct(HTMLElement, [], El); };
  El.prototype = Object.create(HTMLElement.prototype);
  El.prototype.constructor = El;
  Object.setPrototypeOf(El, HTMLElement);

  El.prototype.connectedCallback = function () {
    if (this._rwUp) return;
    this._rwUp = true;
    addHead();
    this.innerHTML = HTML;
    script('/parallaxx-nav.js', 'rw-nav-js');
    script('/parallaxx-footer.js', 'rw-foot-js');
    script('https://link.msgsndr.com/js/form_embed.js', 'rw-ghl-js');
    try { boot(); } catch (e) { /* the page renders fully visible without it */ }
  };

  customElements.define('%(tag)s', El);
})();
""" % dict(
    tag=TAG,
    css=CSS,
    html=HTML,
    pagejs=PAGE_JS,
    fonts="\n".join(
        "    once('rw-font%d', function () { var l = document.createElement('link'); l.rel = 'stylesheet'; l.href = '%s'; return l; });"
        % (i, u) for i, u in enumerate(font_links)),
)

OUT.write_text(bundle, encoding="utf-8")
print("wrote %s  %d bytes  css=%d html=%d js=%d fonts=%d"
      % (OUT.name, len(bundle), len(CSS), len(HTML), len(PAGE_JS), len(font_links)))
