#!/usr/bin/env python3
"""
Build the site chrome as Wix Custom Elements.

    PtNav v3.dc.html     -> parallaxx-nav.js      tag: parallaxx-nav
    PtFooter v3.dc.html  -> parallaxx-footer.js   tag: parallaxx-footer

    python3 build-chrome-bundles.py

Same contract as build-home-men-bundle.py: the .dc.html is the SOURCE OF
RECORD and the .js is overwritten every run. Never hand-edit the output.

WHY THE CHROME NEEDS BUNDLING AT ALL
Until now PtNav and PtFooter only ever existed as .dc.html, which meant they
could be placed in Wix but could never be seen in the GitHub Pages preview.
Every preview of every page has therefore been missing its header and footer,
so the seam where a page meets the footer has never once been checked before
going live. These bundles make the preview show what Wix will show.

TWO DIFFERENCES FROM THE PAGE BUILDER

  1. PROPS. In the DC runtime a component reads this.props, which Wix supplies
     from the editor. A custom element has no props, so this.props is rewired
     to read HOST ATTRIBUTES instead: <parallaxx-nav active="men">.
     PtNav v3 also derives active from the URL by itself, so the attribute is
     only a manual override.

  2. NO GSAP OR LENIS. The chrome must never wait on a CDN. A header that
     appears late is worse than one that never animates.
"""
import re, sys, pathlib

HERE = pathlib.Path(__file__).parent

JOBS = [
    {"src": "PtNav v3.dc.html",    "out": "parallaxx-nav.js",
     "tag": "parallaxx-nav",       "cls": "ParallaxxNav",
     "root": "pt-nav",             "props": ["active"]},
    {"src": "PtFooter v3.dc.html", "out": "parallaxx-footer.js",
     "tag": "parallaxx-footer",    "cls": "ParallaxxFooter",
     "root": "pt-foot",            "props": []},
]


def build(job):
    src_path = HERE / job["src"]
    src = src_path.read_text(encoding="utf-8")

    lines = src.split("\n")

    opens = [i for i, l in enumerate(lines) if l.strip() == "<style>"]
    if not opens:
        sys.exit(f"FAIL [{job['src']}]: no <style> block found.")

    def style_block(i):
        close = next(k for k in range(i + 1, len(lines)) if lines[k].strip() == "</style>")
        return "\n".join(lines[i + 1:close])

    CSS = "\n\n".join(style_block(i) for i in opens)

    # markup: everything between </helmet> and </x-dc>
    h_end = next(i for i, l in enumerate(lines) if l.strip() == "</helmet>")
    x_end = next(i for i, l in enumerate(lines) if l.rstrip() == "</x-dc>")
    HTML = "\n".join(lines[h_end + 1:x_end]).strip()

    # Only CSS and HTML are embedded in template literals, so only they can be
    # broken by a backtick. The JS body is emitted as raw source, where a
    # backtick in a comment is harmless -- checking the whole file rejected
    # PtNav v3 for the word `active` inside an explanatory comment.
    for label, chunk in (("CSS", CSS), ("HTML", HTML)):
        if "`" in chunk:
            sys.exit(f"FAIL [{job['src']}]: backtick inside the {label}. It would "
                     f"terminate the template literal and destroy the block.")
        if "${" in chunk:
            sys.exit(f"FAIL [{job['src']}]: '${{' inside the {label} would interpolate.")

    js = src[src.index('<script type="text/x-dc"'):]
    js = js[js.index(">") + 1:js.index("</script>")]
    body = js[js.index("componentDidMount(){") + len("componentDidMount(){"):]
    body = body[:body.rindex("renderVals()")].rstrip()
    body = body[:body.rindex("}")].rstrip()

    body = body.replace("document.getElementById(", "root.getElementById(")
    body = body.replace("this.props", "props")

    if "document.getElementById" in body:
        sys.exit(f"FAIL [{job['src']}]: a document.getElementById survived.")

    font_links = re.findall(r'<link href="([^"]+)" rel="stylesheet">', src)
    fonts = "\n".join(
        "    var f%d=document.createElement('link'); f%d.rel='stylesheet'; f%d.href=%r; "
        "document.head.appendChild(f%d);" % (i, i, i, u, i)
        for i, u in enumerate(font_links))

    prop_lines = "\n".join(
        "      %s: host.getAttribute('%s') || ''," % (p, p) for p in job["props"])

    out = """/* PARALLAXX %s - GENERATED by build-chrome-bundles.py from "%s".
   DO NOT EDIT - edit the .dc.html and rerun the build.
   Tag: %s */
(function(){
  if (customElements.get('%s')) return;

  var CSS = `%s`;

  var HTML = `%s`;

  var FONT_ID = 'px-chrome-fonts';
  function addFonts(){
    if (document.getElementById(FONT_ID)) return;
    var p1=document.createElement('link'); p1.rel='preconnect'; p1.href='https://fonts.googleapis.com'; document.head.appendChild(p1);
    var p2=document.createElement('link'); p2.rel='preconnect'; p2.href='https://fonts.gstatic.com'; p2.crossOrigin=''; document.head.appendChild(p2);
%s
    var m=document.createElement('meta'); m.id=FONT_ID; document.head.appendChild(m);
  }

  function boot(root, props){
    if(!root || !root.getElementById('%s')) return;
%s
  }

  class %s extends HTMLElement {
    connectedCallback(){
      if (this._mounted) return; this._mounted = true;
      addFonts();
      var host = this;
      var shadow = this.attachShadow({mode:'open'});
      shadow.innerHTML = '<style>'+CSS+'</style>'+HTML;
      var props = {
%s
      };
      try{ boot(shadow, props); }catch(e){ console.error('[px chrome] boot failed:', e); }
    }
  }
  customElements.define('%s', %s);
})();
""" % (job["tag"].upper(), job["src"], job["tag"], job["tag"], CSS, HTML,
       fonts, job["root"], body, job["cls"], prop_lines, job["tag"], job["cls"])

    (HERE / job["out"]).write_text(out, encoding="utf-8")
    print(f"built {job['out']:24s} css={len(CSS):6,}  html={len(HTML):6,}  boot={len(body):6,}")


for j in JOBS:
    build(j)
