#!/usr/bin/env python3
"""
Build parallaxx-home-page.js from "Parallaxx Home.dc.html".

The .dc.html is the SOURCE OF RECORD. This script converts it into the
self-contained shadow-DOM custom element that Wix loads. Never hand-edit
parallaxx-home-page.js -- it is overwritten every run.

    python3 build-home-bundle.py

WHY A BUILD STEP AT ALL
The .dc.html runs inside Wix's Design Code runtime, where the component is
in the light DOM. The deployed bundle runs inside a shadow root. Three
things differ, and all three fail SILENTLY rather than throwing:

  1. document.getElementById() returns null inside a shadow root.
  2. GSAP resolves STRING selectors ('#px-hero') against document, so any
     ScrollTrigger keyed to a string gets a null trigger and never scrubs.
     This is what left every phone behind permanently dirty glass.
  3. @font-face declared inside a shadow tree is ignored by Chrome, so
     fonts have to be injected into document.head separately.

The guards below fail the build rather than shipping any of those.
"""
import re, sys, pathlib

HERE = pathlib.Path(__file__).parent
SRC  = HERE / "Parallaxx Home.dc.html"
OUT  = HERE / "parallaxx-home-page.js"

src = SRC.read_text(encoding="utf-8")

# ---- guards on the SOURCE -------------------------------------------------
if "`" in src:
    bad = [i + 1 for i, l in enumerate(src.split("\n")) if "`" in l]
    sys.exit(f"FAIL: backtick in source (lines {bad}). CSS and HTML are embedded "
             f"in template literals; a backtick terminates them and silently "
             f"destroys the stylesheet. Use single quotes.")
if "${" in src:
    sys.exit("FAIL: '${' in source would interpolate inside the template literal.")
if re.search(r"trigger:\s*'#", src):
    sys.exit("FAIL: GSAP ScrollTrigger keyed to a string selector. Inside a "
             "shadow root that resolves to null and the tween never runs. "
             "Use document.getElementById('...') so the converter rewrites it.")

lines = src.split("\n")

def style_block(open_line_idx):
    close = next(k for k in range(open_line_idx + 1, len(lines))
                 if lines[k].strip() == "</style>")
    return "\n".join(lines[open_line_idx + 1:close])

opens = [i for i, l in enumerate(lines) if l.strip() == "<style>"]
if len(opens) < 2:
    sys.exit("FAIL: expected a @font-face <style> and a main <style> in the helmet.")
FONTFACE, CSS = style_block(opens[0]), style_block(opens[1])

h0 = next(i for i, l in enumerate(lines) if l.startswith('<div id="px-root">'))
h1 = next(i for i, l in enumerate(lines) if l.rstrip() == "</x-dc>")
HTML = "\n".join(lines[h0:h1]).rstrip()

js = src[src.index('<script type="text/x-dc"'):]
js = js[js.index(">") + 1:js.index("</script>")]
body = js[js.index("componentDidMount(){") + len("componentDidMount(){"):]
body = body[:body.rindex("renderVals()")].rstrip()
body = body[:body.rindex("}")].rstrip()          # drop componentDidMount's closer

body = body.replace(
    "    const root = document.getElementById('px-root');\n    if(!root) return;\n", "")
body = body.replace("document.getElementById(", "root.getElementById(")

# ---- guards on the OUTPUT -------------------------------------------------
if "const root =" in body:
    sys.exit("FAIL: local root binding survived; it would shadow boot()'s parameter.")
if "document.getElementById" in body:
    sys.exit("FAIL: a document.getElementById survived the rewrite.")

font_links = re.findall(r'<link href="([^"]+)" rel="stylesheet">',
                        "\n".join(lines[:opens[0] + 30]))
fonts = "\n".join(
    "    var f%d=document.createElement('link'); f%d.rel='stylesheet'; f%d.href=%r; "
    "document.head.appendChild(f%d);" % (i, i, i, u, i)
    for i, u in enumerate(font_links))

OUT.write_text("""/* PARALLAXX TRANSFORMATIONS - Home page Wix Custom Element. Tag: parallaxx-home-page.
   GENERATED by build-home-bundle.py from "Parallaxx Home.dc.html".
   DO NOT EDIT THIS FILE - edit the .dc.html and rerun the build.
   In the Wix editor: turn the site Header + Footer OFF for this page. */
(function(){
  if (customElements.get('parallaxx-home-page')) return;

  var CSS = `%s`;

  var HTML = `%s`;

  function addFonts(){
    if (document.getElementById('px-fonts')) return;
    var p1=document.createElement('link'); p1.rel='preconnect'; p1.href='https://fonts.googleapis.com'; document.head.appendChild(p1);
    var p2=document.createElement('link'); p2.rel='preconnect'; p2.href='https://fonts.gstatic.com'; p2.crossOrigin=''; document.head.appendChild(p2);
%s
    /* @font-face has to live in the DOCUMENT, not the shadow root. Chrome
       ignores font-face rules declared inside a shadow tree. */
    var ff=document.createElement('style'); ff.id='px-fonts'; ff.textContent=`%s`; document.head.appendChild(ff);
  }

  function loadScript(src){
    return new Promise(function(res,rej){
      var ex=document.querySelector('script[data-px="'+src+'"]');
      if(ex){ if(ex.getAttribute('data-loaded')){res();} else { ex.addEventListener('load',function(){res();}); ex.addEventListener('error',rej);} return; }
      var s=document.createElement('script'); s.src=src; s.async=false; s.setAttribute('data-px',src);
      s.addEventListener('load',function(){ s.setAttribute('data-loaded','1'); res(); });
      s.addEventListener('error',rej);
      document.head.appendChild(s);
    });
  }

  function loadLibs(){
    var g=loadScript('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js')
      .then(function(){ return loadScript('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js'); });
    var l=loadScript('https://unpkg.com/lenis@1.1.13/dist/lenis.min.js');
    return Promise.all([ g.catch(function(){}), l.catch(function(){}) ]);
  }

  /* This rewrites ancestor heights, which moves every scroll position on the
     page. ScrollTrigger has already cached those positions, so without a
     refresh afterwards its triggers fire at the wrong offsets. Returns
     whether it actually changed anything so the caller can avoid refreshing
     for nothing. */
  function collapseAncestors(host){
    var changed = false;
    try{ var h=host.getBoundingClientRect().height; if(h<50) return false;
      var n=host.parentElement,guard=0;
      while(n && n!==document.body && guard++<14){ if(n.getBoundingClientRect().height>h+600){ n.style.height='auto'; n.style.minHeight='0px'; changed = true; } n=n.parentElement; }
    }catch(e){}
    return changed;
  }

  function collapseAndRefresh(host){
    var changed = collapseAncestors(host);
    if (changed && window.ScrollTrigger) {
      try{ window.ScrollTrigger.refresh(); }catch(e){}
    }
  }

  function boot(root){
    if(!root || !root.getElementById('px-root')) return;
%s
  }

  class ParallaxxHomePage extends HTMLElement {
    connectedCallback(){
      if (this._mounted) return; this._mounted = true;
      addFonts();
      var shadow = this.attachShadow({mode:'open'});
      shadow.innerHTML = '<style>'+CSS+'</style>'+HTML;
      var host = this;
      loadLibs().then(function(){ try{ boot(shadow); }catch(e){ console.error('[px] boot failed:', e); } })
        .catch(function(){ try{ boot(shadow); }catch(e){} });
      requestAnimationFrame(function(){ collapseAndRefresh(host); });
      [400,1200,2500].forEach(function(t){ setTimeout(function(){ collapseAndRefresh(host); }, t); });
      window.addEventListener('resize', function(){ collapseAndRefresh(host); }, {passive:true});
    }
  }
  customElements.define('parallaxx-home-page', ParallaxxHomePage);
})();
""" % (CSS, HTML, fonts, FONTFACE, body), encoding="utf-8")

print(f"built {OUT.name}  css={len(CSS)}  html={len(HTML)}  boot={len(body)}  fonts={len(font_links)}")
