#!/usr/bin/env python3
"""Wrap the Reconnected Man v2 preview as the Custom Element the site loads.

    Source URL  /parallaxx-reconnected-man.js
    Tag         parallaxx-reconnected-man

Supersedes build-reconnected-man-bundle.py, which read the Wix editor export
(The Reconnected Man.dc.html) and is kept beside this one so the old design can
still be rebuilt. Both write the SAME output file, so only one is current --
this one.

Modelled on build_bundle_v10.py, which does the same job for the other door, so
the two pages now share one architecture: light DOM, stylesheet scoped to
#rm-page, behaviour script using document.querySelector, and the nav and footer
as custom elements that attach their own shadow roots.

MEDIA IS ABSOLUTE ON PURPOSE. The bundle is injected into a page served from
parallaxxtransformations.com, so a relative /assets/... path resolves against
that host and 404s. Videos point at the Wix CDN ids the previous bundle already
used; the images added for this design ride on GitHub Pages, the same origin
this bundle is served from.
"""
import re, pathlib

HERE = pathlib.Path(__file__).parent
SRC  = HERE / "reconnected-man-v2-preview.html"
OUT  = HERE / "parallaxx-reconnected-man.js"
TAG  = "parallaxx-reconnected-man"

s = SRC.read_text(encoding="utf-8")

font_links = re.findall(r'<link[^>]*href="(https://fonts\.googleapis\.com[^"]+)"[^>]*>', s)
CSS  = "\n".join(re.findall(r"<style>([\s\S]*?)</style>", s))

body_start = s.index('<div id="rm-page"')
body_end   = s.index('<script>')
HTML = s[body_start:body_end].strip()
PAGE_JS = "\n;\n".join(re.findall(r"<script>([\s\S]*?)</script>", s))

# A lone backslash inside a template literal starts an escape sequence, and CSS
# content values like \2014 read as octal, which is a hard syntax error.
CSS  = CSS.replace("\\", "\\\\")
HTML = HTML.replace("\\", "\\\\")

for name, blob in (("CSS", CSS), ("HTML", HTML), ("PAGE_JS", PAGE_JS)):
    if "`" in blob or "${" in blob:
        raise SystemExit("FAIL: backtick or dollar-brace in %s breaks the template literal" % name)

FORM = "UxzzQRv0AbKKQZ0P9bau"
assert "rm-page" in HTML, "page root missing"
assert "parallaxx-nav" in HTML and "parallaxx-footer" in HTML, "chrome missing from the body"
assert HTML.count(FORM) == 3, "the form id must appear three times, got %d" % HTML.count(FORM)

# The annotation layer is a build-time thing and must never reach a browser.
for marker in ('class="note"', 'class="review-only"', 'class="bar-top"',
               'class="src"', 'class="pending"', 'IMAGE_SLOT_', '[CLIENT]', 'data:image'):
    if marker in HTML or marker in CSS:
        raise SystemExit("FAIL: %s is still in the build" % marker)

# A relative asset path silently 404s on the host domain. Catch it here rather
# than in a browser three days later.
for bad in re.findall(r'(?:src|poster|href)="(/assets/[^"]*)"', HTML) + re.findall(r'url\((["\']?)(/assets/[^)"\']*)', CSS):
    raise SystemExit("FAIL: relative asset path %r would 404 on the host domain" % (bad,))

print("media   %d wix video, %d github image, %d relative"
      % (HTML.count("video.wixstatic.com"),
         (HTML + CSS).count("parallaxxlifeco.github.io"),
         (HTML + CSS).count('"/assets/')))

bundle = """/* PARALLAXX TRANSFORMATIONS - The Reconnected Man. Tag: %(tag)s.
   GENERATED by build_bundle_man_v2.py from reconnected-man-v2-preview.html,
   which is the approved design. DO NOT EDIT THIS FILE, edit that one and rerun.

   Renders into the LIGHT DOM on purpose. The stylesheet is scoped to #rm-page
   and the behaviour script uses document.querySelector, so light DOM keeps the
   videos, the accordion, the modal and every reveal working as approved. */
(function () {
  if (customElements.get('%(tag)s')) return;

  var CSS = `%(css)s`;
  var HTML = `%(html)s`;

  function once(id, make) {
    if (document.getElementById(id)) return;
    var el = make(); el.id = id; document.head.appendChild(el);
  }

  function addHead() {
    once('rm-pre1', function () { var l = document.createElement('link'); l.rel = 'preconnect'; l.href = 'https://fonts.googleapis.com'; return l; });
    once('rm-pre2', function () { var l = document.createElement('link'); l.rel = 'preconnect'; l.href = 'https://fonts.gstatic.com'; l.crossOrigin = ''; return l; });
%(fonts)s
    once('rm-css', function () { var st = document.createElement('style'); st.textContent = CSS; return st; });
    if (!document.querySelector('meta[name="viewport"]')) {
      var mv = document.createElement('meta'); mv.name = 'viewport';
      mv.content = 'width=device-width, initial-scale=1'; document.head.appendChild(mv);
    }
  }

  function script(src, id) {
    if (document.getElementById(id)) return;
    var sc = document.createElement('script'); sc.id = id; sc.src = src; sc.async = false;
    document.head.appendChild(sc);
  }

  function boot() {
%(pagejs)s
  }

  var El = function () { return Reflect.construct(HTMLElement, [], El); };
  El.prototype = Object.create(HTMLElement.prototype);
  El.prototype.constructor = El;
  Object.setPrototypeOf(El, HTMLElement);

  El.prototype.connectedCallback = function () {
    if (this._rmUp) return;
    this._rmUp = true;
    addHead();
    this.innerHTML = HTML;
    script('/parallaxx-nav.js', 'rm-nav-js');
    script('/parallaxx-footer.js', 'rm-foot-js');
    script('https://link.msgsndr.com/js/form_embed.js', 'rm-ghl-js');
    try { boot(); } catch (e) { /* the page renders fully visible without it */ }
  };

  customElements.define('%(tag)s', El);
})();
""" % dict(
    tag=TAG, css=CSS, html=HTML, pagejs=PAGE_JS,
    fonts="\n".join(
        "    once('rm-font%d', function () { var l = document.createElement('link'); l.rel = 'stylesheet'; l.href = '%s'; return l; });"
        % (i, u) for i, u in enumerate(font_links)),
)

OUT.write_text(bundle, encoding="utf-8")
print("wrote %s  %d bytes  css=%d html=%d js=%d fonts=%d"
      % (OUT.name, len(bundle), len(CSS), len(HTML), len(PAGE_JS), len(font_links)))
