/* PARALLAXX TRANSFORMATIONS - Home page Wix Custom Element. Tag: parallaxx-home.
   GENERATED by build-home-bundle.py from "Parallaxx Home.dc.html".
   DO NOT EDIT THIS FILE - edit the .dc.html and rerun the build.
   In the Wix editor: turn the site Header + Footer OFF for this page. */
(function(){
  if (customElements.get('parallaxx-home')) return;

  var CSS = `/* ═══════════════════════════════════════════════════════════════════
   PARALLAXX - HOME (rebuilt 9 Oct 2026, "concept 2")
   -------------------------------------------------------------------
   ONE JOB: get the right person to /men or /women fast, and give them a
   reason to trust Daniel on the way past. Daniel's brief, 9 Oct: the home
   page is a door that filters men and women into the next page, kept
   short on mobile.

   THREE BLOCKS.
     01 HERO + DOORS  one line that sets up BOTH pages, then the doors.
                      Each door heading is the H1 of the page it opens,
                      word for word, so the click lands on the line they
                      just chose. Change a door page's H1, change it here.
     02 GIVE IT ALL   the credibility band. Daniel asked to keep it: it is
                      the reference to the wider world of experiences.
     03 ELSE          one quiet row for everybody who is neither.
     -- NAV / FOOTER  PtNav v3 and PtFooter v3, baked in as before.

   The previous six-block version (shared paragraph, record, close) is in
   git history before this commit if anything needs lifting back.

   TOKENS: navy #061938  gold #E8C65F  coral #FF501F  cream #F1ECE1
   THE ACCENT RULE. GOLD IS DANIEL. CORAL IS YOU.

   NO container-type ON #px-root OR ANY ANCESTOR OF #pt-nav. It makes the
   element a containing block for fixed descendants and the site nav
   would scroll away with the page.
   ═══════════════════════════════════════════════════════════════════ */
  :host{display:block;background:#061938}
  *{box-sizing:border-box}
  #px-root{background:#061938;color:#F1ECE1;
    font-family:'Montserrat',system-ui,-apple-system,sans-serif;
    -webkit-font-smoothing:antialiased;overflow-x:hidden}
  #px-root h1,#px-root h2,#px-root h3,#px-root h4,#px-root p{margin:0}
  #px-root h1,#px-root h2,#px-root h3{text-wrap:balance}
  #px-root p{text-wrap:pretty}
  #px-root img{display:block;max-width:100%}
  .px-serif{font-family:'Poppins','Montserrat',sans-serif;font-weight:300;letter-spacing:-.02em}
  .px-hand{font-family:'Lumios Marker','Permanent Marker',cursive;font-weight:400}
  .px-wrap{max-width:1180px;margin:0 auto;padding:0 clamp(16px,4vw,48px)}
  .px-arrow{display:inline-block;transition:transform .2s}
  a:hover .px-arrow{transform:translateX(4px)}

  @keyframes px-rise{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:none}}
  .px-rise{animation:px-rise .7s cubic-bezier(.22,.61,.36,1) both}
  .px-d1{animation-delay:.05s}.px-d2{animation-delay:.16s}
  .px-d3{animation-delay:.27s}.px-d4{animation-delay:.38s}
  @media(prefers-reduced-motion:reduce){.px-rise{animation:none}}

  /* ══ 01 HERO + DOORS ══ */
  #px-hero{position:relative;background:#061938;overflow:hidden}
  #px-hero .photo{position:absolute;top:0;right:0;bottom:0;width:46%}
  #px-hero .photo img{width:100%;height:100%;object-fit:cover;object-position:40% 25%}
  #px-hero .photo::after{content:"";position:absolute;inset:0;
    background:linear-gradient(90deg,#061938 0%,rgba(6,25,56,.6) 22%,rgba(6,25,56,0) 55%),
               linear-gradient(0deg,#061938 0%,rgba(6,25,56,0) 30%),
               linear-gradient(180deg,rgba(6,25,56,.8) 0,rgba(6,25,56,0) 170px)}
  /* the third gradient keeps the nav legible over the bright sky at the top */
  #px-hero .in{position:relative;z-index:2;padding-top:clamp(150px,18vh,200px);padding-bottom:clamp(56px,7vw,90px)}
  #px-hero .note{color:#E8C65F;font-size:1.3rem;display:inline-block;transform:rotate(-2deg);transform-origin:left;margin-bottom:16px}
  #px-hero h1{font-size:clamp(2.4rem,4.6vw,4.3rem);line-height:1.05;max-width:14ch}
  #px-hero .lede{margin-top:22px;font-size:clamp(1.02rem,1.3vw,1.15rem);line-height:1.65;color:#C4CEE0;max-width:36ch}

  #px-doors{margin-top:clamp(44px,6vw,72px);display:grid;grid-template-columns:1fr 1fr;gap:16px;max-width:800px}
  .px-door{display:flex;flex-direction:column;gap:14px;text-decoration:none;background:#F1ECE1;color:#1E2A3D;
    padding:clamp(22px,2.6vw,32px);border-radius:6px;transition:transform .25s,box-shadow .25s}
  .px-door:hover{transform:translateY(-3px);box-shadow:0 22px 44px -26px rgba(0,0,0,.7)}
  .px-door .tag{font-size:.72rem;letter-spacing:.2em;text-transform:uppercase;font-weight:700;color:#A08A5E}
  .px-door h2{font-size:clamp(1.3rem,2vw,1.65rem);line-height:1.2}
  .px-door .go{margin-top:auto;padding-top:6px;color:#FF501F;font-weight:600;font-size:.95rem}

  @media(max-width:860px){
    #px-hero .photo{position:relative;width:100%;height:40vh;min-height:280px}
    #px-hero .photo::after{background:linear-gradient(180deg,rgba(6,25,56,.35) 0%,rgba(6,25,56,0) 35%,#061938 100%)}
    #px-hero .in{padding-top:0;margin-top:-70px;padding-bottom:56px}
    #px-hero h1{font-size:2.3rem}
    #px-doors{grid-template-columns:1fr;gap:12px;margin-top:30px}
    .px-door{flex-direction:row;flex-wrap:wrap;align-items:baseline;gap:6px 12px;padding:20px}
    .px-door .tag{width:100%}
    .px-door h2{flex:1 1 60%;font-size:1.25rem}
    .px-door .go{margin:0;padding:0}
  }
  @media(max-width:360px){#px-hero h1{font-size:2rem}}

  /* ══ 02 GIVE IT ALL ══ */
  #px-gia{position:relative;min-height:520px;display:flex;align-items:flex-end;overflow:hidden}
  #px-gia > img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:30% 40%}
  #px-gia::after{content:"";position:absolute;inset:0;
    background:linear-gradient(90deg,rgba(3,14,34,.2) 0%,rgba(3,14,34,.55) 45%,rgba(3,14,34,.92) 75%),
               linear-gradient(0deg,rgba(3,14,34,.85) 0%,rgba(3,14,34,0) 45%)}
  #px-gia .px-wrap{position:relative;z-index:2;width:100%;display:flex;justify-content:flex-end;padding-top:80px;padding-bottom:64px}
  #px-gia .card{max-width:470px}
  #px-gia .note{color:#E8C65F;font-size:1.2rem;display:inline-block;transform:rotate(-2deg);margin-bottom:14px}
  #px-gia p{font-size:1.04rem;line-height:1.7;color:#F1ECE1}
  #px-gia p strong{font-weight:600}
  #px-gia dl{display:flex;gap:30px;margin:26px 0;padding:18px 0;border-top:1px solid rgba(241,236,225,.14);border-bottom:1px solid rgba(241,236,225,.14)}
  #px-gia dl div{margin:0}
  #px-gia dt{font-family:'Poppins',sans-serif;font-weight:300;font-size:2rem;color:#E8C65F;line-height:1}
  #px-gia dd{margin:8px 0 0;font-size:.64rem;letter-spacing:.18em;text-transform:uppercase;font-weight:700;color:#C4CEE0}
  #px-gia .links{display:flex;gap:24px;flex-wrap:wrap;font-weight:600;font-size:.92rem}
  #px-gia .links a{color:#F1ECE1;text-decoration:none;border-bottom:1.5px solid currentColor;padding-bottom:3px}
  #px-gia .links a.gold{color:#E8C65F}
  @media(max-width:760px){
    #px-gia{min-height:0;display:block}
    #px-gia > img{position:relative;height:260px}
    #px-gia::after{display:none}
    #px-gia .px-wrap{background:#030E22;padding-top:30px;padding-bottom:48px;display:block}
    #px-gia dl{gap:22px}
    #px-gia dt{font-size:1.6rem}
  }

  /* ══ 03 ELSE ══ */
  #px-else{background:#030E22;padding:30px 0 40px;text-align:center;font-size:.9rem;color:#C4CEE0}
  #px-else .lab{display:block;font-size:.68rem;letter-spacing:.2em;text-transform:uppercase;font-weight:700;margin-bottom:12px}
  #px-else a{white-space:nowrap;color:#F1ECE1;margin:0 12px;text-decoration:none;border-bottom:1px solid rgba(241,236,225,.35);line-height:2.2}

/*/* ══════════════════════════════════════════════════════════════════
   SITE NAV, BUILT IN RATHER THAN PLACED
   Same story as the footer below it. PtNav belongs in the Wix header
   strip so it is editable in one place for every page; it would not
   load there, so it ships inside this page.

   PtNav v3.dc.html stays the source of record. If the strip starts
   working, delete this block and the markup rather than maintaining
   two copies.

   ONE THING TO WATCH. The bar is position:fixed. Inside a shadow root
   that still resolves against the viewport, but ANY ancestor carrying
   transform, filter, perspective or will-change becomes its containing
   block instead, and the nav would scroll away with the page. If that
   happens in Wix, the culprit is a wrapper on Wix's side, not here.
   ══════════════════════════════════════════════════════════════════ */
/* ═══════════════════════════════════════════════════════════════════
   PARALLAXX · PRIMARY NAVIGATION · v3
   -------------------------------------------------------------------
   STRUCTURE (this is the whole argument of the redesign)
     LOGO          home. no "Home" text item — the mark does that job.
     FOR MEN   ▾   → The Reconnected Man
     FOR WOMEN ▾   → The Reconnected Woman
     ABOUT
     TESTIMONIALS
     CONTACT       coral pill, far right.

   WHY THE DOORS COME FIRST
   The sorting page's entire premise is that a visitor must choose a
   side before anything else can land. The nav has to agree with that.
   "For Men" and "For Women" are therefore the first and largest thing
   after the mark, and everything that is ABOUT DANIEL (About,
   Testimonials) sits after the reader's own doors, not before them.

   THE PARENTS ARE REAL LINKS
   "For Men" goes to the men's page; the dropdown is an addition, not
   the only way through. A nav item that can only be hovered is a dead
   end on touch and a dead end for keyboards.

   ───────────────────────────────────────────────────────────────────
   TOKENS shared with GIVE IT ALL:  navy #061938  gold #E8C65F  Montserrat
   TOKENS Parallaxx only:  coral #FF501F  Poppins  cream #F1ECE1

   THE ACCENT RULE. GOLD IS DANIEL. CORAL IS YOU.
   Gold marks where you ARE (the active item, the hovered child).
   Coral marks the one thing you can DO (Contact). Nothing else in
   this bar is allowed to be coral — the moment a second thing is,
   the pill stops meaning anything.
   ═══════════════════════════════════════════════════════════════════ */
:root{
  --px-navy:#061938;
  --px-navy-deep:#04122A;
  --px-navy-ink:#030C1C;
  --px-gold:#E8C65F;
  --px-gold-lift:#F3DD93;
  --px-coral:#FF501F;
  --px-coral-lift:#FF6A3D;
  --px-cream:#F1ECE1;
  --px-mist:#B1BFD7;
  --px-slate:#7C89A3;
}

/* ═══ SHELL ═══════════════════════════════════════════════════════ */
#pt-nav,#pt-nav *{box-sizing:border-box}
#pt-nav{
  position:fixed;top:0;left:0;right:0;z-index:90;
  font-family:'Montserrat',system-ui,-apple-system,sans-serif;
  border-bottom:1px solid transparent;
  background:transparent;
  transition:background .4s ease,border-color .4s ease;
  -webkit-font-smoothing:antialiased;
}
/* Navy on scroll. NEVER black. */
/* Solid, no backdrop-filter: inside a shadow root Chromium composites the
   filter against an already filtered backdrop and the page reads straight
   through a background that is 92% opaque. */
#pt-nav.is-stuck{
  background:#061938;
  border-bottom-color:rgba(232,198,95,.16);
}
#pt-bar{
  max-width:1360px;margin:0 auto;
  padding:16px clamp(20px,4vw,52px);
  display:flex;align-items:center;gap:clamp(16px,2.2vw,28px);
  position:relative;
}

/* ═══ LOGO ════════════════════════════════════════════════════════ */
#pt-logo{flex:0 0 auto;display:flex;align-items:center;line-height:0;
  border-radius:6px;text-decoration:none;transition:opacity .25s ease}
#pt-logo:hover{opacity:.82}
#pt-logo:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:6px}
/* If the CDN ever fails, the alt text renders as ordinary cream wordmark
   text rather than a giant blue underlined link. */
#pt-logo img{height:30px;width:auto;display:block;
  font-size:.82rem;font-weight:700;letter-spacing:.02em;color:#F1ECE1}
@media(max-width:600px){#pt-logo img{height:26px}}
/* 400px AND BELOW. At 360 the mark is 216px wide, the Contact pill is
   another 129 and the burger 40. Together with the gutters that is 28px
   more than the screen, so the pill ran off the right edge and took half
   the burger with it. A menu button you cannot reach is worse than any
   of the things it opens. Everything comes down a step. */
@media(max-width:400px){
  #pt-logo img{height:21px}
  /* The mark is an <img> with width:auto, so it normally scales with the
     height above. If the CDN fails it falls back to the alt text, which
     is a fixed 216px of wordmark and pushes the Contact pill and the
     burger off the right edge. This caps it either way. */
  #pt-logo{max-width:50vw;overflow:hidden}
  #pt-bar{padding:14px 16px;gap:10px}
  #pt-cta-wrap{gap:8px;margin-left:auto}
  #pt-cta{font-size:.78rem;padding:.62em 1.05em}
  #pt-burger{padding:6px;margin-right:-6px}
}

/* ═══ LINK RAIL ═══════════════════════════════════════════════════ */
#pt-links{
  display:flex;align-items:center;gap:clamp(20px,2.4vw,34px);
  margin-left:auto;
}
.pt-item{position:relative;display:flex;align-items:center}
.pt-link{
  display:inline-flex;align-items:center;gap:.35em;
  font-size:.9rem;font-weight:600;letter-spacing:.005em;
  color:#B1BFD7;white-space:nowrap;text-decoration:none;
  padding:6px 0;border-radius:4px;
  transition:color .2s ease;
}
.pt-link:hover,.pt-link:focus-visible{color:#F1ECE1;outline:none}
.pt-link:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:4px}

/* WHERE YOU ARE. Gold, plus a rule under it so it survives being
   read by someone who cannot separate gold from mist. */
.pt-item.is-active > .pt-link,
.pt-link.is-active{color:#E8C65F}
.pt-item.is-active > .pt-link::after,
.pt-link.is-active::after{
  content:"";position:absolute;left:0;right:0;bottom:-2px;height:2px;
  background:rgba(232,198,95,.75);border-radius:2px;
}
.pt-link{position:relative}

/* ═══ CARET + DROPDOWN ════════════════════════════════════════════ */
.pt-caret{
  background:none;border:none;padding:6px 2px;margin:0;
  font-family:inherit;font-size:.72em;line-height:1;
  color:inherit;cursor:pointer;
  display:inline-flex;align-items:center;
  transition:transform .25s ease,color .2s ease;
  color:#7C89A3;
}
.pt-item:hover .pt-caret{color:#B1BFD7}
.pt-caret:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:3px;border-radius:4px}
.pt-item:hover .pt-caret,
.pt-item.is-open .pt-caret{transform:rotate(180deg)}

.pt-menu{
  position:absolute;top:100%;left:50%;
  transform:translateX(-50%);
  min-width:252px;
  display:none;flex-direction:column;gap:2px;
  margin-top:14px;
  background:#04122A;
  border:1px solid rgba(232,198,95,.18);
  border-radius:14px;padding:10px;
  box-shadow:0 30px 60px -20px rgba(3,12,28,.8);
}
/* The 14px gap between the item and the menu would break a hover
   chain, so the bridge below keeps the pointer "inside" while it
   crosses. Without it the menu flickers shut mid-travel. */
.pt-menu::before{content:"";position:absolute;top:-16px;left:0;right:0;height:16px}

/* Desktop opens on hover AND on keyboard focus. No JS involved. */
@media(min-width:1024px){
  .pt-item:hover .pt-menu,
  .pt-item:focus-within .pt-menu,
  .pt-item.is-open .pt-menu{display:flex}
}
.pt-menu a{
  padding:11px 14px;border-radius:9px;
  font-size:.88rem;font-weight:500;color:#D7DEEA;
  white-space:nowrap;text-decoration:none;
  transition:background .2s ease,color .2s ease;
}
.pt-menu a:hover,.pt-menu a:focus-visible{
  background:rgba(232,198,95,.1);color:#E8C65F;outline:none}
.pt-menu a:focus-visible{box-shadow:inset 0 0 0 1px rgba(232,198,95,.55)}
.pt-menu .pt-sub{
  display:block;font-size:.63rem;letter-spacing:.18em;text-transform:uppercase;
  font-weight:800;color:#7C89A3;margin-bottom:3px}
.pt-menu a:hover .pt-sub{color:rgba(232,198,95,.72)}

/* ═══ CONTACT · THE ONLY CORAL IN THE BAR ═════════════════════════ */
#pt-cta-wrap{display:flex;align-items:center;gap:14px;flex:0 0 auto;margin-left:clamp(8px,1.6vw,20px)}
#pt-cta{
  display:inline-flex;align-items:center;gap:.5em;
  background:#FF501F;color:#FFFFFF;
  font-weight:700;font-size:.86rem;
  padding:.72em 1.45em;border-radius:999px;
  white-space:nowrap;text-decoration:none;
  transition:background .25s ease,transform .25s ease,box-shadow .25s ease;
}
#pt-cta:hover,#pt-cta:focus-visible{
  background:#FF6A3D;transform:translateY(-1px);
  box-shadow:0 10px 24px -10px rgba(255,80,31,.7);outline:none}
#pt-cta:focus-visible{outline:2px solid #F3DD93;outline-offset:3px}
#pt-cta .arrow{font-size:.9em;transition:transform .25s ease}
#pt-cta:hover .arrow{transform:translateX(3px)}

/* ═══ BURGER ══════════════════════════════════════════════════════ */
#pt-burger{
  display:none;background:none;border:none;cursor:pointer;
  flex-direction:column;justify-content:center;gap:5px;
  padding:8px;margin-right:-8px;border-radius:6px}
#pt-burger:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:2px}
#pt-burger span{display:block;width:24px;height:2px;background:#F1ECE1;border-radius:2px;
  transition:transform .3s ease,opacity .2s ease}
#pt-nav.menu-open #pt-burger span:nth-child(1){transform:translateY(7px) rotate(45deg)}
#pt-nav.menu-open #pt-burger span:nth-child(2){opacity:0}
#pt-nav.menu-open #pt-burger span:nth-child(3){transform:translateY(-7px) rotate(-45deg)}

/* ═══ MOBILE ══════════════════════════════════════════════════════ */
@media(max-width:1023px){
  #pt-burger{display:flex}
  #pt-nav{background:#061938}

  #pt-links{
    position:absolute;top:100%;left:0;right:0;
    flex-direction:column;align-items:stretch;gap:2px;
    margin-left:0;
    /* SOLID, AND NO BACKDROP FILTER ON THIS ONE. The bar above keeps its
       blur; this panel cannot have one. Nested backdrop-filters inside a
       shadow root make Chromium composite this element against an already
       filtered backdrop, and the page behind reads straight through a
       background that is 98.5% opaque. On the built-in version of this nav
       the hero headline was legible through the open menu. The bar's own
       blur still gives the effect where it matters. */
    background:#061938;
    border-bottom:1px solid rgba(232,198,95,.16);
    padding:10px clamp(16px,4vw,44px) 22px;
    max-height:calc(100vh - 68px);overflow-y:auto;
    display:none;
  }
  #pt-nav.menu-open #pt-links{display:flex}

  .pt-item{flex-wrap:wrap;justify-content:space-between;
    border-bottom:1px solid rgba(241,236,225,.07)}
  .pt-item:last-child{border-bottom:none}
  .pt-link{flex:1 1 auto;padding:15px 2px;font-size:1rem}
  .pt-item.is-active > .pt-link::after,.pt-link.is-active::after{display:none}
  /* The caret was #7C89A3 at .85em: the same grey as inactive text, on a
     control people are meant to notice and press. On a phone it read as
     punctuation, not a button. Gold picks it out of the row, the stroke
     gives the glyph weight a font-weight cannot (it is a symbol, and the
     face has no bolder cut of it), and the ring makes the tap target
     visible so it is obvious there is more underneath. */
  .pt-caret{
    flex:0 0 auto;padding:11px 12px;font-size:1.02em;
    color:#E8C65F;-webkit-text-stroke:.6px #E8C65F;
    border:1px solid rgba(232,198,95,.34);border-radius:999px;
    margin-left:6px;
  }
  .pt-item.is-open .pt-caret{
    color:#F4E1A2;-webkit-text-stroke:.6px #F4E1A2;
    background:rgba(232,198,95,.14);border-color:rgba(232,198,95,.62)}

  /* Child list is a plain indented block on mobile. A floating panel
     inside a panel is a place to get lost. */
  .pt-menu{
    position:static;transform:none;min-width:0;width:100%;
    margin:0 0 12px;padding:0 0 0 14px;
    background:transparent;backdrop-filter:none;-webkit-backdrop-filter:none;
    border:none;border-left:2px solid rgba(232,198,95,.28);
    border-radius:0;box-shadow:none;
    flex-basis:100%;
  }
  .pt-menu::before{display:none}
  .pt-item.is-open .pt-menu{display:flex}
  .pt-menu a{padding:12px 12px;font-size:.94rem}

  #pt-cta-wrap{margin-left:auto}
  #pt-cta{font-size:.8rem;padding:.68em 1.2em}
  #pt-cta .cta-long{display:none}
}
@media(max-width:420px){
  #pt-cta{padding:.66em 1.05em}
  #pt-cta .arrow{display:none}
}


/* ═══ THE 320px BAR ═══════════════════════════════════════════════
   At 320 the logo, the Contact pill and the burger add up to more than
   the bar, and the burger hangs 9px off the right edge. Nothing here is
   a redesign: the logo loses 4px, the bar loses 6px of padding either
   side, and the pill tightens. Added 4 Aug 2026 to all three pages and
   to PtNav v3.dc.html, which stays the source of record. */
@media(max-width:360px){
  #pt-bar{padding-left:14px;padding-right:14px;gap:10px}
  #pt-logo img{height:22px}
  #pt-cta{padding:.6em .82em;font-size:.8rem}
  #pt-burger{width:34px;margin-right:-4px}
}

@media(prefers-reduced-motion:reduce){
  #pt-nav,#pt-nav *{transition:none!important}
}

/*    SITE FOOTER, BUILT IN RATHER THAN PLACED
   PtFooter is its own custom element and is meant to sit once in the
   Wix footer strip, which is what makes it editable in one place for
   every page. It would not load there, so it ships inside this page
   instead. That is a real cost and it should be written down: this
   copy of the footer will not track PtFooter v3.dc.html. Change one
   and the other does not move.

   PtFooter v3.dc.html stays the source of record. If it starts loading
   in Wix again, delete this block and the markup at the foot of the
   page rather than maintaining two.

   Every selector here is pt- prefixed and nothing in the page uses that
   prefix, so the two sheets do not touch.
   ══════════════════════════════════════════════════════════════════ */
/* ═══════════════════════════════════════════════════════════════════
   PARALLAXX · SITE FOOTER · v3  ·  THREE COLUMNS + UTILITY ROW
   -------------------------------------------------------------------
   THE PROBLEM WITH v2
   Twenty-four links in four equal columns. Every one of them the same
   size, the same colour, the same weight. On a site whose entire
   premise is "pick one of two doors", the last thing on the page was
   a sitemap that made twenty-four things look equally important.

   THE FIX IS NOT FEWER LINKS. IT IS HIERARCHY.
   Seven pages on this site are linked from NOWHERE except this footer:
   Blog, both podcasts, Progress Journal, Three Toxic Lies, Identity
   2.0, As Seen In. Delete them from here and they are orphaned:
   unreachable by a human, and invisible to search because nothing
   points at them. So they stay. They just stop shouting.

   WHAT THE VISITOR SEES NOW
     THREE COLUMNS, LARGE   the two doors, then Daniel. nine links.
                            the whole site, as far as anyone arriving
                            cares.
     ONE QUIET ROW, SMALL   everything else, inline, dot-separated,
                            in the register of a footnote rather than
                            a menu. Reachable. Not competing.

   Reading order does the work: doors first at full weight, then the
   row you only look at if you were already looking for something
   specific, then legal. Each tier is quieter than the one above it.

   WHY THERE IS NO BLURB UNDER THE LOGO
   A footer does not need to restate the pitch. Everything above it has
   already spoken, and by the time anyone is down here they are looking
   for a link, not for the argument again.

   WHY THE GIVE IT ALL BANNER IS GONE
   It was a full-width tinted panel with a badge and two lines of copy,
   for a brand that reads as a men's event. Under a footer that serves
   two avatars it was the single loudest thing on the page, and it was
   shouting at half the audience. It is now one gold line in Daniel's
   column, which is the correct size for a sibling brand.

   ───────────────────────────────────────────────────────────────────
   TOKENS shared with GIVE IT ALL:  navy #061938  gold #E8C65F  Montserrat
   TOKENS Parallaxx only:  coral #FF501F  Poppins  cream #F1ECE1

   THE ACCENT RULE. GOLD IS DANIEL. CORAL IS YOU.
   There is NO coral down here, on purpose. Coral marks the reader's
   move, and every ask has already been made: the nav carries a coral
   Contact pill on every page, and the page above closes with its own.
   GIVE IT ALL is gold, because it is his world, not your move.
   ═══════════════════════════════════════════════════════════════════ */
:root{
  --px-navy:#061938;
  --px-navy-deep:#04122A;
  --px-navy-ink:#030C1C;
  --px-gold:#E8C65F;
  --px-gold-lift:#F3DD93;
  --px-coral:#FF501F;
  --px-coral-lift:#FF6A3D;
  --px-cream:#F1ECE1;
  --px-mist:#B1BFD7;
  --px-slate:#7C89A3;
}

#pt-foot,#pt-foot *{box-sizing:border-box}
#pt-foot{
  background:#030C1C;
  border-top:1px solid rgba(232,198,95,.16);
  font-family:'Montserrat',system-ui,-apple-system,sans-serif;
  color:#B1BFD7;-webkit-font-smoothing:antialiased}
#pt-foot-inner{max-width:1360px;margin:0 auto;
  padding:clamp(34px,3.6vw,46px) clamp(20px,4vw,52px) 24px}

/* ═══ TIER 1 · IDENTITY + THE THREE COLUMNS ═══════════════════════
   Two doors and Daniel. The doors are the reader's two routes in;
   the third is everywhere Daniel himself shows up, which is what the
   GIVE IT ALL bar used to be doing at ten times the size. */
#pt-foot-top{
  display:grid;
  grid-template-columns:minmax(260px,1fr) repeat(3,minmax(0,.72fr));
  gap:clamp(30px,3.4vw,52px);
  align-items:start;
  margin-bottom:clamp(28px,3vw,36px)}
/* Identity spans the full width once the columns need the room. */
@media(max-width:1080px){#pt-foot-top{grid-template-columns:repeat(3,minmax(0,1fr));gap:38px 30px}
  #pt-ident{grid-column:1/-1}}
/* THREE COLUMNS ALL THE WAY DOWN. This used to fall to two at 680 and to
   one at 440, which on a 390px phone made the footer 878px tall, taller
   than most of the sections above it and by a long way the tallest thing
   nobody came for. Held at three it is 563px, a third shorter, and the
   two-up version was the worst of both: it put Daniel alone on a row and
   left half of it empty.

   Holding three also keeps the footer the same object it is on desktop.
   Three doors, three columns, whatever the device. The type comes down
   at the bottom breakpoint to buy the width, which is the right trade
   for a block that is scanned rather than read. */
@media(max-width:680px){#pt-foot-top{gap:30px 20px}}
@media(max-width:440px){
  #pt-foot-top{gap:22px 12px}
  .pt-door h4{font-size:.6rem;letter-spacing:.12em;margin-bottom:10px;padding-bottom:8px}
  .pt-door a{font-size:.78rem;line-height:1.28;padding:4px 0}
}
#pt-foot-logo{display:inline-block;line-height:0;margin-bottom:14px;text-decoration:none}
#pt-foot-logo img{height:30px;width:auto;display:block;
  font-size:.8rem;font-weight:700;color:#F1ECE1}

#pt-social{display:flex;gap:18px;flex-wrap:wrap;margin-top:16px}
#pt-social a{font-size:.85rem;font-weight:600;color:#B1BFD7;
  text-decoration:none;transition:color .2s ease}
#pt-social a:hover,#pt-social a:focus-visible{color:#E8C65F;outline:none}

/* ── THE DOORS. Deliberately larger than anything else down here. ── */
.pt-door h4{
  font-size:.68rem;letter-spacing:.18em;text-transform:uppercase;
  font-weight:800;color:#A88F4E;margin:0 0 12px;
  padding-bottom:9px;border-bottom:1px solid rgba(232,198,95,.18)}
/* THE WHOLE BLOCK IS DELIBERATELY SHALLOW. Nothing down here is being
   sold. It exists so that seven otherwise-orphaned pages are reachable
   and so somebody hunting for terms or a podcast can find them. Every
   vertical value in this file was cut roughly a third for that reason,
   and the type went with it. If it starts feeling like a section again,
   it has grown.

   .92rem, not 1.02. At 1.02 these matched the page's body copy exactly,
   which made the footer read as another content section rather than as
   the foot of the page. They are still the largest thing down here, and
   still clearly larger than the utility row at .82, so the hierarchy the
   note above describes is intact. The size came off the type and went
   into padding instead, so the tap target grew rather than shrank.

   margin-bottom went 1px -> 9px on 5 Aug. The padding already made each
   link a decent target, but stacked with 1px between them the boxes
   were effectively continuous, so an imprecise tap in a column landed
   on a neighbour rather than on nothing. The targets are the same size;
   there is simply somewhere to miss now. */
.pt-door a{
  display:block;color:#D7DEEA;font-size:.92rem;font-weight:500;
  line-height:1.3;padding:5px 0;margin-bottom:9px;text-decoration:none;
  border-radius:3px;transition:color .2s ease}
.pt-door a:first-of-type{padding-top:0}
.pt-door a:last-child{margin-bottom:0}
.pt-door a:hover,.pt-door a:focus-visible{color:#E8C65F;outline:none}

/* THE SIBLING BRAND, AS A LINE RATHER THAN A BANNER.
   It stays GOLD, because gold is Daniel and GIVE IT ALL is his room.
   That single colour is now the whole signal — it used to be a
   42px badge, a border, a tinted panel and two lines of body copy,
   which made a men's-retreat brand the loudest thing in a footer
   serving two avatars. */
.pt-door a.ext{color:#E8C65F;font-weight:600}
.pt-door a.ext:hover,.pt-door a.ext:focus-visible{color:#F3DD93}
.pt-door a.ext .mk{font-size:.8em;margin-left:.35em;opacity:.8}

/* ═══ TIER 2 · THE UTILITY ROW ════════════════════════════════════
   Everything the site has that is not a door. Small, inline, dot
   separated. This is the register of a footnote, and that is the
   point: it is here for the person who came looking for it, and
   invisible to the person who did not. */
/* SPACING, NOT SIZE. Measured on a 390px viewport, adjacent links in
   this row sat 0px apart: the dot separator is an ::after INSIDE the
   anchor, so each link's hit box ran all the way to the next one's.
   Nothing here is too small to hit; the problem was that a near miss
   could not miss. A thumb aimed at "Blog" drifting three pixels right
   opened "Progress Journal", and a wrong destination is worse than a
   dead tap, because there is no retry, only a back button.

   So the dot now hugs the link it belongs to and the flex gap carries
   the separation. Visually the row is within a couple of pixels of
   where it was. Between the hit boxes there is now 18px of nothing. */
#pt-util{
  display:flex;flex-wrap:wrap;align-items:center;
  gap:9px 18px;
  padding-top:18px;border-top:1px solid rgba(241,236,225,.1);
  margin-bottom:14px}
#pt-util a{
  color:#6E7B94;font-size:.82rem;text-decoration:none;
  padding:3px 0;border-radius:3px;white-space:nowrap;
  transition:color .2s ease}
#pt-util a:hover,#pt-util a:focus-visible{color:#E8C65F;outline:none}
/* Separator TRAILS its link rather than leading the next one. With
   ::before, every line the row wraps onto opens with an orphaned dot.
   Trailing means a wrapped line starts on a word, which is what the
   eye expects, and the dot left at a line end reads as continuation. */
#pt-util a:not(:last-child)::after{
  content:"·";color:#3E4A63;margin:0 0 0 9px;display:inline-block}

/* ═══ TIER 3 · LEGAL ══════════════════════════════════════════════ */
#pt-legal{
  display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;
  color:#5E6B85;font-size:.8rem;line-height:1.6}
#pt-legal .links{display:inline-flex;gap:18px;flex-wrap:wrap}
#pt-legal a{color:inherit;text-decoration:none;
  border-bottom:1px solid rgba(232,198,95,.4);padding-bottom:1px;
  transition:color .2s ease,border-color .2s ease}
#pt-legal a:hover,#pt-legal a:focus-visible{
  color:#B1BFD7;border-bottom-color:#E8C65F;outline:none}

/* ═══ THE JUMBLE, AND WHY THREE COLUMNS WAS NOT THE PROBLEM ═══════
   Held at three columns a 390px phone gives each one 109px, and at
   109px "The Reconnected Man" takes three lines while "About" takes
   one. Every column therefore started its second link at a different
   height, its third at a different height again, and nothing in the
   block lined up with anything beside it. Read top to bottom it is
   three tidy lists; read across -- which is how anybody actually
   looks at a footer -- it was rubble.

   THE FIX IS ALIGNMENT, NOT FEWER COLUMNS. Dropping to two columns
   was tried before and rejected in the note above for good reasons,
   and it would not have fixed this: two ragged columns are still
   ragged. Each column becomes a SUBGRID of the footer's own rows, so
   row 2 is the same height in all three columns whether its link
   wrapped to one line or three. The heading rule, the first link and
   the last link now sit on the same three lines across the block.

   Browsers without subgrid (pre-2023) ignore the declaration and get
   exactly today's layout, which is the correct fallback.

   The utility row loses its dot separators and becomes two columns at
   the same breakpoint. Ten dot-separated links wrapping freely across
   a phone put separators at the ends of lines and orphaned "As Seen
   In" on a line of its own; two columns is a list, and a list is what
   it is. Dots return above 560px where the row fits in two lines.

   THE BLOCK ALSO HAS TO SIT HERE, AFTER .pt-door a, AND THAT IS A BUG
   BEING FIXED RATHER THAN A HOUSE STYLE. The existing max-width:440
   rule is written ABOVE the base .pt-door a declaration, and a media
   query does not raise specificity -- the later rule wins at every
   width. So its .78rem never applied on any phone: the columns have
   always been rendering .92rem links inside 109px, which is most of
   why they wrapped three deep. The size drops again below, from a
   position where it can actually win. Leave this block last. */
/* THE COLUMNS WRAP TO THE WORD, WHICH IS WHY THEY LOOK LIKE THEY RUN
   INTO EACH OTHER · 10 Aug. Aligning the rows fixed the raggedness but
   not the cause. At 109px and .79rem, "The Reconnected" is 115px wide,
   so it cannot share a line with anything: the column breaks after
   "The", then after "Reconnected", and three one-word lines beside
   three one-word lines reads as one field of loose words rather than
   as three lists. Nothing is actually overflowing its column -- it
   just looks that way, which for this purpose is the same thing.

   THE THRESHOLD IS "The Reconnected" FITTING ON A LINE. That string is
   9.1x its own font size, so the column needs the type at or under
   11.75px. 3.2cqw of the footer's own width lands on 11.2, and cqw is
   used here for the same reason as the page sheet above: the widget is
   not the viewport, and vw cannot see what Wix took.

   The column gap goes 12 -> 14 in the same breath. Twelve pixels
   between two columns of wrapped text is not enough white to separate
   them, and that is the other half of "runs into the next column". */
@media(max-width:560px){
  #pt-foot-top{grid-template-rows:auto repeat(5,auto);row-gap:22px;
    container-type:inline-size;column-gap:14px}
  .pt-door{display:grid;grid-template-rows:subgrid;grid-row:2/span 5;
    row-gap:9px;align-content:start}
  .pt-door h4{font-size:clamp(8.5px,2.6cqw,10px);letter-spacing:.1em;padding-bottom:8px;
    margin-bottom:0;align-self:end}
  .pt-door a{font-size:clamp(8.8px,3.2cqw,12.6px);line-height:1.32;padding:3px 0;
    margin-bottom:0;align-self:start}
  #pt-social{gap:14px}
  #pt-social a{font-size:.78rem}
  /* ══ THE FOOTNOTE ROWS WERE LOUDER THAN THE DOORS · 10 Aug ══
     .pt-door a came down to 3.2cqw here to buy the three columns
     their width, and nothing underneath it followed. The utility row
     stayed at .82rem and the legal line at .8rem, so on a 390px phone
     the grey links rendered at 13.1px and 12.8px against door links
     at 11.2 -- the least important type in the footer set two pixels
     LARGER than the most important, which is the whole tier order
     inverted by a breakpoint that only remembered one of its rules.

     Fixed by measuring all three rows against the SAME container
     rather than against the viewport, which this sheet has already
     learned Wix does not hand the component:
         doors   3.2cqw    ~11.2px
         util    2.85cqw   ~10.0px
         legal   2.7cqw     ~9.5px
     #pt-foot-inner becomes the container for the two rows that sit
     OUTSIDE #pt-foot-top. Its content box is exactly #pt-foot-top's
     width -- the padding is on the inner, the top row has none -- so
     one cqw means the same thing in all three rules and the ratios
     hold at every width instead of only at the one they were read
     off. Ceilings sit just under the desktop sizes so nothing jumps
     at the breakpoint. ══ */
  #pt-foot-inner{container-type:inline-size}
  #pt-util{display:grid;grid-template-columns:1fr 1fr;gap:2px 14px;
    align-items:start}
  #pt-util a{white-space:normal;line-height:1.35;padding:5px 0;
    font-size:clamp(8px,2.85cqw,11.2px)}
  #pt-util a:not(:last-child)::after{content:none}
  #pt-legal{font-size:clamp(7.6px,2.7cqw,10.6px);gap:10px;line-height:1.55}
}

#pt-foot a:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:3px}
@media(prefers-reduced-motion:reduce){#pt-foot,#pt-foot *{transition:none!important}}`;

  var HTML = `<div id="px-root">

<header id="pt-nav">
  <div id="pt-bar">

    <!-- ══ LOGO = HOME. No text "Home" item; the mark is the link. ══ -->
    <a id="pt-logo" href="https://www.parallaxxtransformations.com" aria-label="Parallaxx Transformations — home">
      <img src="https://static.wixstatic.com/media/e1784d_fe3c841c471f47d088f0cd631a89d883~mv2.png"
           alt="Parallaxx Transformations">
    </a>

    <nav id="pt-links" aria-label="Primary">

      <!-- ══ FOR MEN ══ parent is a real link to the men's page ══ -->
      <div class="pt-item pt-has-drop" data-nav="men">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/men">For Men</a>
        <button class="pt-caret" type="button" aria-label="Show For Men menu" aria-expanded="false" aria-controls="pt-menu-men">&#9662;</button>
        <div class="pt-menu" id="pt-menu-men">
          <a href="https://www.parallaxxtransformations.com/men">Start Here</a>
          <a href="https://www.parallaxxtransformations.com/the-reconnected-man">The Reconnected Man</a>
        </div>
      </div>

      <!-- ══ FOR WOMEN ══ -->
      <div class="pt-item pt-has-drop" data-nav="women">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/women">For Women</a>
        <button class="pt-caret" type="button" aria-label="Show For Women menu" aria-expanded="false" aria-controls="pt-menu-women">&#9662;</button>
        <div class="pt-menu" id="pt-menu-women">
          <a href="https://www.parallaxxtransformations.com/women">Start Here</a>
          <a href="https://www.parallaxxtransformations.com/the-reconnected-woman">The Reconnected Woman</a>
        </div>
      </div>

      <div class="pt-item" data-nav="about">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/about-daniel-lawson">About</a>
      </div>

      <div class="pt-item" data-nav="testimonials">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/testimonials-daniel-lawson">Testimonials</a>
      </div>

    </nav>

    <div id="pt-cta-wrap">
      <!-- CONTACT. Coral pill — Parallaxx-only accent. GIA uses a gold
           pill in this exact position: same shape, different colour.
           That is the whole family/identity trick. -->
      <a id="pt-cta" data-nav="contact" href="https://www.parallaxxtransformations.com/contact-daniel-lawson">
        Contact<span class="cta-long">&nbsp;</span><span class="arrow" aria-hidden="true">&#8594;</span>
      </a>
      <button id="pt-burger" type="button" aria-label="Menu" aria-expanded="false" aria-controls="pt-links">
        <span></span><span></span><span></span>
      </button>
    </div>

  </div>
</header>

<!-- ══════════════ 01 · HERO + DOORS ══════════════
     The H1 sets up BOTH pages: each door page opens on a version of
     handling it all on your own. The door headings are those pages' H1s
     verbatim (/men "You handled it all yourself. That's the distance.",
     /women "You've hit every target. And you're still behind."). Keep
     them in step. Second person on both, never a he beside a she. -->
<section id="px-hero">
  <div class="photo"><img src="https://static.wixstatic.com/media/111174_36d2347a86fd4315b960a3f1082c14af~mv2.jpg" alt="Daniel Lawson" loading="eager" fetchpriority="high"></div>
  <div class="px-wrap in">
    <span class="note px-hand px-rise px-d1">if this is you</span>
    <h1 class="px-serif px-rise px-d2">Coaching for people who handle it all on their own.</h1>
    <p class="lede px-rise px-d3">Ask how you&rsquo;re doing and you say fine. Or busy. Same answer for years.</p>
    <div id="px-doors">
      <a class="px-door px-rise px-d3" href="https://www.parallaxxtransformations.com/men">
        <span class="tag">For men</span>
        <h2 class="px-serif">You handled it all yourself. That&rsquo;s the distance.</h2>
        <span class="go">This is me <span class="px-arrow" aria-hidden="true">&#8594;</span></span>
      </a>
      <a class="px-door px-rise px-d4" href="https://www.parallaxxtransformations.com/women">
        <span class="tag">For women</span>
        <h2 class="px-serif">You&rsquo;ve hit every target. And you&rsquo;re still behind.</h2>
        <span class="go">This is me <span class="px-arrow" aria-hidden="true">&#8594;</span></span>
      </a>
    </div>
  </div>
</section>

<!-- ══════════════ 02 · GIVE IT ALL ══════════════
     Kept at Daniel's request, 9 Oct 2026: credibility and the reference
     to the wider world of experiences. Numbers ruled 3 Aug 2026. The
     hand line was "who's holding it"; "holding" is on the voice skill's
     internal-vocabulary list. -->
<section id="px-gia">
  <img src="https://static.wixstatic.com/media/111174_ad3e5fa47d294ff890516b996bbd2d3c~mv2.jpg" alt="Daniel Lawson facilitating a GIVE IT ALL evening" loading="lazy" decoding="async">
  <div class="px-wrap">
    <div class="card">
      <span class="note px-hand">who you&rsquo;ll be with</span>
      <p>I&rsquo;m <strong>Daniel Lawson</strong>. Credentialled through the <strong>International Coach Guild</strong>, qualified through over half a decade of client results, and the founder of <strong>GIVE IT ALL</strong> world of experiences.</p>
      <dl>
        <div><dt>1000+</dt><dd>Lives changed</dd></div>
        <div><dt>9</dt><dd>Countries</dd></div>
        <div><dt>6+</dt><dd>Years facilitating</dd></div>
      </dl>
      <div class="links">
        <a href="https://www.parallaxxtransformations.com/about-daniel-lawson">How I got here <span class="px-arrow" aria-hidden="true">&#8594;</span></a>
        <a class="gold" href="https://giveitallevent.com">GIVE IT ALL experiences <span class="px-arrow" aria-hidden="true">&#8594;</span></a>
      </div>
    </div>
  </div>
</section>

<!-- ══════════════ 03 · NEITHER OF THOSE ══════════════ -->
<section id="px-else">
  <span class="lab">Here for something else?</span>
  <a href="https://www.parallaxxtransformations.com/daniel-lawson-speaking">Speaking</a><a href="https://www.parallaxxtransformations.com/insights/">Insights</a><a href="https://www.parallaxxtransformations.com/parallaxx-perspectives-podcast">The podcast</a><a href="https://www.parallaxxtransformations.com/ptjournal">The journal</a>
</section>

<footer id="pt-foot">
  <div id="pt-foot-inner">

    <div id="pt-foot-top">

      <!-- ══ IDENTITY ══ The mark and the four places he posts. No
           paragraph, no CTA: both were cut, and the column is better
           for it. ══ -->
      <div id="pt-ident">
        <a id="pt-foot-logo" href="https://www.parallaxxtransformations.com" aria-label="Parallaxx Transformations — home">
          <img src="https://static.wixstatic.com/media/e1784d_fe3c841c471f47d088f0cd631a89d883~mv2.png"
               alt="Parallaxx Transformations" loading="lazy">
        </a>
        <nav id="pt-social" aria-label="Social">
          <a href="https://www.youtube.com/@ReconnectYou1/featured" target="_blank" rel="noopener">YouTube</a>
          <a href="https://www.linkedin.com/in/daniel-reconnect-you/" target="_blank" rel="noopener">LinkedIn</a>
          <a href="https://www.instagram.com/daniel.lawson__/" target="_blank" rel="noopener">Instagram</a>
          <a href="https://www.facebook.com/Kiwi.Daniel" target="_blank" rel="noopener">Facebook</a>
        </nav>
      </div>

      <!-- ══ THE TWO DOORS ══ Same names, same order as the nav. ══ -->
      <nav class="pt-door" aria-label="For men">
        <h4>For Men</h4>
        <a href="https://www.parallaxxtransformations.com/men">Start here</a>
        <a href="https://www.parallaxxtransformations.com/the-reconnected-man">The Reconnected Man</a>
        <!-- THE ARCHETYPE QUIZ LIVES AT /the-archetype-quiz.
             This pointed at /reconnect until 24 Aug 2026, with a comment
             above it asserting that /reconnect WAS the quiz. It never was.
             /reconnect was the Reconnect programme -- a fourteen week,
             invitation-only pathway -- and it 301s to the home page. So the
             footer on every page of the site carried a link labelled "The
             Archetype Quiz" that landed on the home page, and a comment
             that would have talked the next person out of fixing it. The
             label was always right; the URL was always wrong. -->
        <a href="https://www.parallaxxtransformations.com/the-archetype-quiz">The Archetype Quiz</a>
      </nav>

      <nav class="pt-door" aria-label="For women">
        <h4>For Women</h4>
        <a href="https://www.parallaxxtransformations.com/women">Start here</a>
        <a href="https://www.parallaxxtransformations.com/the-reconnected-woman">The Reconnected Woman</a>
        <!-- [CLIENT] /priority-audit is the URL the women's home page
             CTA uses. Confirm the page is live before publishing. -->
        <a href="https://www.parallaxxtransformations.com/priority-audit">The Priority Audit</a>
      </nav>

      <!-- ══ DANIEL ══ Not a door. The three places he shows up in
           person, smallest commitment first. GIVE IT ALL is the last
           of them rather than a banner of its own. ══ -->
      <nav class="pt-door" aria-label="Daniel">
        <h4>Daniel</h4>
        <a href="https://www.parallaxxtransformations.com/about-daniel-lawson">About</a>
        <a href="https://www.parallaxxtransformations.com/daniel-lawson-speaking">Speaking</a>
        <!-- [CLIENT] No facilitating page exists on the site yet. This
             URL is a guess and must be confirmed or repointed. -->
        <a href="https://www.parallaxxtransformations.com/facilitating">Facilitating</a>
        <a class="ext" href="https://giveitallevent.com" target="_blank" rel="noopener">GIVE IT ALL<span class="mk" aria-hidden="true">&#8599;</span></a>
      </nav>

    </div>

    <!-- ══ THE UTILITY ROW ══
         Ordered by who asks for it: the person, then the work he makes,
         then the proof. Seven of these are linked from nowhere else on
         the site, which is exactly why the row exists. ══ -->
    <nav id="pt-util" aria-label="More">
      <a href="https://www.parallaxxtransformations.com/book-a-call-with-daniel-lawson">Book a Call</a>
      <a class="ext" href="https://www.youtube.com/@ReconnectYou1/featured" target="_blank" rel="noopener">Reconnect You Podcast<span class="mk" aria-hidden="true">&#8599;</span></a>
      <a href="https://www.parallaxxtransformations.com/parallaxx-perspectives-podcast">Perspectives Podcast</a>
      <a href="https://www.parallaxxtransformations.com/blog">Blog</a>
      <a href="https://www.parallaxxtransformations.com/ptjournal">Progress Journal</a>
      <a href="https://www.parallaxxtransformations.com/three-toxic-lies">Three Toxic Lies</a>
      <!-- [CLIENT] If Identity 2.0 is aimed at one avatar, promote it
           into that door's column instead of leaving it here. -->
      <a href="https://www.parallaxxtransformations.com/your-identity-challenge">Your Identity 2.0 Challenge</a>
      <a href="https://www.parallaxxtransformations.com/testimonials-daniel-lawson">Testimonials</a>
      <a href="https://www.parallaxxtransformations.com/daniel-lawson-as-seen-in">As Seen In</a>
    </nav>

    <div id="pt-legal">
      <span>&copy; <span id="pt-year">2026</span> Parallaxx Transformations &middot; Daniel Lawson</span>
      <span class="links">
        <a href="https://www.parallaxxtransformations.com/terms-of-use">Terms of Service</a>
        <a href="https://www.parallaxxtransformations.com/privacy-policy">Privacy Policy</a>
      </span>
    </div>

  </div>
</footer>

</div>`;

  function addFonts(){
    if (document.getElementById('px-fonts')) return;
    var p1=document.createElement('link'); p1.rel='preconnect'; p1.href='https://fonts.googleapis.com'; document.head.appendChild(p1);
    var p2=document.createElement('link'); p2.rel='preconnect'; p2.href='https://fonts.gstatic.com'; p2.crossOrigin=''; document.head.appendChild(p2);
    var f0=document.createElement('link'); f0.rel='stylesheet'; f0.href='https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&display=swap'; document.head.appendChild(f0);
    var f1=document.createElement('link'); f1.rel='stylesheet'; f1.href='https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap'; document.head.appendChild(f1);
    /* @font-face has to live in the DOCUMENT, not the shadow root. Chrome
       ignores font-face rules declared inside a shadow tree. */
    var ff=document.createElement('style'); ff.id='px-fonts'; ff.textContent=`/* LUMIOS MARKER is not on Google Fonts. Upload the .woff2 to Wix Media and drop
   the URL in below. Until then the stack falls through to Permanent Marker. */
@font-face{font-family:'Lumios Marker';font-display:swap;
  src:url('LUMIOS_MARKER_WOFF2_URL') format('woff2');}`; document.head.appendChild(ff);
  }

  function loadScript(src){
    return new Promise(function(res,rej){
      var ex=document.querySelector('script[data-px="'+src+'"]');
      if(ex){ if(ex.getAttribute('data-loaded')){res();} else { ex.addEventListener('load',function(){res();}); ex.addEventListener('error',rej);} return; }
      var s=document.createElement('script'); s.src=src; s.async=false; s.setAttribute('data-px',src);
      s.addEventListener('load',function(){ s.setAttribute('data-loaded','1'); res(); });
      s.addEventListener('error',rej);
      document.head.appendChild(s);
    });
  }

  function loadLibs(){
    var g=loadScript('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js')
      .then(function(){ return loadScript('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js'); });
    var l=loadScript('https://unpkg.com/lenis@1.1.13/dist/lenis.min.js');
    return Promise.all([ g.catch(function(){}), l.catch(function(){}) ]);
  }

  /* ══════════════ ANCESTOR COLLAPSE ══════════════
     Wix wraps a custom element in containers with fixed heights, so the page
     renders inside a short box with its own scrollbar. This walks up and
     releases them.

     IT MUST ONLY EVER RUN ONCE PER ELEMENT. The first version re-ran on
     every resize and called ScrollTrigger.refresh() whenever it changed
     anything. If Wix re-applied its own height after we set auto -- which it
     does -- "changed" was true on every pass, so:
         resize -> collapse -> refresh -> layout mutates -> resize -> ...
     That loop grew the document until Chrome clamped it at 2^24, which is
     16,777,216px of empty scroll. A WeakSet makes each element a one-shot,
     which is enough on its own to break the cycle.

     Three further belts, because a runaway here is invisible in the editor
     and catastrophic on the live page:
       - resize is debounced, so a drag is one pass and not sixty
       - refreshes are capped
       - a sanity check bails out entirely if the document is already absurd,
         so a loop that starts for some other reason cannot be fed by us
     ══════════════════════════════════════════════ */
  var PX_SANE_MAX = 200000;              // taller than any real page here
  var pxCollapsed = new WeakSet();
  var pxRefreshes = 0;
  var pxPasses    = 0;                   // hard ceiling on collapse passes
  var PX_MAX_PASSES = 400;

  /* Sums the real content inside the shadow root. A fixed-position child (a
     baked-in site nav) takes no space in flow, so summing children and
     skipping fixed ones is the only honest number. */
  function contentHeight(host){
    var total = 0;
    try{
      var kids = host.shadowRoot ? host.shadowRoot.children : [];
      for (var i=0;i<kids.length;i++){
        var c = kids[i];
        if (c.tagName === 'STYLE') continue;
        var cs = window.getComputedStyle(c);
        if (cs.position === 'fixed' || cs.display === 'none') continue;
        total += c.getBoundingClientRect().height;
      }
    }catch(e){}
    return total;
  }

  /* WHAT THIS IS ACTUALLY FIXING, measured on the live About page 5 Aug.
     59851px of page with 5790px of content in it: fifty thousand pixels of
     empty section under the footer. Wix writes the widget height the editor
     last recorded into an INLINE STYLESHEET RULE, not an inline style:

         #comp-msfv7drl { height: 59851px }
         #comp-msfv7drl { --custom-element-height: 59851px }

     Two consequences, and the previous version of this function missed both.

     1. A plain host.style.height = 'auto' LOSES to that rule. Every write
        here has to be setProperty with 'important' or nothing moves.
     2. The rule sits on the PARENT and the host stretches to match, so host
        and parent measure identically. Comparing each ancestor against the
        HOST and asking for a 600px difference therefore compares a number
        with itself. It never fired, on any page, for the exact case it was
        written for. Everything is measured against the CONTENT now.

     Verified in the browser before shipping: 59851 -> 5790, and it held.

     THE RUNAWAY GUARDS STAY. They are not paranoia: this loop once grew a
     document to Chrome's 2^24 clamp. The whole thing bails if the page is
     already absurd, and there is a hard ceiling on total passes.

     ───────────────────────────────────────────────────────────────────
     REVISED 10 Aug, FOR THE ENDLESS BLUE SCROLL ON MOBILE.

     Three separate faults, and the version above fixed none of them on a
     phone.

     1. THE WEAKSET MADE IT ONE-SHOT. Once an element had been collapsed
        it was never looked at again. Wix re-applies the stored height
        after ITS OWN layout settles, and on mobile it does it more than
        once -- on orientation change, on the mobile-view swap, and when
        its lazy sections resolve. We collapsed at 400ms, Wix wrote the
        height back at 1800ms, and the WeakSet meant nothing ever fixed
        it again. Re-applying is SAFE because the write is idempotent:
        it only ever fires when the box is taller than its own content,
        and setting height:auto on a box that is already auto changes
        nothing and reports no change. The pass counter is the real
        runaway guard and it is what the WeakSet was standing in for.

     2. THE MOBILE HEIGHT IS A DIFFERENT NUMBER. Wix stores desktop and
        mobile layout separately, so a page that was fixed on desktop can
        still carry a five-figure height in the mobile breakpoint. This
        is almost always the actual source of a navy void that scrolls
        for a screen or twenty. Nothing about the fix changes; it just
        has to still be running when the mobile layout applies, which is
        what the longer watch window below is for.

     3. THE VOID CAN BE A SIBLING, NOT AN ANCESTOR. Walking up only ever
        finds boxes the widget is INSIDE. A Wix page whose section was
        left with a stored height puts the empty space in a sibling
        section AFTER ours, which no amount of ancestor walking touches.
        Empty trailing siblings are now collapsed too -- and only if they
        are genuinely empty: no text, no image, no iframe, no video, no
        canvas, and taller than 200px. That test is deliberately strict.
        A sibling with anything in it is somebody's content and is left
        exactly alone. */
  function pxIsEmptyBox(el){
    try{
      if (el.offsetHeight <= 200) return false;
      if ((el.textContent || '').trim().length) return false;
      if (el.querySelector('img,svg,iframe,video,canvas,input,button,picture')) return false;
      var cs = window.getComputedStyle(el);
      if (cs.position === 'fixed' || cs.display === 'none') return false;
      return true;
    }catch(e){ return false; }
  }

  function pxClearHeight(el){
    el.style.setProperty('height','auto','important');
    el.style.setProperty('min-height','0px','important');
    el.style.setProperty('max-height','none','important');
    el.style.setProperty('--custom-element-height','auto','important');
  }

  function collapseAncestors(host){
    var changed = false;
    try{
      if (pxPasses++ > PX_MAX_PASSES) return false;
      if (document.documentElement.scrollHeight > PX_SANE_MAX) return false;
      var content = contentHeight(host);
      if (content < 50) return false;

      if (host.getBoundingClientRect().height > content + 24){
        if (window.getComputedStyle(host).display === 'inline') host.style.setProperty('display','block','important');
        pxClearHeight(host);
        changed = true;
      }

      var n = host.parentElement, guard = 0;
      while(n && n !== document.body && guard++ < 14){
        if(n.getBoundingClientRect().height > content + 240){
          pxClearHeight(n);
          changed = true;
        }
        /* EMPTY TRAILING SIBLINGS. Only forward siblings: an empty box
           ABOVE the widget is a spacer somebody put there on purpose,
           and collapsing it would move the page under the reader. */
        var sib = n.nextElementSibling, sguard = 0;
        while(sib && sguard++ < 6){
          if (!pxCollapsed.has(sib) && pxIsEmptyBox(sib)){
            pxCollapsed.add(sib);
            pxClearHeight(sib);
            changed = true;
          }
          sib = sib.nextElementSibling;
        }
        n = n.parentElement;
      }

      /* ── LAST RESORT: SWEEP EVERYTHING BELOW US ──────────────────
         Added 10 Aug, because the walk above still assumes the void is
         related to this widget by ancestry or by being a sibling of one
         of its ancestors. On a Wix page it does not have to be either:
         a stored height can sit on a section three levels sideways, and
         the empty space lands under the footer regardless.

         So: if the document is STILL materially taller than the bottom
         of our own content once the targeted passes have run, take one
         bounded sweep of the whole document for empty boxes that begin
         at or below that bottom edge, and collapse those. Bounded three
         ways -- it only runs when there is still a real discrepancy, it
         only touches boxes that pass the same strict emptiness test,
         and each element is one-shot via the WeakSet. Anything with a
         single character of text, an image or a control in it is
         somebody's content and is never touched. */
      var bottom = host.getBoundingClientRect().bottom + window.scrollY;
      if (document.documentElement.scrollHeight > bottom + 400){
        var all = document.body.querySelectorAll('div,section,footer,main');
        for (var k=0; k<all.length && k<3000; k++){
          var el = all[k];
          if (pxCollapsed.has(el)) continue;
          if (el.contains(host)) continue;
          var r = el.getBoundingClientRect();
          if (r.top + window.scrollY < bottom - 8) continue;
          if (!pxIsEmptyBox(el)) continue;
          pxCollapsed.add(el);
          pxClearHeight(el);
          changed = true;
        }
      }
    }catch(e){}
    return changed;
  }

  function collapseAndRefresh(host){
    if (!collapseAncestors(host)) return;
    if (pxRefreshes >= 4) return;
    pxRefreshes++;
    if (window.ScrollTrigger) { try{ window.ScrollTrigger.refresh(); }catch(e){} }
  }

  function boot(root){
    if(!root || !root.getElementById('px-root')) return;


    /* THE ONLY SCRIPT ON THE PAGE, AND NOTHING DEPENDS ON IT.
       Every word above is already visible before this runs. All it does is
       cancel the entrance for anybody arriving already scrolled, so a deep
       link or a restored scroll position does not replay an animation the
       visitor has effectively already watched. */
  /* ══════════════ SITE NAV ══════════════
     PtNav is built into this page rather than placed in the Wix header
     strip, for the same reason as the footer: the strip would not load it.
     PtNav v3.dc.html stays the source of record and this copy will not
     track it. Change one and the other does not move.

     Two things had to change coming in. The active prop is gone, because
     there is no Wix instance to set one, so the section is worked out from
     the URL and nothing else. And every lookup goes through root, which is
     the shadow root once this is bundled.

     document.addEventListener is deliberately left alone below: the
     outside-click and Escape handlers have to hear events that never reach
     the shadow root. */
  (function siteNav(){

    const nav = root.getElementById('pt-nav');
    if(!nav) return;
    const links  = root.getElementById('pt-links');
    const burger = root.getElementById('pt-burger');
    const items  = [...nav.querySelectorAll('.pt-has-drop')];
    const MOBILE = () => window.innerWidth < 1024;

    /* ── WHERE YOU ARE ──────────────────────────────────────────────
       Worked out from the URL, because this element lives ONCE in the
       site's header strip and therefore serves every page from a single
       instance. A per-page the active prop cannot do that: one instance
       carries one value, so "For Women" would sit underlined on the
       men's page too.

       The prop still wins when it is set, for the Wix editor preview
       and for any page whose path does not match the table below. */
    const PATHS = [
      [/^\/(men|the-reconnected-man|the-archetype-quiz)\b/,      'men'],
      [/^\/(women|the-reconnected-woman|priority-audit)\b/,      'women'],
      [/^\/about-daniel-lawson\b/,                              'about'],
      [/^\/(daniel-lawson-speaking|facilitating)\b/,             'about'],
      [/^\/testimonials-daniel-lawson\b/,                       'testimonials'],
      [/^\/(contact-daniel-lawson|book-a-call)/,                 'contact']
    ];
    const fromPath = () => {
      const p = (location.pathname || '').replace(/\/+$/, '').toLowerCase() || '/';
      for(const [re, key] of PATHS) if(re.test(p)) return key;
      return '';
    };
    const active = fromPath();
    if(active){
      const el = nav.querySelector('[data-nav="'+active+'"]');
      if(el) el.classList.add('is-active');
    }

    /* ── NAVY ON SCROLL ─────────────────────────────────────────── */
    let ticking = false;
    const onScroll = () => {
      if(ticking) return; ticking = true;
      requestAnimationFrame(() => {
        nav.classList.toggle('is-stuck', window.scrollY > 40);
        ticking = false;
      });
    };
    window.addEventListener('scroll', onScroll, {passive:true});
    onScroll();

    /* ── MOBILE PANEL ───────────────────────────────────────────── */
    const closeMenu = () => {
      nav.classList.remove('menu-open');
      burger.setAttribute('aria-expanded','false');
      items.forEach(closeDrop);
    };
    burger.addEventListener('click', () => {
      const open = !nav.classList.contains('menu-open');
      nav.classList.toggle('menu-open', open);
      burger.setAttribute('aria-expanded', String(open));
      if(!open) items.forEach(closeDrop);
    });

    /* ── SUBMENUS ───────────────────────────────────────────────────
       Desktop hover and keyboard focus are pure CSS. The caret only
       exists for pointers that cannot hover, and for anyone who would
       rather tap the arrow than the word. */
    function closeDrop(it){
      it.classList.remove('is-open');
      const c = it.querySelector('.pt-caret');
      if(c) c.setAttribute('aria-expanded','false');
    }
    items.forEach(it => {
      const caret = it.querySelector('.pt-caret');
      caret.addEventListener('click', e => {
        e.preventDefault(); e.stopPropagation();
        const open = !it.classList.contains('is-open');
        items.forEach(closeDrop);
        it.classList.toggle('is-open', open);
        caret.setAttribute('aria-expanded', String(open));
      });
    });

    /* ── DISMISSAL ──────────────────────────────────────────────── */
    links.querySelectorAll('a').forEach(a =>
      a.addEventListener('click', () => { if(MOBILE()) closeMenu(); }));

    /* composedPath, not e.target. A click inside a shadow root is RETARGETED
       by the time it reaches the document: e.target becomes the host element,
       so nav.contains(e.target) is false for a click on the burger itself and
       this handler closed the panel in the same tick the burger opened it.
       The menu looked completely dead. composedPath() reports the real path
       through the shadow tree, and in the light DOM it still contains nav, so
       one line covers both runtimes. */
    document.addEventListener('click', e => {
      const path = e.composedPath ? e.composedPath() : [e.target];
      if(path.indexOf(nav) === -1){ items.forEach(closeDrop); if(MOBILE()) closeMenu(); }
    });

    document.addEventListener('keydown', e => {
      if(e.key !== 'Escape') return;
      items.forEach(closeDrop);
      if(nav.classList.contains('menu-open')){ closeMenu(); burger.focus(); }
    });

    /* Crossing the breakpoint with the phone panel open would leave a
       stranded overlay on the desktop layout. */
    let wasMobile = MOBILE();
    window.addEventListener('resize', () => {
      const now = MOBILE();
      if(now !== wasMobile){ wasMobile = now; closeMenu(); }
    });
  })();

    /* ══ FOOTER YEAR ══
       The footer is built into this page rather than placed as its own
       element, same as the women's page. This is the only line of script it
       has: a stale copyright year is the one thing in a footer nobody
       remembers to update, and it is what makes a site look abandoned.
       Runs BEFORE the reduced-motion return so it happens either way. */
    const year = root.getElementById('pt-year');
    if (year) year.textContent = String(new Date().getFullYear());

    const reduce = window.matchMedia('(prefers-reduced-motion:reduce)').matches;
    if(reduce) return;

    if(window.scrollY > 40){
      root.querySelectorAll('.px-rise').forEach(el=>{ el.style.animation = 'none'; });
    }
  }

  class ParallaxxHome extends HTMLElement {
    connectedCallback(){
      if (this._mounted) return; this._mounted = true;
      addFonts();
      var shadow = this.attachShadow({mode:'open'});
      shadow.innerHTML = '<style>'+CSS+'</style>'+HTML;
      var host = this;
      /* THE HOST ITSELF, NOT JUST ITS ANCESTORS.
         collapseAndRefresh only walks upward. If the Wix editor has given
         the widget its own fixed height -- which it does by default -- the
         element keeps it and the surplus renders as empty page background
         under the content. Clearing it here is the difference between a
         page and a page followed by a white cliff. Added 4 Aug 2026. */
      try{ host.style.height='auto'; host.style.minHeight='0px'; }catch(e){}
      loadLibs().then(function(){ try{ boot(shadow); }catch(e){ console.error('[px] boot failed:', e); } })
        .catch(function(){ try{ boot(shadow); }catch(e){} });
      requestAnimationFrame(function(){ collapseAndRefresh(host); });
      /* A WATCH WINDOW, NOT FIVE GUESSES. The old schedule stopped at
         6s, and Wix's mobile layout can re-apply a stored height later
         than that on a cold 4G load. Every 500ms for 20 seconds, then
         once more at 30, and after that the ResizeObserver and the
         resize/orientation handlers are on their own. A pass over an
         already-correct page costs one getBoundingClientRect and
         returns false, so the cost of the window is negligible and the
         cost of missing the write is a screen of empty navy. */
      var pxTicks = 0;
      var pxWatch = setInterval(function(){
        collapseAndRefresh(host);
        if (++pxTicks >= 40) clearInterval(pxWatch);
      }, 500);
      [400,1200,2500,4000,6000,30000].forEach(function(t){ setTimeout(function(){ collapseAndRefresh(host); }, t); });
      window.addEventListener('orientationchange', function(){
        setTimeout(function(){ collapseAndRefresh(host); }, 300);
      }, {passive:true});
      window.addEventListener('load', function(){ collapseAndRefresh(host); }, {passive:true});
      /* Images arriving late change the content height, and Wix can re-apply
         its stored height after its own layout settles. Watching the host is
         cheaper and far more reliable than guessing more timeouts. */
      if (window.ResizeObserver){
        try{ new ResizeObserver(function(){ collapseAndRefresh(host); }).observe(host); }catch(e){}
      }
      var pxRT;
      window.addEventListener('resize', function(){
        clearTimeout(pxRT);
        pxRT = setTimeout(function(){ collapseAndRefresh(host); }, 250);
      }, {passive:true});
    }
  }
  customElements.define('parallaxx-home', ParallaxxHome);
})();
