/* PARALLAXX TRANSFORMATIONS - Terms of Use. Custom Element. Tag: parallaxx-terms.
   GENERATED by build-legal-bundles.py from "Parallaxx Legal.dc.html".
   DO NOT EDIT THIS FILE - edit the .dc.html and rerun the build, which
   rebuilds BOTH legal pages. They share one source on purpose.

   PtNav v3 and PtFooter v3 are baked in, so site Header and Footer must be
   OFF, same as every other page in the README table.

   No libraries. These are documents; nothing on them animates beyond a CSS
   keyframe, and a legal page that is waiting on a CDN is a legal page that
   can fail to render at the moment somebody is auditing the site. */
(function(){
  if (customElements.get('parallaxx-terms')) return;

  var CSS = `/* ═══════════════════════════════════════════════════════════════════
   PARALLAXX TRANSFORMATIONS  ·  LEGAL
   -------------------------------------------------------------------
   ONE SOURCE, TWO PAGES. The Privacy Policy and the Terms of Use are
   two routes, two tags and two bundles, and they are authored here in
   one file because everything except their words is identical. Split
   into two .dc.html files they would share a stylesheet by copy, and
   the first fix to one of them would silently stop applying to the
   other -- which is the exact failure the footer bundle has been
   carrying for months. build-legal-bundles.py slices this file on the
   two <section> ids and emits a bundle per page.

   THE WORDS ARE VERBATIM. Every sentence in both documents is the
   copy harvested off the live Wix pages, unchanged. What changed is
   only the typesetting: Wix's export flattened its lists into loose
   paragraphs, so the rights, the sharing cases and the usage purposes
   are lists again. Nothing was added, removed or rephrased, because
   nobody here is the lawyer.

   THE SKIN, THOUGH, IS DELIBERATE.
   Long prose reads better as dark type on cream than cream on navy,
   so the documents sit on cream and the header and the closing block
   bracket them in navy. That is the same alternation as every other
   page, arranged around the fact that these are the only two pages on
   the site somebody reads top to bottom.

   GOLD is the section rules and the date. There is no coral anywhere
   except the closing block's link, because there is one move on these
   pages and it is leaving them.
   ═══════════════════════════════════════════════════════════════════ */

  :where(#lg-root) *,:where(#lg-root) *::before,:where(#lg-root) *::after{box-sizing:border-box;margin:0;padding:0}
  #lg-root ::selection{background:#FF501F;color:#fff}

  #lg-root{
    --navy:#04122A; --navy-2:#0A1D3C; --navy-ink:#030C1C;
    --cream:#F1ECE1; --cream-2:#F7F3EA;
    --gold:#E8C65F; --gold-lift:#F3DD93; --bronze:#A08A5E;
    --coral:#FF501F; --coral-lift:#FF6A3D; --coral-ink:#C0391A;
    --mist:#B1BFD7; --slate:#7C89A3; --label:#5E6B85;
    --ink:#1F2A3D; --ink-soft:#5A6274; --line:#12233F; --line-cream:#DED6C4;
    --lg-nav:68px;
    background:var(--navy);
    color:var(--mist);
    font-family:'Montserrat',system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;
    font-size:16px;line-height:1.7;position:relative;overflow-x:clip;
    -webkit-font-smoothing:antialiased;
  }

  .lg-serif{font-family:'Poppins','Montserrat',sans-serif;font-weight:400;letter-spacing:-.018em;line-height:1.18;color:var(--cream)}
  .lg-wrap{max-width:1240px;margin:0 auto;padding-left:clamp(20px,4vw,52px);padding-right:clamp(20px,4vw,52px)}
  .lg-col{max-width:680px;margin-left:auto;margin-right:auto}
  .lg-label{font-size:.66rem;letter-spacing:.22em;text-transform:uppercase;font-weight:700;color:var(--gold);opacity:.9}
  .sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}

  .lg-up{animation:lgUp .7s cubic-bezier(.22,.61,.36,1) both}
  @keyframes lgUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
  @media(prefers-reduced-motion:reduce){
    #lg-root *,#lg-root *::before,#lg-root *::after{animation:none!important;transition:none!important}
  }

  /* ── HEADER ──────────────────────────────────────────────────── */
  .lg-head{background:var(--navy);
    padding:calc(clamp(48px,7vw,84px) + var(--lg-nav)) 0 clamp(44px,6vw,72px)}
  .lg-head h1{font-size:clamp(1.9rem,5.2vw,3rem);font-weight:400;margin:16px 0 0;max-width:18ch}
  .lg-meta{margin:22px 0 0;display:flex;flex-wrap:wrap;gap:10px 22px;align-items:baseline}
  .lg-meta .date{font-size:.78rem;letter-spacing:.16em;text-transform:uppercase;font-weight:700;color:var(--gold);opacity:.9}
  .lg-meta .who{font-size:.86rem;color:var(--slate)}
  .lg-jump{margin:26px 0 0;font-size:.86rem;color:var(--slate)}
  .lg-jump a{color:var(--mist);text-decoration:underline;text-underline-offset:3px;
    text-decoration-color:rgba(232,198,95,.45);transition:color .25s}
  .lg-jump a:hover{color:var(--cream);text-decoration-color:var(--gold)}
  .lg-jump a:focus-visible{outline:2px solid var(--gold);outline-offset:3px}

  /* ── DOCUMENT BODY ───────────────────────────────────────────────
     THE MEASURE IS 68ch AND THE LEADING IS 1.75. These are the only
     two pages on the site read top to bottom rather than scanned, and
     the default 1.7 on a 52ch column is tuned for scanning. */
  .lg-doc{background:var(--cream);color:var(--ink-soft);padding:clamp(52px,7vw,88px) 0}
  .lg-doc .lg-col{max-width:none}
  .lg-doc .prose{max-width:68ch;margin:0 auto;font-size:1rem;line-height:1.75}
  .lg-doc .prose > p{margin:0 0 18px}
  .lg-doc .prose > p:last-child{margin-bottom:0}
  .lg-doc h2{font-family:'Poppins','Montserrat',sans-serif;font-weight:500;letter-spacing:-.012em;
    color:var(--ink);font-size:clamp(1.16rem,2.5vw,1.4rem);line-height:1.3;
    margin:clamp(38px,5vw,54px) 0 18px;padding-top:clamp(30px,4vw,40px);
    border-top:1px solid var(--line-cream);position:relative}
  .lg-doc h2::before{content:'';position:absolute;top:-1px;left:0;width:46px;height:1px;background:var(--bronze)}
  .lg-doc h2:first-child{margin-top:0;padding-top:0;border-top:0}
  .lg-doc h2:first-child::before{display:none}
  .lg-doc .lede{font-size:1.06rem;line-height:1.7;color:var(--ink);margin:0 0 22px}
  .lg-doc strong{font-weight:600;color:var(--ink)}
  .lg-doc ul{margin:0 0 18px;padding:0;list-style:none}
  .lg-doc li{position:relative;padding-left:26px;margin:0 0 13px;line-height:1.7}
  .lg-doc li::before{content:'';position:absolute;left:4px;top:.72em;width:7px;height:1px;background:var(--bronze)}
  .lg-doc li:last-child{margin-bottom:0}
  .lg-doc li strong{display:inline}
  .lg-doc a{color:var(--coral-ink);text-decoration:underline;text-underline-offset:3px;font-weight:600}
  .lg-doc a:hover{color:var(--coral)}

  /* ── CLOSING ─────────────────────────────────────────────────── */
  .lg-close{background:var(--navy-ink);padding:clamp(48px,6vw,76px) 0}
  .lg-close h2{font-family:'Poppins','Montserrat',sans-serif;font-weight:400;letter-spacing:-.018em;
    color:var(--cream);font-size:clamp(1.24rem,2.8vw,1.65rem);margin:14px 0 0;line-height:1.26}
  .lg-close p{margin:14px 0 0;color:var(--slate);font-size:.97rem;max-width:52ch}
  .lg-close p a{color:var(--mist);text-decoration:underline;text-underline-offset:3px;
    text-decoration-color:rgba(255,80,31,.6);font-weight:600;transition:color .25s}
  .lg-close p a:hover{color:var(--cream);text-decoration-color:var(--coral)}
  .lg-close p a:focus-visible{outline:2px solid var(--gold);outline-offset:3px}
  .lg-other{margin:clamp(24px,3vw,32px) 0 0;display:flex;flex-wrap:wrap;gap:10px}
  .lg-other a{font-size:.76rem;font-weight:600;letter-spacing:.1em;text-transform:uppercase;
    color:var(--mist);border:1px solid rgba(241,236,225,.18);border-radius:999px;
    padding:.72em 1.24em;text-decoration:none;transition:border-color .25s,color .25s,background .25s}
  .lg-other a:hover{border-color:var(--gold);color:var(--cream);background:rgba(232,198,95,.08)}
  .lg-other a:focus-visible{outline:2px solid var(--gold);outline-offset:3px}

  @media(max-width:560px){
    .lg-head{padding-top:calc(36px + var(--lg-nav));padding-bottom:40px}
    .lg-doc .prose{font-size:.97rem}
    .lg-doc li{padding-left:22px}
  }

/* ═══════════════════════════════════════════════════════════════════
   PtNav v3 + PtFooter v3, BAKED IN · 14 Aug
   Ported verbatim from The Reconnected Man, which carries the current
   pair including the phone-columns footer: subgrid rows so the three
   link columns start on the same lines, cqw type so the door links stay
   larger than the utility row, and the utility row as two columns
   without dot separators below 560px.

   THIS FLIPS THE WIX CONTRACT FOR THIS PAGE. It used to ship no chrome,
   so the site Header and Footer had to stay ON. Now they must be turned
   OFF, exactly like every other page in the README table, or the page
   renders two navs and two footers.

   The nav works out where it is from the URL rather than from a prop,
   and its table already maps /priority-audit to the women's door, so
   For Women lights up here with nothing to configure.
   ═══════════════════════════════════════════════════════════════════ */
#pt-nav,#pt-nav *{box-sizing:border-box}
#pt-nav{
  position:fixed;top:0;left:0;right:0;z-index:90;
  font-family:'Montserrat',system-ui,-apple-system,sans-serif;
  border-bottom:1px solid transparent;
  background:transparent;
  transition:background .4s ease,border-color .4s ease,backdrop-filter .4s ease;
  -webkit-font-smoothing:antialiased;
}
/* Navy on scroll. NEVER black. */
#pt-nav.is-stuck{
  background:rgba(6,25,56,.92);
  backdrop-filter:blur(16px);
  -webkit-backdrop-filter:blur(16px);
  border-bottom-color:rgba(232,198,95,.16);
}
#pt-bar{
  max-width:1360px;margin:0 auto;
  padding:16px clamp(20px,4vw,52px);
  display:flex;align-items:center;gap:clamp(16px,2.2vw,28px);
  position:relative;
}

/* ═══ LOGO ════════════════════════════════════════════════════════ */
#pt-logo{flex:0 0 auto;display:flex;align-items:center;line-height:0;
  border-radius:6px;text-decoration:none;transition:opacity .25s ease}
#pt-logo:hover{opacity:.82}
#pt-logo:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:6px}
/* If the CDN ever fails, the alt text renders as ordinary cream wordmark
   text rather than a giant blue underlined link. */
#pt-logo img{height:30px;width:auto;display:block;
  font-size:.82rem;font-weight:700;letter-spacing:.02em;color:#F1ECE1}
@media(max-width:600px){#pt-logo img{height:26px}}
/* 400px AND BELOW. At 360 the mark is 216px wide, the Contact pill is
   another 129 and the burger 40. Together with the gutters that is 28px
   more than the screen, so the pill ran off the right edge and took half
   the burger with it. A menu button you cannot reach is worse than any
   of the things it opens. Everything comes down a step. */
@media(max-width:400px){
  #pt-logo img{height:21px}
  /* The mark is an <img> with width:auto, so it normally scales with the
     height above. If the CDN fails it falls back to the alt text, which
     is a fixed 216px of wordmark and pushes the Contact pill and the
     burger off the right edge. This caps it either way. */
  #pt-logo{max-width:50vw;overflow:hidden}
  #pt-bar{padding:14px 16px;gap:10px}
  #pt-cta-wrap{gap:8px;margin-left:auto}
  #pt-cta{font-size:.78rem;padding:.62em 1.05em}
  #pt-burger{padding:6px;margin-right:-6px}
}

/* ═══ LINK RAIL ═══════════════════════════════════════════════════ */
#pt-links{
  display:flex;align-items:center;gap:clamp(20px,2.4vw,34px);
  margin-left:auto;
}
.pt-item{position:relative;display:flex;align-items:center}
.pt-link{
  display:inline-flex;align-items:center;gap:.35em;
  font-size:.9rem;font-weight:600;letter-spacing:.005em;
  color:#B1BFD7;white-space:nowrap;text-decoration:none;
  padding:6px 0;border-radius:4px;
  transition:color .2s ease;
}
.pt-link:hover,.pt-link:focus-visible{color:#F1ECE1;outline:none}
.pt-link:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:4px}

/* WHERE YOU ARE. Gold, plus a rule under it so it survives being
   read by someone who cannot separate gold from mist. */
.pt-item.is-active > .pt-link,
.pt-link.is-active{color:#E8C65F}
.pt-item.is-active > .pt-link::after,
.pt-link.is-active::after{
  content:"";position:absolute;left:0;right:0;bottom:-2px;height:2px;
  background:rgba(232,198,95,.75);border-radius:2px;
}
.pt-link{position:relative}

/* ═══ CARET + DROPDOWN ════════════════════════════════════════════ */
.pt-caret{
  background:none;border:none;padding:6px 2px;margin:0;
  font-family:inherit;font-size:.72em;line-height:1;
  color:inherit;cursor:pointer;
  display:inline-flex;align-items:center;
  transition:transform .25s ease,color .2s ease;
  color:#7C89A3;
}
.pt-item:hover .pt-caret{color:#B1BFD7}
.pt-caret:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:3px;border-radius:4px}
.pt-item:hover .pt-caret,
.pt-item.is-open .pt-caret{transform:rotate(180deg)}

.pt-menu{
  position:absolute;top:100%;left:50%;
  transform:translateX(-50%);
  min-width:252px;
  display:none;flex-direction:column;gap:2px;
  margin-top:14px;
  background:rgba(4,18,42,.98);
  backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);
  border:1px solid rgba(232,198,95,.18);
  border-radius:14px;padding:10px;
  box-shadow:0 30px 60px -20px rgba(3,12,28,.8);
}
/* The 14px gap between the item and the menu would break a hover
   chain, so the bridge below keeps the pointer "inside" while it
   crosses. Without it the menu flickers shut mid-travel. */
.pt-menu::before{content:"";position:absolute;top:-16px;left:0;right:0;height:16px}

/* Desktop opens on hover AND on keyboard focus. No JS involved. */
@media(min-width:1024px){
  .pt-item:hover .pt-menu,
  .pt-item:focus-within .pt-menu,
  .pt-item.is-open .pt-menu{display:flex}
}
.pt-menu a{
  padding:11px 14px;border-radius:9px;
  font-size:.88rem;font-weight:500;color:#D7DEEA;
  white-space:nowrap;text-decoration:none;
  transition:background .2s ease,color .2s ease;
}
.pt-menu a:hover,.pt-menu a:focus-visible{
  background:rgba(232,198,95,.1);color:#E8C65F;outline:none}
.pt-menu a:focus-visible{box-shadow:inset 0 0 0 1px rgba(232,198,95,.55)}
.pt-menu .pt-sub{
  display:block;font-size:.63rem;letter-spacing:.18em;text-transform:uppercase;
  font-weight:800;color:#7C89A3;margin-bottom:3px}
.pt-menu a:hover .pt-sub{color:rgba(232,198,95,.72)}

/* ═══ CONTACT · THE ONLY CORAL IN THE BAR ═════════════════════════ */
#pt-cta-wrap{display:flex;align-items:center;gap:14px;flex:0 0 auto;margin-left:clamp(8px,1.6vw,20px)}
#pt-cta{
  display:inline-flex;align-items:center;gap:.5em;
  background:#FF501F;color:#FFFFFF;
  font-weight:700;font-size:.86rem;
  padding:.72em 1.45em;border-radius:999px;
  white-space:nowrap;text-decoration:none;
  transition:background .25s ease,transform .25s ease,box-shadow .25s ease;
}
#pt-cta:hover,#pt-cta:focus-visible{
  background:#FF6A3D;transform:translateY(-1px);
  box-shadow:0 10px 24px -10px rgba(255,80,31,.7);outline:none}
#pt-cta:focus-visible{outline:2px solid #F3DD93;outline-offset:3px}
#pt-cta .arrow{font-size:.9em;transition:transform .25s ease}
#pt-cta:hover .arrow{transform:translateX(3px)}

/* ═══ BURGER ══════════════════════════════════════════════════════ */
#pt-burger{
  display:none;background:none;border:none;cursor:pointer;
  flex-direction:column;justify-content:center;gap:5px;
  padding:8px;margin-right:-8px;border-radius:6px}
#pt-burger:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:2px}
#pt-burger span{display:block;width:24px;height:2px;background:#F1ECE1;border-radius:2px;
  transition:transform .3s ease,opacity .2s ease}
#pt-nav.menu-open #pt-burger span:nth-child(1){transform:translateY(7px) rotate(45deg)}
#pt-nav.menu-open #pt-burger span:nth-child(2){opacity:0}
#pt-nav.menu-open #pt-burger span:nth-child(3){transform:translateY(-7px) rotate(-45deg)}

/* ═══ MOBILE ══════════════════════════════════════════════════════ */
@media(max-width:1023px){
  #pt-burger{display:flex}
  #pt-nav{background:rgba(6,25,56,.92);backdrop-filter:blur(16px);
    -webkit-backdrop-filter:blur(16px)}

  #pt-links{
    position:absolute;top:100%;left:0;right:0;
    flex-direction:column;align-items:stretch;gap:2px;
    margin-left:0;
    /* SOLID, AND NO BACKDROP FILTER ON THIS ONE. The bar above keeps its
       blur; this panel cannot have one. Nested backdrop-filters inside a
       shadow root make Chromium composite this element against an already
       filtered backdrop, and the page behind reads straight through a
       background that is 98.5% opaque. On the built-in version of this nav
       the hero headline was legible through the open menu. The bar's own
       blur still gives the effect where it matters. */
    background:#061938;
    border-bottom:1px solid rgba(232,198,95,.16);
    padding:10px clamp(16px,4vw,44px) 22px;
    max-height:calc(100vh - 68px);overflow-y:auto;
    display:none;
  }
  #pt-nav.menu-open #pt-links{display:flex}

  .pt-item{flex-wrap:wrap;justify-content:space-between;
    border-bottom:1px solid rgba(241,236,225,.07)}
  .pt-item:last-child{border-bottom:none}
  .pt-link{flex:1 1 auto;padding:15px 2px;font-size:1rem}
  .pt-item.is-active > .pt-link::after,.pt-link.is-active::after{display:none}
  /* The caret was #7C89A3 at .85em: the same grey as inactive text, on a
     control people are meant to notice and press. On a phone it read as
     punctuation, not a button. Gold picks it out of the row, the stroke
     gives the glyph weight a font-weight cannot (it is a symbol, and the
     face has no bolder cut of it), and the ring makes the tap target
     visible so it is obvious there is more underneath. */
  .pt-caret{
    flex:0 0 auto;padding:11px 12px;font-size:1.02em;
    color:#E8C65F;-webkit-text-stroke:.6px #E8C65F;
    border:1px solid rgba(232,198,95,.34);border-radius:999px;
    margin-left:6px;
  }
  .pt-item.is-open .pt-caret{
    color:#F4E1A2;-webkit-text-stroke:.6px #F4E1A2;
    background:rgba(232,198,95,.14);border-color:rgba(232,198,95,.62)}

  /* Child list is a plain indented block on mobile. A floating panel
     inside a panel is a place to get lost. */
  .pt-menu{
    position:static;transform:none;min-width:0;width:100%;
    margin:0 0 12px;padding:0 0 0 14px;
    background:transparent;backdrop-filter:none;-webkit-backdrop-filter:none;
    border:none;border-left:2px solid rgba(232,198,95,.28);
    border-radius:0;box-shadow:none;
    flex-basis:100%;
  }
  .pt-menu::before{display:none}
  .pt-item.is-open .pt-menu{display:flex}
  .pt-menu a{padding:12px 12px;font-size:.94rem}

  #pt-cta-wrap{margin-left:auto}
  #pt-cta{font-size:.8rem;padding:.68em 1.2em}
  #pt-cta .cta-long{display:none}
}
@media(max-width:420px){
  #pt-cta{padding:.66em 1.05em}
  #pt-cta .arrow{display:none}
}


/* ═══ THE 320px BAR ═══════════════════════════════════════════════
   At 320 the logo, the Contact pill and the burger add up to more than
   the bar, and the burger hangs 9px off the right edge. Nothing here is
   a redesign: the logo loses 4px, the bar loses 6px of padding either
   side, and the pill tightens. Added 4 Aug 2026 to all three pages and
   to PtNav v3.dc.html, which stays the source of record. */
@media(max-width:360px){
  #pt-bar{padding-left:14px;padding-right:14px;gap:10px}
  #pt-logo img{height:22px}
  #pt-cta{padding:.6em .82em;font-size:.8rem}
  #pt-burger{width:34px;margin-right:-4px}
}

@media(prefers-reduced-motion:reduce){
  #pt-nav,#pt-nav *{transition:none!important}
}

/* ── (the source file splits nav and footer across two sheets;
      here they land in one, so the tags are dropped) ── */

/* ===================================================================
   PtFooter v3 - BAKED IN VERBATIM from "PtFooter v3.dc.html"
   Do not hand-edit. If the component changes, re-copy it.
   =================================================================== */

/* ═══════════════════════════════════════════════════════════════════
   PARALLAXX · SITE FOOTER · v3  ·  THREE COLUMNS + UTILITY ROW
   -------------------------------------------------------------------
   THE PROBLEM WITH v2
   Twenty-four links in four equal columns. Every one of them the same
   size, the same colour, the same weight. On a site whose entire
   premise is "pick one of two doors", the last thing on the page was
   a sitemap that made twenty-four things look equally important.

   THE FIX IS NOT FEWER LINKS. IT IS HIERARCHY.
   Seven pages on this site are linked from NOWHERE except this footer:
   Blog, both podcasts, Progress Journal, Three Toxic Lies, Identity
   2.0, As Seen In. Delete them from here and they are orphaned:
   unreachable by a human, and invisible to search because nothing
   points at them. So they stay. They just stop shouting.

   WHAT THE VISITOR SEES NOW
     THREE COLUMNS, LARGE   the two doors, then Daniel. nine links.
                            the whole site, as far as anyone arriving
                            cares.
     ONE QUIET ROW, SMALL   everything else, inline, dot-separated,
                            in the register of a footnote rather than
                            a menu. Reachable. Not competing.

   Reading order does the work: doors first at full weight, then the
   row you only look at if you were already looking for something
   specific, then legal. Each tier is quieter than the one above it.

   WHY THERE IS NO BLURB UNDER THE LOGO
   A footer does not need to restate the pitch. Everything above it has
   already spoken, and by the time anyone is down here they are looking
   for a link, not for the argument again.

   WHY THE GIVE IT ALL BANNER IS GONE
   It was a full-width tinted panel with a badge and two lines of copy,
   for a brand that reads as a men's event. Under a footer that serves
   two avatars it was the single loudest thing on the page, and it was
   shouting at half the audience. It is now one gold line in Daniel's
   column, which is the correct size for a sibling brand.

   ───────────────────────────────────────────────────────────────────
   TOKENS shared with GIVE IT ALL:  navy #061938  gold #E8C65F  Montserrat
   TOKENS Parallaxx only:  coral #FF501F  Poppins  cream #F1ECE1

   THE ACCENT RULE. GOLD IS DANIEL. CORAL IS YOU.
   There is NO coral down here, on purpose. Coral marks the reader's
   move, and every ask has already been made: the nav carries a coral
   Contact pill on every page, and the page above closes with its own.
   GIVE IT ALL is gold, because it is his world, not your move.
   ═══════════════════════════════════════════════════════════════════ */
:root{
  --px-navy:#061938;
  --px-navy-deep:#04122A;
  --px-navy-ink:#030C1C;
  --px-gold:#E8C65F;
  --px-gold-lift:#F3DD93;
  --px-coral:#FF501F;
  --px-coral-lift:#FF6A3D;
  --px-cream:#F1ECE1;
  --px-mist:#B1BFD7;
  --px-slate:#7C89A3;
}

#pt-foot,#pt-foot *{box-sizing:border-box}
#pt-foot{
  background:#030C1C;
  border-top:1px solid rgba(232,198,95,.16);
  font-family:'Montserrat',system-ui,-apple-system,sans-serif;
  color:#B1BFD7;-webkit-font-smoothing:antialiased}
#pt-foot-inner{max-width:1360px;margin:0 auto;
  padding:clamp(34px,3.6vw,46px) clamp(20px,4vw,52px) 24px}

/* ═══ TIER 1 · IDENTITY + THE THREE COLUMNS ═══════════════════════
   Two doors and Daniel. The doors are the reader's two routes in;
   the third is everywhere Daniel himself shows up, which is what the
   GIVE IT ALL bar used to be doing at ten times the size. */
#pt-foot-top{
  display:grid;
  grid-template-columns:minmax(260px,1fr) repeat(3,minmax(0,.72fr));
  gap:clamp(30px,3.4vw,52px);
  align-items:start;
  margin-bottom:clamp(28px,3vw,36px)}
/* Identity spans the full width once the columns need the room. */
@media(max-width:1080px){#pt-foot-top{grid-template-columns:repeat(3,minmax(0,1fr));gap:38px 30px}
  #pt-ident{grid-column:1/-1}}
/* THREE COLUMNS ALL THE WAY DOWN. This used to fall to two at 680 and to
   one at 440, which on a 390px phone made the footer 878px tall, taller
   than most of the sections above it and by a long way the tallest thing
   nobody came for. Held at three it is 563px, a third shorter, and the
   two-up version was the worst of both: it put Daniel alone on a row and
   left half of it empty.

   Holding three also keeps the footer the same object it is on desktop.
   Three doors, three columns, whatever the device. The type comes down
   at the bottom breakpoint to buy the width, which is the right trade
   for a block that is scanned rather than read. */
@media(max-width:680px){#pt-foot-top{gap:30px 20px}}
@media(max-width:440px){
  #pt-foot-top{gap:22px 12px}
  .pt-door h4{font-size:.6rem;letter-spacing:.12em;margin-bottom:10px;padding-bottom:8px}
  .pt-door a{font-size:.78rem;line-height:1.28;padding:4px 0}
}

#pt-foot-logo{display:inline-block;line-height:0;margin-bottom:14px;text-decoration:none}
#pt-foot-logo img{height:30px;width:auto;display:block;
  font-size:.8rem;font-weight:700;color:#F1ECE1}

#pt-social{display:flex;gap:18px;flex-wrap:wrap;margin-top:16px}
#pt-social a{font-size:.85rem;font-weight:600;color:#B1BFD7;
  text-decoration:none;transition:color .2s ease}
#pt-social a:hover,#pt-social a:focus-visible{color:#E8C65F;outline:none}

/* ── THE DOORS. Deliberately larger than anything else down here. ── */
.pt-door h4{
  font-size:.68rem;letter-spacing:.18em;text-transform:uppercase;
  font-weight:800;color:#A88F4E;margin:0 0 12px;
  padding-bottom:9px;border-bottom:1px solid rgba(232,198,95,.18)}
/* THE WHOLE BLOCK IS DELIBERATELY SHALLOW. Nothing down here is being
   sold. It exists so that seven otherwise-orphaned pages are reachable
   and so somebody hunting for terms or a podcast can find them. Every
   vertical value in this file was cut roughly a third for that reason,
   and the type went with it. If it starts feeling like a section again,
   it has grown.

   .92rem, not 1.02. At 1.02 these matched the page's body copy exactly,
   which made the footer read as another content section rather than as
   the foot of the page. They are still the largest thing down here, and
   still clearly larger than the utility row at .82, so the hierarchy the
   note above describes is intact. The size came off the type and went
   into padding instead, so the tap target grew rather than shrank.

   margin-bottom went 1px -> 9px on 5 Aug. The padding already made each
   link a decent target, but stacked with 1px between them the boxes
   were effectively continuous, so an imprecise tap in a column landed
   on a neighbour rather than on nothing. The targets are the same size;
   there is simply somewhere to miss now. */
.pt-door a{
  display:block;color:#D7DEEA;font-size:.92rem;font-weight:500;
  line-height:1.3;padding:5px 0;margin-bottom:9px;text-decoration:none;
  border-radius:3px;transition:color .2s ease}
.pt-door a:first-of-type{padding-top:0}
.pt-door a:last-child{margin-bottom:0}
.pt-door a:hover,.pt-door a:focus-visible{color:#E8C65F;outline:none}

/* THE SIBLING BRAND, AS A LINE RATHER THAN A BANNER.
   It stays GOLD, because gold is Daniel and GIVE IT ALL is his room.
   That single colour is now the whole signal — it used to be a
   42px badge, a border, a tinted panel and two lines of body copy,
   which made a men's-retreat brand the loudest thing in a footer
   serving two avatars. */
.pt-door a.ext{color:#E8C65F;font-weight:600}
.pt-door a.ext:hover,.pt-door a.ext:focus-visible{color:#F3DD93}
.pt-door a.ext .mk{font-size:.8em;margin-left:.35em;opacity:.8}

/* ═══ TIER 2 · THE UTILITY ROW ════════════════════════════════════
   Everything the site has that is not a door. Small, inline, dot
   separated. This is the register of a footnote, and that is the
   point: it is here for the person who came looking for it, and
   invisible to the person who did not. */
/* SPACING, NOT SIZE. Measured on a 390px viewport, adjacent links in
   this row sat 0px apart: the dot separator is an ::after INSIDE the
   anchor, so each link's hit box ran all the way to the next one's.
   Nothing here is too small to hit; the problem was that a near miss
   could not miss. A thumb aimed at "Blog" drifting three pixels right
   opened "Progress Journal", and a wrong destination is worse than a
   dead tap, because there is no retry, only a back button.

   So the dot now hugs the link it belongs to and the flex gap carries
   the separation. Visually the row is within a couple of pixels of
   where it was. Between the hit boxes there is now 18px of nothing. */
#pt-util{
  display:flex;flex-wrap:wrap;align-items:center;
  gap:9px 18px;
  padding-top:18px;border-top:1px solid rgba(241,236,225,.1);
  margin-bottom:14px}
#pt-util a{
  color:#6E7B94;font-size:.82rem;text-decoration:none;
  padding:3px 0;border-radius:3px;white-space:nowrap;
  transition:color .2s ease}
#pt-util a:hover,#pt-util a:focus-visible{color:#E8C65F;outline:none}
/* Separator TRAILS its link rather than leading the next one. With
   ::before, every line the row wraps onto opens with an orphaned dot.
   Trailing means a wrapped line starts on a word, which is what the
   eye expects, and the dot left at a line end reads as continuation. */
#pt-util a:not(:last-child)::after{
  content:"·";color:#3E4A63;margin:0 0 0 9px;display:inline-block}

/* ═══ TIER 3 · LEGAL ══════════════════════════════════════════════ */
#pt-legal{
  display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;
  color:#5E6B85;font-size:.8rem;line-height:1.6}
#pt-legal .links{display:inline-flex;gap:18px;flex-wrap:wrap}
#pt-legal a{color:inherit;text-decoration:none;
  border-bottom:1px solid rgba(232,198,95,.4);padding-bottom:1px;
  transition:color .2s ease,border-color .2s ease}
#pt-legal a:hover,#pt-legal a:focus-visible{
  color:#B1BFD7;border-bottom-color:#E8C65F;outline:none}

/* ═══ THE JUMBLE, AND WHY THREE COLUMNS WAS NOT THE PROBLEM ═══════
   Held at three columns a 390px phone gives each one 109px, and at
   109px "The Reconnected Man" takes three lines while "About" takes
   one. Every column therefore started its second link at a different
   height, its third at a different height again, and nothing in the
   block lined up with anything beside it. Read top to bottom it is
   three tidy lists; read across -- which is how anybody actually
   looks at a footer -- it was rubble.

   THE FIX IS ALIGNMENT, NOT FEWER COLUMNS. Dropping to two columns
   was tried before and rejected in the note above for good reasons,
   and it would not have fixed this: two ragged columns are still
   ragged. Each column becomes a SUBGRID of the footer's own rows, so
   row 2 is the same height in all three columns whether its link
   wrapped to one line or three. The heading rule, the first link and
   the last link now sit on the same three lines across the block.

   Browsers without subgrid (pre-2023) ignore the declaration and get
   exactly today's layout, which is the correct fallback.

   The utility row loses its dot separators and becomes two columns at
   the same breakpoint. Ten dot-separated links wrapping freely across
   a phone put separators at the ends of lines and orphaned "As Seen
   In" on a line of its own; two columns is a list, and a list is what
   it is. Dots return above 560px where the row fits in two lines.

   THE BLOCK ALSO HAS TO SIT HERE, AFTER .pt-door a, AND THAT IS A BUG
   BEING FIXED RATHER THAN A HOUSE STYLE. The existing max-width:440
   rule is written ABOVE the base .pt-door a declaration, and a media
   query does not raise specificity -- the later rule wins at every
   width. So its .78rem never applied on any phone: the columns have
   always been rendering .92rem links inside 109px, which is most of
   why they wrapped three deep. The size drops again below, from a
   position where it can actually win. Leave this block last. */
/* THE COLUMNS WRAP TO THE WORD, WHICH IS WHY THEY LOOK LIKE THEY RUN
   INTO EACH OTHER · 10 Aug. Aligning the rows fixed the raggedness but
   not the cause. At 109px and .79rem, "The Reconnected" is 115px wide,
   so it cannot share a line with anything: the column breaks after
   "The", then after "Reconnected", and three one-word lines beside
   three one-word lines reads as one field of loose words rather than
   as three lists. Nothing is actually overflowing its column -- it
   just looks that way, which for this purpose is the same thing.

   THE THRESHOLD IS "The Reconnected" FITTING ON A LINE. That string is
   9.1x its own font size, so the column needs the type at or under
   11.75px. 3.2cqw of the footer's own width lands on 11.2, and cqw is
   used here for the same reason as the page sheet above: the widget is
   not the viewport, and vw cannot see what Wix took.

   The column gap goes 12 -> 14 in the same breath. Twelve pixels
   between two columns of wrapped text is not enough white to separate
   them, and that is the other half of "runs into the next column". */
@media(max-width:560px){
  #pt-foot-top{grid-template-rows:auto repeat(5,auto);row-gap:22px;
    container-type:inline-size;column-gap:14px}
  .pt-door{display:grid;grid-template-rows:subgrid;grid-row:2/span 5;
    row-gap:9px;align-content:start}
  .pt-door h4{font-size:clamp(8.5px,2.6cqw,10px);letter-spacing:.1em;padding-bottom:8px;
    margin-bottom:0;align-self:end}
  .pt-door a{font-size:clamp(8.8px,3.2cqw,12.6px);line-height:1.32;padding:3px 0;
    margin-bottom:0;align-self:start}
  #pt-social{gap:14px}
  #pt-social a{font-size:.78rem}
  /* ══ THE FOOTNOTE ROWS WERE LOUDER THAN THE DOORS · 10 Aug ══
     .pt-door a came down to 3.2cqw here to buy the three columns
     their width, and nothing underneath it followed. The utility row
     stayed at .82rem and the legal line at .8rem, so on a 390px phone
     the grey links rendered at 13.1px and 12.8px against door links
     at 11.2 -- the least important type in the footer set two pixels
     LARGER than the most important, which is the whole tier order
     inverted by a breakpoint that only remembered one of its rules.

     Fixed by measuring all three rows against the SAME container
     rather than against the viewport, which this sheet has already
     learned Wix does not hand the component:
         doors   3.2cqw    ~11.2px
         util    2.85cqw   ~10.0px
         legal   2.7cqw     ~9.5px
     #pt-foot-inner becomes the container for the two rows that sit
     OUTSIDE #pt-foot-top. Its content box is exactly #pt-foot-top's
     width -- the padding is on the inner, the top row has none -- so
     one cqw means the same thing in all three rules and the ratios
     hold at every width instead of only at the one they were read
     off. Ceilings sit just under the desktop sizes so nothing jumps
     at the breakpoint. ══ */
  #pt-foot-inner{container-type:inline-size}
  #pt-util{display:grid;grid-template-columns:1fr 1fr;gap:2px 14px;
    align-items:start}
  #pt-util a{white-space:normal;line-height:1.35;padding:5px 0;
    font-size:clamp(8px,2.85cqw,11.2px)}
  #pt-util a:not(:last-child)::after{content:none}
  #pt-legal{font-size:clamp(7.6px,2.7cqw,10.6px);gap:10px;line-height:1.55}
}

#pt-foot a:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:3px}
@media(prefers-reduced-motion:reduce){#pt-foot,#pt-foot *{transition:none!important}}`;

  var HTML = `<div id="lg-root">

<header id="pt-nav">
  <div id="pt-bar">

    <!-- ══ LOGO = HOME. No text "Home" item; the mark is the link. ══ -->
    <a id="pt-logo" href="https://www.parallaxxtransformations.com" aria-label="Parallaxx Transformations — home">
      <img src="https://static.wixstatic.com/media/e1784d_fe3c841c471f47d088f0cd631a89d883~mv2.png"
           alt="Parallaxx Transformations">
    </a>

    <nav id="pt-links" aria-label="Primary">

      <!-- ══ FOR MEN ══ parent is a real link to the men's page ══ -->
      <div class="pt-item pt-has-drop" data-nav="men">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/men">For Men</a>
        <button class="pt-caret" type="button" aria-label="Show For Men menu" aria-expanded="false" aria-controls="pt-menu-men">&#9662;</button>
        <div class="pt-menu" id="pt-menu-men">
          <a href="https://www.parallaxxtransformations.com/men">Start Here</a>
          <a href="https://www.parallaxxtransformations.com/the-reconnected-man">The Reconnected Man</a>
        </div>
      </div>

      <!-- ══ FOR WOMEN ══ -->
      <div class="pt-item pt-has-drop" data-nav="women">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/women">For Women</a>
        <button class="pt-caret" type="button" aria-label="Show For Women menu" aria-expanded="false" aria-controls="pt-menu-women">&#9662;</button>
        <div class="pt-menu" id="pt-menu-women">
          <a href="https://www.parallaxxtransformations.com/women">Start Here</a>
          <a href="https://www.parallaxxtransformations.com/the-reconnected-woman">The Reconnected Woman</a>
        </div>
      </div>

      <div class="pt-item" data-nav="about">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/about-daniel-lawson">About</a>
      </div>

      <div class="pt-item" data-nav="testimonials">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/testimonials-daniel-lawson">Testimonials</a>
      </div>

    </nav>

    <div id="pt-cta-wrap">
      <!-- CONTACT. Coral pill — Parallaxx-only accent. GIA uses a gold
           pill in this exact position: same shape, different colour.
           That is the whole family/identity trick. -->
      <a id="pt-cta" data-nav="contact" href="https://www.parallaxxtransformations.com/contact-daniel-lawson">
        Contact<span class="cta-long">&nbsp;</span><span class="arrow" aria-hidden="true">&#8594;</span>
      </a>
      <button id="pt-burger" type="button" aria-label="Menu" aria-expanded="false" aria-controls="pt-links">
        <span></span><span></span><span></span>
      </button>
    </div>

  </div>
</header>

<section id="lg-terms">

  <div class="lg-head">
    <div class="lg-wrap"><div class="lg-col">
      <p class="lg-label lg-up">Legal</p>
      <h1 class="lg-serif lg-up" style="animation-delay:.08s">Terms of Use</h1>
      <div class="lg-meta lg-up" style="animation-delay:.16s">
        <span class="date">Last updated 13 June 2023</span>
        <span class="who">Parallax Life Co Pty LTD, trading as Parallaxx Transformations</span>
      </div>
      <p class="lg-jump lg-up" style="animation-delay:.24s">Looking for the <a href="https://www.parallaxxtransformations.com/privacy-policy">Privacy Policy</a> instead?</p>
    </div></div>
  </div>

  <div class="lg-doc">
    <div class="lg-wrap"><div class="lg-col"><div class="prose">

      <p class="lede">Welcome to Parallax Life Co Pty LTD (ACN 66 631 353 752) trading as Parallaxx Transformations, hereafter referred to as &ldquo;Parallaxx&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;. Please read these Terms of Use (&ldquo;Terms&rdquo;, &ldquo;Terms of Use&rdquo;) carefully before using our website and services.</p>

      <p>By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.</p>

      <h2>1. Use of the Service</h2>
      <p>You are responsible for all activity that occurs through your use of the Service. You may not post or transmit, or cause to be posted or transmitted, any communication or solicitation designed or intended to obtain password, account, or private information from any other user of the Service.</p>

      <h2>2. Intellectual Property</h2>
      <p>All content, trademarks, services marks, trade names, logos, and icons are proprietary to Parallaxx. Nothing contained on the website should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any trademark displayed on this website without the written permission of Parallaxx. Your use of the trademarks displayed on this website, or any other content on this website, except as provided herein, is strictly prohibited.</p>

      <h2>3. User Conduct</h2>
      <p>You agree to use the Service in compliance with all applicable laws. You agree not to take any action that has a negative impact on the functionality or performance of the Service.</p>

      <h2>4. Indemnity</h2>
      <p>You agree to indemnify and hold harmless Parallaxx and its officers, directors, employees, agents, distributors, and affiliates from and against any and all claims, demands, liabilities, costs, or expenses, including reasonable attorney&rsquo;s fees, resulting from your breach of these Terms.</p>

      <h2>5. Privacy</h2>
      <p>Your use of the website is also subject to Parallaxx&rsquo;s <a href="https://www.parallaxxtransformations.com/privacy-policy">Privacy Policy</a>. Please review our Privacy Policy, which also governs the website and informs users of our data collection practices.</p>

      <h2>6. Termination</h2>
      <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.</p>

      <h2>7. Limitation of Liability</h2>
      <p>In no event shall Parallaxx, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>

      <h2>8. Changes</h2>
      <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will make an effort to provide at least 30 days&rsquo; notice prior to any new terms taking effect. By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms.</p>

      <h2>9. Governing Law</h2>
      <p>These Terms shall be governed and construed in accordance with the laws of Australia, without regard to its conflict of law provisions.</p>

    </div></div></div>
  </div>

  <div class="lg-close">
    <div class="lg-wrap"><div class="lg-col">
      <p class="lg-label">Questions</p>
      <h2>Something here unclear?</h2>
      <p>Write to <a href="mailto:daniel@parallaxxtransformations.com">daniel@parallaxxtransformations.com</a>. It comes to Daniel&rsquo;s own inbox.</p>
      <nav class="lg-other" aria-label="More">
        <a href="https://www.parallaxxtransformations.com/privacy-policy">Privacy Policy</a>
        <a href="https://www.parallaxxtransformations.com/contact-daniel-lawson">Contact</a>
      </nav>
    </div></div>
  </div>

</section>

<footer id="pt-foot">
  <div id="pt-foot-inner">

    <div id="pt-foot-top">

      <!-- ══ IDENTITY ══ The mark and the four places he posts. No
           paragraph, no CTA: both were cut, and the column is better
           for it. ══ -->
      <div id="pt-ident">
        <a id="pt-foot-logo" href="https://www.parallaxxtransformations.com" aria-label="Parallaxx Transformations — home">
          <img src="https://static.wixstatic.com/media/e1784d_fe3c841c471f47d088f0cd631a89d883~mv2.png"
               alt="Parallaxx Transformations" loading="lazy">
        </a>
        <nav id="pt-social" aria-label="Social">
          <a href="https://www.youtube.com/@ReconnectYou1/featured" target="_blank" rel="noopener">YouTube</a>
          <a href="https://www.linkedin.com/in/daniel-reconnect-you/" target="_blank" rel="noopener">LinkedIn</a>
          <a href="https://www.instagram.com/daniel.lawson__/" target="_blank" rel="noopener">Instagram</a>
          <a href="https://www.facebook.com/Kiwi.Daniel" target="_blank" rel="noopener">Facebook</a>
        </nav>
      </div>

      <!-- ══ THE TWO DOORS ══ Same names, same order as the nav. ══ -->
      <nav class="pt-door" aria-label="For men">
        <h4>For Men</h4>
        <a href="https://www.parallaxxtransformations.com/men">Start here</a>
        <a href="https://www.parallaxxtransformations.com/the-reconnected-man">The Reconnected Man</a>
        <!-- THE ARCHETYPE QUIZ LIVES AT /the-archetype-quiz.
             This pointed at /reconnect until 24 Aug 2026, with a comment
             above it asserting that /reconnect WAS the quiz. It never was.
             /reconnect was the Reconnect programme -- a fourteen week,
             invitation-only pathway -- and it 301s to the home page. So the
             footer on every page of the site carried a link labelled "The
             Archetype Quiz" that landed on the home page, and a comment
             that would have talked the next person out of fixing it. The
             label was always right; the URL was always wrong. -->
        <a href="https://www.parallaxxtransformations.com/the-archetype-quiz">The Archetype Quiz</a>
      </nav>

      <nav class="pt-door" aria-label="For women">
        <h4>For Women</h4>
        <a href="https://www.parallaxxtransformations.com/women">Start here</a>
        <a href="https://www.parallaxxtransformations.com/the-reconnected-woman">The Reconnected Woman</a>
        <!-- [CLIENT] /priority-audit is the URL the women's home page
             CTA uses. Confirm the page is live before publishing. -->
        <a href="https://www.parallaxxtransformations.com/priority-audit">The Priority Audit</a>
      </nav>

      <!-- ══ DANIEL ══ Not a door. The three places he shows up in
           person, smallest commitment first. GIVE IT ALL is the last
           of them rather than a banner of its own. ══ -->
      <nav class="pt-door" aria-label="Daniel">
        <h4>Daniel</h4>
        <a href="https://www.parallaxxtransformations.com/about-daniel-lawson">About</a>
        <a href="https://www.parallaxxtransformations.com/daniel-lawson-speaking">Speaking</a>
        <!-- [CLIENT] No facilitating page exists on the site yet. This
             URL is a guess and must be confirmed or repointed. -->
        <a href="https://www.parallaxxtransformations.com/facilitating">Facilitating</a>
        <a class="ext" href="https://giveitallevent.com" target="_blank" rel="noopener">GIVE IT ALL<span class="mk" aria-hidden="true">&#8599;</span></a>
      </nav>

    </div>

    <!-- ══ THE UTILITY ROW ══
         Ordered by who asks for it: the person, then the work he makes,
         then the proof. Seven of these are linked from nowhere else on
         the site, which is exactly why the row exists. ══ -->
    <nav id="pt-util" aria-label="More">
      <a href="https://www.parallaxxtransformations.com/contact-daniel-lawson">Contact</a>
      <a href="https://www.parallaxxtransformations.com/book-a-call-with-daniel-lawson">Book a Call</a>
      <a href="https://www.parallaxxtransformations.com/reconnect-you-podcast-with-daniel-lawson">Reconnect You Podcast</a>
      <a href="https://www.parallaxxtransformations.com/parallaxx-perspectives-podcast">Perspectives Podcast</a>
      <a href="https://www.parallaxxtransformations.com/blog">Blog</a>
      <a href="https://www.parallaxxtransformations.com/ptjournal">Progress Journal</a>
      <a href="https://www.parallaxxtransformations.com/three-toxic-lies">Three Toxic Lies</a>
      <!-- [CLIENT] If Identity 2.0 is aimed at one avatar, promote it
           into that door's column instead of leaving it here. -->
      <a href="https://www.parallaxxtransformations.com/your-identity-challenge">Your Identity 2.0 Challenge</a>
      <a href="https://www.parallaxxtransformations.com/testimonials-daniel-lawson">Testimonials</a>
      <a href="https://www.parallaxxtransformations.com/daniel-lawson-as-seen-in">As Seen In</a>
    </nav>

    <div id="pt-legal">
      <span>&copy; <span id="pt-year">2026</span> Parallaxx Transformations &middot; Daniel Lawson</span>
      <span class="links">
        <a href="https://www.parallaxxtransformations.com/terms-of-use">Terms of Service</a>
        <a href="https://www.parallaxxtransformations.com/privacy-policy">Privacy Policy</a>
      </span>
    </div>

  </div>
</footer>

</div>`;

  function addFonts(){
    if (document.getElementById('lg-fonts')) return;
    var p1=document.createElement('link'); p1.rel='preconnect'; p1.href='https://fonts.googleapis.com'; document.head.appendChild(p1);
    var p2=document.createElement('link'); p2.rel='preconnect'; p2.href='https://fonts.gstatic.com'; p2.crossOrigin=''; document.head.appendChild(p2);
    var f0=document.createElement('link'); f0.rel='stylesheet'; f0.href='https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&display=swap'; document.head.appendChild(f0);
    var f1=document.createElement('link'); f1.rel='stylesheet'; f1.href='https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap'; document.head.appendChild(f1);
    /* @font-face has to live in the DOCUMENT, not the shadow root. Chrome
       ignores font-face rules declared inside a shadow tree. */
    var ff=document.createElement('style'); ff.id='lg-fonts'; ff.textContent=`/* LUMIOS MARKER is not on Google Fonts -- upload the .woff2 to Wix Media and
   drop the URL in below. Until then the stack falls through to Permanent
   Marker, which is the closest free marker face, so nothing renders as a
   system script by accident. */
@font-face{font-family:'Lumios Marker';font-display:swap;
  src:url('LUMIOS_MARKER_WOFF2_URL') format('woff2');}`; document.head.appendChild(ff);
  }

  function boot(root){
    if(!root || !root.getElementById('lg-root')) return;


/* ================================================================
       PtNav v3 + PtFooter v3 LOGIC - BAKED IN VERBATIM, root-aware.

       Both take a ROOT. In the built bundle that is the shadow root, where a
       document lookup returns null and fails SILENTLY - the nav would render
       perfectly and do nothing at all. In Design Code and the standalone
       preview 'root' is the page div, which has no getElementById, so the
       expression below falls back to 'document' and the preview still works.
       The outside-click and Escape listeners stay on 'document' on purpose:
       a click that lands outside the shadow tree still has to close the menu.
       ================================================================ */
    function initPtNav(R){
      R = R || document;

        const nav = R.getElementById('pt-nav');
        if(!nav) return;
        const links  = R.getElementById('pt-links');
        const burger = R.getElementById('pt-burger');
        const items  = [...nav.querySelectorAll('.pt-has-drop')];
        const MOBILE = () => window.innerWidth < 1024;

        /* ── WHERE YOU ARE ──────────────────────────────────────────────
           Worked out from the URL, because this element lives ONCE in the
           site's header strip and therefore serves every page from a single
           instance. A per-page 'active' prop cannot do that: one instance
           carries one value, so "For Women" would sit underlined on the
           men's page too.

           The prop still wins when it is set, for the Wix editor preview
           and for any page whose path does not match the table below. */
        const PATHS = [
          [/^\/(men|the-reconnected-man|the-archetype-quiz)\b/,      'men'],
          [/^\/(women|the-reconnected-woman|priority-audit)\b/,      'women'],
          [/^\/about-daniel-lawson\b/,                              'about'],
          [/^\/(daniel-lawson-speaking|facilitating)\b/,             'about'],
          [/^\/testimonials-daniel-lawson\b/,                       'testimonials'],
          [/^\/(contact-daniel-lawson|book-a-call)/,                 'contact']
        ];
        const fromPath = () => {
          const p = (location.pathname || '').replace(/\/+$/, '').toLowerCase() || '/';
          for(const [re, key] of PATHS) if(re.test(p)) return key;
          return '';
        };
        const active = fromPath();   /* baked in: no props, URL only */
        if(active){
          const el = nav.querySelector('[data-nav="'+active+'"]');
          if(el) el.classList.add('is-active');
        }

        /* ── NAVY ON SCROLL ─────────────────────────────────────────── */
        let ticking = false;
        const onScroll = () => {
          if(ticking) return; ticking = true;
          requestAnimationFrame(() => {
            nav.classList.toggle('is-stuck', window.scrollY > 40);
            ticking = false;
          });
        };
        window.addEventListener('scroll', onScroll, {passive:true});
        onScroll();

        /* ── MOBILE PANEL ───────────────────────────────────────────── */
        const closeMenu = () => {
          nav.classList.remove('menu-open');
          burger.setAttribute('aria-expanded','false');
          items.forEach(closeDrop);
        };
        burger.addEventListener('click', () => {
          const open = !nav.classList.contains('menu-open');
          nav.classList.toggle('menu-open', open);
          burger.setAttribute('aria-expanded', String(open));
          if(!open) items.forEach(closeDrop);
        });

        /* ── SUBMENUS ───────────────────────────────────────────────────
           Desktop hover and keyboard focus are pure CSS. The caret only
           exists for pointers that cannot hover, and for anyone who would
           rather tap the arrow than the word. */
        function closeDrop(it){
          it.classList.remove('is-open');
          const c = it.querySelector('.pt-caret');
          if(c) c.setAttribute('aria-expanded','false');
        }
        items.forEach(it => {
          const caret = it.querySelector('.pt-caret');
          caret.addEventListener('click', e => {
            e.preventDefault(); e.stopPropagation();
            const open = !it.classList.contains('is-open');
            items.forEach(closeDrop);
            it.classList.toggle('is-open', open);
            caret.setAttribute('aria-expanded', String(open));
          });
        });

        /* ── DISMISSAL ──────────────────────────────────────────────── */
        links.querySelectorAll('a').forEach(a =>
          a.addEventListener('click', () => { if(MOBILE()) closeMenu(); }));

        /* composedPath, not e.target. A click inside a shadow root is RETARGETED
           by the time it reaches the document: e.target becomes the host element,
           so nav.contains(e.target) is false for a click on the burger itself and
           this handler closed the panel in the same tick the burger opened it.
           The menu looked completely dead. composedPath() reports the real path
           through the shadow tree, and in the light DOM it still contains nav, so
           one line covers both runtimes. */
        document.addEventListener('click', e => {
          const path = e.composedPath ? e.composedPath() : [e.target];
          if(path.indexOf(nav) === -1){ items.forEach(closeDrop); if(MOBILE()) closeMenu(); }
        });

        document.addEventListener('keydown', e => {
          if(e.key !== 'Escape') return;
          items.forEach(closeDrop);
          if(nav.classList.contains('menu-open')){ closeMenu(); burger.focus(); }
        });

        /* Crossing the breakpoint with the phone panel open would leave a
           stranded overlay on the desktop layout. */
        let wasMobile = MOBILE();
        window.addEventListener('resize', () => {
          const now = MOBILE();
          if(now !== wasMobile){ wasMobile = now; closeMenu(); }
        });
    }

    function initPtFooter(R){
      R = R || document;

        /* The only script in the footer. A stale copyright year is a small
           thing that makes a site look abandoned, and it is the one piece
           of a footer nobody remembers to update. */
        const y = R.getElementById('pt-year');
        if(y) y.textContent = String(new Date().getFullYear());
    }

    var chromeRoot = (typeof root !== 'undefined' && root && root.getElementById) ? root : document;
    try{ initPtNav(chromeRoot); }catch(e){ if(window.console) console.warn('[px] ptnav', e); }
    try{ initPtFooter(chromeRoot); }catch(e){ if(window.console) console.warn('[px] ptfooter', e); }
  }

  function collapseAncestors(host){
    try{ var h=host.getBoundingClientRect().height; if(h<50) return;
      var n=host.parentElement,guard=0;
      while(n && n!==document.body && guard++<14){ if(n.getBoundingClientRect().height>h+600){ n.style.height='auto'; n.style.minHeight='0px'; } n=n.parentElement; }
    }catch(e){}
  }

  class ParallaxxTerms extends HTMLElement {
    connectedCallback(){
      if (this._mounted) return; this._mounted = true;
      addFonts();
      var shadow = this.attachShadow({mode:'open'});
      shadow.innerHTML = '<style>'+CSS+'</style>'+HTML;
      var host = this;
      try{ boot(shadow); }catch(e){ console.error('[lg] boot failed:', e); }
      requestAnimationFrame(function(){ collapseAncestors(host); });
      [400,1200,2500].forEach(function(t){ setTimeout(function(){ collapseAncestors(host); }, t); });
      window.addEventListener('resize', function(){ collapseAncestors(host); }, {passive:true});
    }
  }
  customElements.define('parallaxx-terms', ParallaxxTerms);
})();
