/* PARALLAXX TRANSFORMATIONS - Home page Wix Custom Element. Tag: parallaxx-home.
   GENERATED by build-home-bundle.py from "Parallaxx Home.dc.html".
   DO NOT EDIT THIS FILE - edit the .dc.html and rerun the build.
   In the Wix editor: turn the site Header + Footer OFF for this page. */
(function(){
  if (customElements.get('parallaxx-home')) return;

  var CSS = `/* ═══════════════════════════════════════════════════════════════════
   PARALLAXX - HOME
   Supersedes Parallaxx Home Sort.dc.html
   -------------------------------------------------------------------
   ONE JOB: get the right person to /men or /women in under fifteen
   seconds, and give them a reason to trust Daniel on the way past.
   It is not a sales page and it must not behave like one.

   SIX BLOCKS.
     01 FRAME     what this is, who runs it, what to do. His face.
     02 DOORS     situation is the heading. the tag is small.
     03 SHARED    the deletion. the only general sentence allowed.
     04 DANIEL    the record, stated flat. no origin story.
     05 ELSE      one quiet row for everybody who is neither.
     06 CLOSE     the doors again. nothing new.
     -- NAV       PtNav v3, built in rather than placed. See below.
     -- FOOTER    PtFooter v3, built in rather than placed. See below.

   ───────────────────────────────────────────────────────────────────
   WHY THERE IS NO GLASS ON THIS PAGE
   The glass metaphor needs to know whose life it is sitting in front
   of. At second three we do not know. So this page is Daniel straight
   on with nothing in the way, and the glass starts the moment they
   walk through a door. The portrait carries NO CAPTION: "no glass
   between us" belongs to the men's page and anything written to
   replace it was decorating a photograph that already speaks.

   ───────────────────────────────────────────────────────────────────
   WHY ONLY ONE SENTENCE ON THIS PAGE IS ALLOWED TO BE GENERAL
   Every other page is aimed at one person so hard that a blended
   sentence would break it. Block 03 is the exception: the deletion is
   the one mechanism with named sources on both sides. The COSTUME is
   not, and it is deliberately absent. See HOME PAGE - Copy.md 01.

   ───────────────────────────────────────────────────────────────────
   NO JAVASCRIPT IS REQUIRED TO SEE ANY CONTENT.
   A routing page cannot have content that depends on an animation
   completing. Everything here is visible with scripting off; the
   entrance is a CSS animation that starts from the visible state.

   ───────────────────────────────────────────────────────────────────
   TOKENS shared with GIVE IT ALL:  navy #061938 gold #E8C65F Montserrat
   TOKENS Parallaxx only:  coral #FF501F  Poppins  Lumios Marker  cream #F1ECE1

   THE ACCENT RULE. GOLD IS DANIEL. CORAL IS YOU.
   ═══════════════════════════════════════════════════════════════════ */

  /* ══ THE HOST ═════════════════════════════════════════════════════
     A custom element is display:inline by default. Inline means no block
     box, a baseline to sit on, and a wrapper that is free to size itself
     wrong -- which is what leaves a band of PAGE background under the
     component. On a Wix page that band is white.

     Both lines matter. display:block fixes the box. The background means
     that if anything ever does leave a gap, the gap is navy and invisible
     rather than a white cliff at the bottom of the site.

     The preview harnesses set "parallaxx-home{display:block}" from outside,
     which is why this never showed up locally: the harness was quietly
     fixing it and Wix was not. It belongs in here, where it ships. */
  :host{display:block;background:#061938}

  *{box-sizing:border-box}
  #px-root{background:#061938;color:#F1ECE1;
    font-family:'Montserrat',system-ui,-apple-system,sans-serif;
    -webkit-font-smoothing:antialiased;overflow-x:hidden}
  #px-root h1,#px-root h2,#px-root h3,#px-root h4,#px-root p{margin:0}
  #px-root h1,#px-root h2,#px-root h3{text-wrap:balance}
  #px-root p{text-wrap:pretty}
  .px-serif{font-family:'Poppins','Montserrat',sans-serif;font-weight:300;letter-spacing:-.018em}
  .px-hand{font-family:'Lumios Marker','Permanent Marker',cursive;font-weight:400}
  .px-sec{padding:clamp(44px,5.5vw,78px) clamp(20px,4vw,52px);position:relative}
  /* THE SMALLEST PHONES GET ROOM, NOT SMALLER TYPE.
     At 320 the section and card gutters together eat 88px of a 320px screen,
     which is why the qualifier still wrapped after the type had already been
     scaled down as far as it should go. Shrinking the type further would have
     made it unreadable to fix a layout problem. Taking 16px back off the
     gutters fixes it and gives every other line on the page more room too. */
  @media(max-width:360px){
    .px-sec{padding-left:16px;padding-right:16px}
    .px-door{padding:22px 18px}
  }
  .px-wrap{max-width:1080px;margin:0 auto}

  @keyframes px-rise{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:none}}
  .px-rise{animation:px-rise .7s cubic-bezier(.22,.61,.36,1) both}
  .px-d1{animation-delay:.05s}.px-d2{animation-delay:.16s}
  .px-d3{animation-delay:.27s}.px-d4{animation-delay:.38s}
  @media(prefers-reduced-motion:reduce){.px-rise{animation:none}}

/* ═══ 01 · THE FRAME ══════════════════════════════════════════════ */
/* Two columns on desktop, portrait first on mobile. The portrait is
   NOT decorative: 46% of credibility judgements are made on visual
   design alone, and the page it replaces had no human on it at all. */
  /* Clears the fixed nav bar. #pt-bar is 16px of padding either side
     of a 30px logo, so ~62px, plus breathing room. */
  #px-top{padding-top:clamp(104px,10vw,150px)}
  #px-top .grid{display:grid;grid-template-columns:1.05fr .95fr;
    gap:clamp(26px,4vw,58px);align-items:center;max-width:1080px;margin:0 auto}
  @media(max-width:820px){#px-top .grid{grid-template-columns:1fr;gap:26px}}
  #px-top .eyebrow{font-size:clamp(15px,3.2vw,20px);color:#E8C65F;margin-bottom:16px;
    display:block}
  #px-top h1{font-size:clamp(31px,4.6vw,50px);line-height:1.12;color:#F1ECE1;
    margin-bottom:22px;max-width:18ch}
  #px-top .sub{font-size:clamp(16px,1.8vw,20px);line-height:1.65;color:#B1BFD7;
    max-width:40ch}
  /* FORCED BREAK, DESKTOP ONLY. Left to itself the line wraps after
     "Or busy.", which strands "Same answer for years." on its own and
     splits the two halves of the joke. Breaking after "fine." puts the
     whole turn on line two. Below 821px the column is one grid cell
     wide and the natural wrap beats an imposed one, so the br is off. */
  #px-top .sub br{display:none}
  @media(min-width:821px){#px-top .sub br{display:inline}}
  .px-portrait{position:relative;border-radius:20px;overflow:hidden;
    box-shadow:0 24px 60px rgba(0,0,0,.45)}
  .px-portrait img{width:100%;height:100%;display:block;object-fit:cover;
    aspect-ratio:4/5}
  /* Shorter crop on a phone so the doors still break the fold. The portrait
     is doing a credibility job, not a hero-image job, and it does not need
     the height to do it. */
  @media(max-width:820px){.px-portrait img{aspect-ratio:16/10;object-position:50% 26%}}
  /* THE FALSE-FLOOR RULE. Screen one must never look finished, so the
     top edge of the doors is pulled up into the fold. */
  #px-top{padding-bottom:clamp(18px,2.4vw,30px)}

/* ═══ 02 · THE DOORS ══════════════════════════════════════════════ */
/* The SITUATION is the heading. "For men" is a tag, not a promise, and
   it sits small above, so nobody is asked to pick a demographic before
   they have recognised somebody in a sentence. That is also what lets a
   WIFE use the men's door: "a man she never feels" is the most
   recognisable line in the archive to her, and she never has to answer
   a question about herself to get him to the right page. */
  #px-doors{display:grid;grid-template-columns:1fr 1fr;gap:clamp(14px,2vw,22px);
    max-width:1080px;margin:0 auto}
  @media(max-width:820px){#px-doors{grid-template-columns:1fr}}
  .px-door{display:flex;flex-direction:column;background:rgba(241,236,225,.045);
    border:1px solid rgba(241,236,225,.14);border-radius:20px;
    padding:clamp(24px,3vw,36px);text-decoration:none;
    transition:border-color .3s ease,background .3s ease,transform .3s ease}
  .px-door:hover,.px-door:focus-visible{border-color:rgba(255,80,31,.6);
    background:rgba(255,80,31,.075);transform:translateY(-3px);outline:none}
  .px-door:focus-visible{outline:2px solid #FF8A5C;outline-offset:3px}
  .px-door .tag{font-size:.64rem;letter-spacing:.2em;text-transform:uppercase;
    font-weight:800;color:#E8C65F;margin-bottom:14px}
  .px-door h2{font-family:'Poppins','Montserrat',sans-serif;font-weight:300;
    font-size:clamp(21px,2.35vw,29px);line-height:1.22;color:#F1ECE1;margin-bottom:12px}
  .px-door p{font-size:.96rem;line-height:1.7;color:#9DAAC0;margin-bottom:22px}
  /* Heading and body are only ~6px apart in size on a phone, so without more
     air between them they read as one block of text rather than a hook and a
     line underneath it. */
  @media(max-width:520px){
    .px-door h2{margin-bottom:16px}
  }
  /* The qualifier strip is the filter. It sits apart from the body copy so it
     reads as a spec rather than as another sentence. */
  /* SCALED, NOT STEPPED, and there is no breakpoint on it at all.
     At .7rem with .15em tracking this strip wanted 335px and a 390px phone
     gives the card 302, so "CARE ABOUT HER" and "SUCCESSFUL" each dropped an
     orphan onto a second line. The tracking is what costs the room, not the
     words, so the tracking gives way first.

     The worst case is NOT the phone. It is ~900px, where the cards are still
     side by side and each one is at its narrowest. A phone-only media query
     fixed the phone and left 900 broken, and chasing it with one breakpoint
     per handset is how you end up with five of them. One clamp holds a single
     line from 320px all the way up. */
  .px-door .qual{font-size:clamp(.5rem,1.1vw,.7rem);letter-spacing:.055em;
    text-transform:uppercase;font-weight:700;color:#7F8DA6;
    margin-bottom:24px;padding-top:16px;
    border-top:1px solid rgba(241,236,225,.09)}
  .px-door .go{margin-top:auto;font-size:.88rem;font-weight:700;color:#FF6A3D;
    display:inline-flex;align-items:center;gap:.5em}
  .px-door:hover .go{color:#FF804F}

/* ═══ 03 · THE ONE THING BOTH OF THEM DO ══════════════════════════ */
  #px-shared{border-top:1px solid rgba(241,236,225,.09);
    border-bottom:1px solid rgba(241,236,225,.09);
    background:rgba(241,236,225,.022)}
  #px-shared .px-wrap{max-width:760px}
  #px-shared .eyebrow{color:#E8C65F;font-size:clamp(15px,3.2vw,19px);
    display:block;margin-bottom:14px}
  #px-shared h2{font-size:clamp(23px,3.2vw,36px);line-height:1.18;
    margin-bottom:22px;color:#F1ECE1}
  #px-shared p{font-size:clamp(15px,1.65vw,18px);line-height:1.78;
    color:#B1BFD7;margin-bottom:16px}
  /* Daniel's own line, so it carries gold and sits apart. It is the
     confession that stops the paragraph above reading as a man
     diagnosing two groups of people from the outside. */
  #px-shared .mine{border-left:2px solid #E8C65F;padding-left:18px;
    color:#E4E9F2;margin-top:26px;margin-bottom:0}

/* ═══ 04 · ME, AND THE RECORD ═════════════════════════════════════ */
  /* ══ THE FULL-BLEED PLATE ══════════════════════════════════════
     THE ONLY IMAGE ON THIS PAGE BESIDES THE PORTRAIT, and it sits under
     the RECORD rather than anywhere else, because this is the one block
     where a photograph is doing a job instead of decorating: "1000+ lives
     changed, 9 countries" is a claim on flat navy and a receipt over a
     room with people in it.

     WHY A BACK-TO-CAMERA FRAME AND NOT A PORTRAIT-ON-STAGE.
     A man addressing the reader from a platform is the fatal read on the
     women's side (W04 3.6) and it makes Daniel the loudest thing on a page
     whose whole job is to point at the reader. Back to camera inverts it:
     the subject of the photograph is the ROOM, he is the smallest warm
     shape in it, and half the faces are women who chose to be there.

     NOT BEHIND BLOCK 03. That block is the interior one, and a stage
     behind "I built things people needed so I'd never have to ask to be
     included" argues with the sentence.

     TREATMENT. 82% navy, plus a gradient that dissolves both edges into
     the flat navy above and below, so it reads as depth rather than as a
     photograph you stop and look at. Solid navy underneath, so nothing
     here depends on the image loading. Lazy, because it is below the
     fold, and 230KB at 2000px wide. */
  #px-me{position:relative;isolation:isolate;overflow:hidden}
  #px-me .px-plate{position:absolute;inset:0;z-index:-2;
    background:#061938 center 38% / cover no-repeat}
  #px-me .px-plate img{width:100%;height:100%;object-fit:cover;
    object-position:center 46%;display:block;opacity:1}
  /* THE SCRIM IS DARKEST IN THE MIDDLE, NOT AT THE EDGES, which is the
     opposite of a vignette and is what makes this work. The copy is
     centred and capped at 720px, so the middle band carries the text on
     near-solid navy while the room stays legible left and right. A
     uniform veil heavy enough to protect the type also flattened the
     photograph into a smudge, which defeated the point of using it.
     Vertical pass dissolves both edges into the flat navy sections above
     and below so the block has no seams. */
  #px-me .px-veil{position:absolute;inset:0;z-index:-1;
    background:
      linear-gradient(180deg,#061938 0%,rgba(6,25,56,.10) 14%,rgba(6,25,56,.10) 86%,#061938 100%),
      linear-gradient(90deg,rgba(6,25,56,0) 0%,rgba(6,25,56,.62) 24%,rgba(6,25,56,.70) 50%,rgba(6,25,56,.62) 76%,rgba(6,25,56,0) 100%)}
  /* The scrim came down from .95 to .70 in the centre so the room is
     actually visible. Type keeps its contrast from a shadow instead of
     from the veil, which is the cheaper way to buy legibility: it costs
     nothing behind the letters and everything stays readable while the
     photograph stays a photograph. */
  #px-me .px-wrap{text-shadow:0 1px 3px rgba(6,25,56,.95),0 2px 18px rgba(6,25,56,.85)}
  /* On a phone the copy fills the width, so the centre band covers the
     frame and the room reads as tone rather than as a picture. Accepted:
     legibility first, and the photograph is doing a supporting job. */
  @media(max-width:820px){
    #px-me .px-veil{background:
      linear-gradient(180deg,#061938 0%,rgba(6,25,56,.74) 14%,rgba(6,25,56,.78) 86%,#061938 100%)}
  }
  #px-me{padding-top:clamp(66px,8vw,110px);padding-bottom:clamp(66px,8vw,110px)}
  /* On a phone the veil is uniform, so the padding below the link is 66px of
     flat dark photograph with nothing in it. Tighter, and the block ends
     where the content does. */
  @media(max-width:520px){
    #px-me{padding-top:clamp(52px,12vw,66px);padding-bottom:clamp(46px,10vw,60px)}
  }
  #px-me .px-wrap{max-width:900px;text-align:center;position:relative;z-index:1}
  #px-me .hand{color:#E8C65F;font-size:clamp(21px,3vw,30px);display:block;
    margin-bottom:20px}
  #px-me p{font-size:clamp(15px,1.6vw,17.5px);line-height:1.78;color:#C3CDDC;
    margin:0 auto 14px}
  /* The credential sentence is set WIDER than the wrap so it lands on two
     lines rather than three. At the 720px column it broke three ways and the
     orphan line ("ALL world of experiences.") read as a mistake. The record
     strip and the link stay on the narrower measure below it. */
  #px-me p.cred{max-width:none;width:min(100%,900px)}
  #px-me strong{color:#D8DFEA;font-weight:600}
  /* THE RECORD. Billboards on highways: the credential strip currently lives
     only in the footer and at the foot of the avatar pages, and the evidence
     says it belongs high on a high-traffic page. It is also the only evidence
     on this page, because it is about Daniel rather than about anybody's
     result, so it needs nothing captured first. */
  #px-me .px-record{display:flex;flex-wrap:wrap;justify-content:center;
    gap:clamp(22px,4vw,54px);margin:30px 0 26px;padding:24px 0;
    border-top:1px solid rgba(241,236,225,.16);
    border-bottom:1px solid rgba(241,236,225,.16)}
  #px-me .px-record div{text-align:center}
  /* Flex-wrap put "1000+" and "9" on one row and "6+" alone underneath,
     which reads as a mistake rather than as a set. A three-column grid
     cannot wrap, so the row holds whatever the width. The labels tighten
     with it; "YEARS FACILITATING" still takes two lines in its cell, and
     that is fine because all three cells are the same width. */
  @media(max-width:560px){
    #px-me .px-record{display:grid;grid-template-columns:repeat(3,1fr);
      gap:12px;padding:20px 0}
    #px-me .px-record dt{font-size:clamp(23px,6.4vw,30px)}
    #px-me .px-record dd{font-size:.57rem;letter-spacing:.08em;line-height:1.35}
  }
  #px-me .px-record dt{font-family:'Poppins','Montserrat',sans-serif;font-weight:300;
    font-size:clamp(26px,3.4vw,38px);line-height:1;color:#E8C65F;margin:0}
  #px-me .px-record dd{margin:8px 0 0;font-size:.66rem;letter-spacing:.18em;
    text-transform:uppercase;font-weight:700;color:#A4B0C4}
  #px-me a.more{display:inline-block;margin-top:14px;color:#E8C65F;font-weight:700;
    text-decoration:none;font-size:.92rem;
    border-bottom:1px solid rgba(232,198,95,.45);padding-bottom:2px}
  #px-me a.more:hover,#px-me a.more:focus-visible{color:#F1ECE1;border-bottom-color:#F1ECE1}

/* ═══ 05 · NEITHER OF THOSE ═══════════════════════════════════════ */
/* Deliberately the lowest-contrast thing on the page. A two-door page
   bounces everybody who is not one of the two, and some of them book
   the stages. One row, no persuasion. */
  #px-else{border-top:1px solid rgba(241,236,225,.07);text-align:center;
    padding-top:clamp(32px,4vw,52px);padding-bottom:clamp(32px,4vw,52px)}
  #px-else .lab{font-size:.7rem;letter-spacing:.2em;text-transform:uppercase;
    font-weight:800;color:#7C89A3;display:block;margin-bottom:16px}
  #px-else .row{display:flex;flex-wrap:wrap;gap:10px 26px;justify-content:center}
  #px-else a{color:#9DAAC0;text-decoration:none;font-size:.94rem;
    border-bottom:1px solid rgba(157,170,192,.28);padding-bottom:2px}
  #px-else a:hover,#px-else a:focus-visible{color:#F1ECE1;border-bottom-color:#F1ECE1}

/* ═══ 06 · THE CLOSE ══════════════════════════════════════════════ */
  #px-close{text-align:center;padding-bottom:clamp(56px,7vw,96px)}
  #px-close .hand{color:#E8C65F;font-size:clamp(20px,3vw,29px);display:block;
    margin-bottom:26px}
  #px-close .pair{display:grid;grid-template-columns:1fr 1fr;gap:clamp(12px,1.8vw,18px);
    max-width:900px;margin:0 auto;text-align:left}
  @media(max-width:820px){#px-close .pair{grid-template-columns:1fr}}
  .px-mini{display:block;background:rgba(241,236,225,.04);
    border:1px solid rgba(241,236,225,.13);border-radius:16px;
    padding:22px clamp(18px,2.2vw,26px);text-decoration:none;
    transition:border-color .3s ease,background .3s ease}
  .px-mini:hover,.px-mini:focus-visible{border-color:rgba(255,80,31,.55);
    background:rgba(255,80,31,.07);outline:none}
  .px-mini .tag{font-size:.62rem;letter-spacing:.2em;text-transform:uppercase;
    font-weight:800;color:#E8C65F;display:block;margin-bottom:10px}
  .px-mini span.line{font-family:'Poppins','Montserrat',sans-serif;font-weight:300;
    font-size:clamp(16px,1.55vw,19px);line-height:1.35;color:#F1ECE1;display:block}
  .px-mini .go{display:block;margin-top:14px;font-size:.84rem;font-weight:700;color:#FF6A3D}

/*/* ══════════════════════════════════════════════════════════════════
   SITE NAV, BUILT IN RATHER THAN PLACED
   Same story as the footer below it. PtNav belongs in the Wix header
   strip so it is editable in one place for every page; it would not
   load there, so it ships inside this page.

   PtNav v3.dc.html stays the source of record. If the strip starts
   working, delete this block and the markup rather than maintaining
   two copies.

   ONE THING TO WATCH. The bar is position:fixed. Inside a shadow root
   that still resolves against the viewport, but ANY ancestor carrying
   transform, filter, perspective or will-change becomes its containing
   block instead, and the nav would scroll away with the page. If that
   happens in Wix, the culprit is a wrapper on Wix's side, not here.
   ══════════════════════════════════════════════════════════════════ */
/* ═══════════════════════════════════════════════════════════════════
   PARALLAXX · PRIMARY NAVIGATION · v3
   -------------------------------------------------------------------
   STRUCTURE (this is the whole argument of the redesign)
     LOGO          home. no "Home" text item — the mark does that job.
     FOR MEN   ▾   → The Reconnected Man
     FOR WOMEN ▾   → The Reconnected Woman
     ABOUT
     TESTIMONIALS
     CONTACT       coral pill, far right.

   WHY THE DOORS COME FIRST
   The sorting page's entire premise is that a visitor must choose a
   side before anything else can land. The nav has to agree with that.
   "For Men" and "For Women" are therefore the first and largest thing
   after the mark, and everything that is ABOUT DANIEL (About,
   Testimonials) sits after the reader's own doors, not before them.

   THE PARENTS ARE REAL LINKS
   "For Men" goes to the men's page; the dropdown is an addition, not
   the only way through. A nav item that can only be hovered is a dead
   end on touch and a dead end for keyboards.

   ───────────────────────────────────────────────────────────────────
   TOKENS shared with GIVE IT ALL:  navy #061938  gold #E8C65F  Montserrat
   TOKENS Parallaxx only:  coral #FF501F  Poppins  cream #F1ECE1

   THE ACCENT RULE. GOLD IS DANIEL. CORAL IS YOU.
   Gold marks where you ARE (the active item, the hovered child).
   Coral marks the one thing you can DO (Contact). Nothing else in
   this bar is allowed to be coral — the moment a second thing is,
   the pill stops meaning anything.
   ═══════════════════════════════════════════════════════════════════ */
:root{
  --px-navy:#061938;
  --px-navy-deep:#04122A;
  --px-navy-ink:#030C1C;
  --px-gold:#E8C65F;
  --px-gold-lift:#F3DD93;
  --px-coral:#FF501F;
  --px-coral-lift:#FF6A3D;
  --px-cream:#F1ECE1;
  --px-mist:#B1BFD7;
  --px-slate:#7C89A3;
}

/* ═══ SHELL ═══════════════════════════════════════════════════════ */
#pt-nav,#pt-nav *{box-sizing:border-box}
#pt-nav{
  position:fixed;top:0;left:0;right:0;z-index:90;
  font-family:'Montserrat',system-ui,-apple-system,sans-serif;
  border-bottom:1px solid transparent;
  background:transparent;
  transition:background .4s ease,border-color .4s ease,backdrop-filter .4s ease;
  -webkit-font-smoothing:antialiased;
}
/* Navy on scroll. NEVER black. */
#pt-nav.is-stuck{
  background:rgba(6,25,56,.92);
  backdrop-filter:blur(16px);
  -webkit-backdrop-filter:blur(16px);
  border-bottom-color:rgba(232,198,95,.16);
}
#pt-bar{
  max-width:1360px;margin:0 auto;
  padding:16px clamp(20px,4vw,52px);
  display:flex;align-items:center;gap:clamp(16px,2.2vw,28px);
  position:relative;
}

/* ═══ LOGO ════════════════════════════════════════════════════════ */
#pt-logo{flex:0 0 auto;display:flex;align-items:center;line-height:0;
  border-radius:6px;text-decoration:none;transition:opacity .25s ease}
#pt-logo:hover{opacity:.82}
#pt-logo:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:6px}
/* If the CDN ever fails, the alt text renders as ordinary cream wordmark
   text rather than a giant blue underlined link. */
#pt-logo img{height:30px;width:auto;display:block;
  font-size:.82rem;font-weight:700;letter-spacing:.02em;color:#F1ECE1}
@media(max-width:600px){#pt-logo img{height:26px}}

/* ═══ LINK RAIL ═══════════════════════════════════════════════════ */
#pt-links{
  display:flex;align-items:center;gap:clamp(20px,2.4vw,34px);
  margin-left:auto;
}
.pt-item{position:relative;display:flex;align-items:center}
.pt-link{
  display:inline-flex;align-items:center;gap:.35em;
  font-size:.9rem;font-weight:600;letter-spacing:.005em;
  color:#B1BFD7;white-space:nowrap;text-decoration:none;
  padding:6px 0;border-radius:4px;
  transition:color .2s ease;
}
.pt-link:hover,.pt-link:focus-visible{color:#F1ECE1;outline:none}
.pt-link:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:4px}

/* WHERE YOU ARE. Gold, plus a rule under it so it survives being
   read by someone who cannot separate gold from mist. */
.pt-item.is-active > .pt-link,
.pt-link.is-active{color:#E8C65F}
.pt-item.is-active > .pt-link::after,
.pt-link.is-active::after{
  content:"";position:absolute;left:0;right:0;bottom:-2px;height:2px;
  background:rgba(232,198,95,.75);border-radius:2px;
}
.pt-link{position:relative}

/* ═══ CARET + DROPDOWN ════════════════════════════════════════════ */
.pt-caret{
  background:none;border:none;padding:6px 2px;margin:0;
  font-family:inherit;font-size:.72em;line-height:1;
  color:inherit;cursor:pointer;
  display:inline-flex;align-items:center;
  transition:transform .25s ease,color .2s ease;
  color:#7C89A3;
}
.pt-item:hover .pt-caret{color:#B1BFD7}
.pt-caret:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:3px;border-radius:4px}
.pt-item:hover .pt-caret,
.pt-item.is-open .pt-caret{transform:rotate(180deg)}

.pt-menu{
  position:absolute;top:100%;left:50%;
  transform:translateX(-50%);
  min-width:252px;
  display:none;flex-direction:column;gap:2px;
  margin-top:14px;
  background:rgba(4,18,42,.98);
  backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);
  border:1px solid rgba(232,198,95,.18);
  border-radius:14px;padding:10px;
  box-shadow:0 30px 60px -20px rgba(3,12,28,.8);
}
/* The 14px gap between the item and the menu would break a hover
   chain, so the bridge below keeps the pointer "inside" while it
   crosses. Without it the menu flickers shut mid-travel. */
.pt-menu::before{content:"";position:absolute;top:-16px;left:0;right:0;height:16px}

/* Desktop opens on hover AND on keyboard focus. No JS involved. */
@media(min-width:1024px){
  .pt-item:hover .pt-menu,
  .pt-item:focus-within .pt-menu,
  .pt-item.is-open .pt-menu{display:flex}
}
.pt-menu a{
  padding:11px 14px;border-radius:9px;
  font-size:.88rem;font-weight:500;color:#D7DEEA;
  white-space:nowrap;text-decoration:none;
  transition:background .2s ease,color .2s ease;
}
.pt-menu a:hover,.pt-menu a:focus-visible{
  background:rgba(232,198,95,.1);color:#E8C65F;outline:none}
.pt-menu a:focus-visible{box-shadow:inset 0 0 0 1px rgba(232,198,95,.55)}
.pt-menu .pt-sub{
  display:block;font-size:.63rem;letter-spacing:.18em;text-transform:uppercase;
  font-weight:800;color:#7C89A3;margin-bottom:3px}
.pt-menu a:hover .pt-sub{color:rgba(232,198,95,.72)}

/* ═══ CONTACT · THE ONLY CORAL IN THE BAR ═════════════════════════ */
#pt-cta-wrap{display:flex;align-items:center;gap:14px;flex:0 0 auto;margin-left:clamp(8px,1.6vw,20px)}
#pt-cta{
  display:inline-flex;align-items:center;gap:.5em;
  background:#FF501F;color:#FFFFFF;
  font-weight:700;font-size:.86rem;
  padding:.72em 1.45em;border-radius:999px;
  white-space:nowrap;text-decoration:none;
  transition:background .25s ease,transform .25s ease,box-shadow .25s ease;
}
#pt-cta:hover,#pt-cta:focus-visible{
  background:#FF6A3D;transform:translateY(-1px);
  box-shadow:0 10px 24px -10px rgba(255,80,31,.7);outline:none}
#pt-cta:focus-visible{outline:2px solid #F3DD93;outline-offset:3px}
#pt-cta .arrow{font-size:.9em;transition:transform .25s ease}
#pt-cta:hover .arrow{transform:translateX(3px)}

/* ═══ BURGER ══════════════════════════════════════════════════════ */
#pt-burger{
  display:none;background:none;border:none;cursor:pointer;
  flex-direction:column;justify-content:center;gap:5px;
  padding:8px;margin-right:-8px;border-radius:6px}
#pt-burger:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:2px}
#pt-burger span{display:block;width:24px;height:2px;background:#F1ECE1;border-radius:2px;
  transition:transform .3s ease,opacity .2s ease}
#pt-nav.menu-open #pt-burger span:nth-child(1){transform:translateY(7px) rotate(45deg)}
#pt-nav.menu-open #pt-burger span:nth-child(2){opacity:0}
#pt-nav.menu-open #pt-burger span:nth-child(3){transform:translateY(-7px) rotate(-45deg)}

/* ═══ MOBILE ══════════════════════════════════════════════════════ */
@media(max-width:1023px){
  #pt-burger{display:flex}
  #pt-nav{background:rgba(6,25,56,.92);backdrop-filter:blur(16px);
    -webkit-backdrop-filter:blur(16px)}

  #pt-links{
    position:absolute;top:100%;left:0;right:0;
    flex-direction:column;align-items:stretch;gap:2px;
    margin-left:0;
    /* SOLID, AND NO BACKDROP FILTER ON THIS ONE. The bar above keeps its
       blur; this panel cannot have one. Nested backdrop-filters inside a
       shadow root make Chromium composite this element against an already
       filtered backdrop, and the page behind reads straight through a
       background that is 98.5% opaque. On the built-in version of this nav
       the hero headline was legible through the open menu. The bar's own
       blur still gives the effect where it matters. */
    background:#061938;
    border-bottom:1px solid rgba(232,198,95,.16);
    padding:10px clamp(16px,4vw,44px) 22px;
    max-height:calc(100vh - 68px);overflow-y:auto;
    display:none;
  }
  #pt-nav.menu-open #pt-links{display:flex}

  .pt-item{flex-wrap:wrap;justify-content:space-between;
    border-bottom:1px solid rgba(241,236,225,.07)}
  .pt-item:last-child{border-bottom:none}
  .pt-link{flex:1 1 auto;padding:15px 2px;font-size:1rem}
  .pt-item.is-active > .pt-link::after,.pt-link.is-active::after{display:none}
  .pt-caret{flex:0 0 auto;padding:15px 10px;font-size:.85em}

  /* Child list is a plain indented block on mobile. A floating panel
     inside a panel is a place to get lost. */
  .pt-menu{
    position:static;transform:none;min-width:0;width:100%;
    margin:0 0 12px;padding:0 0 0 14px;
    background:transparent;backdrop-filter:none;-webkit-backdrop-filter:none;
    border:none;border-left:2px solid rgba(232,198,95,.28);
    border-radius:0;box-shadow:none;
    flex-basis:100%;
  }
  .pt-menu::before{display:none}
  .pt-item.is-open .pt-menu{display:flex}
  .pt-menu a{padding:12px 12px;font-size:.94rem}

  #pt-cta-wrap{margin-left:auto}
  #pt-cta{font-size:.8rem;padding:.68em 1.2em}
  #pt-cta .cta-long{display:none}
}
@media(max-width:420px){
  #pt-cta{padding:.66em 1.05em}
  #pt-cta .arrow{display:none}
}


/* ═══ THE 320px BAR ═══════════════════════════════════════════════
   At 320 the logo, the Contact pill and the burger add up to more than
   the bar, and the burger hangs 9px off the right edge. Nothing here is
   a redesign: the logo loses 4px, the bar loses 6px of padding either
   side, and the pill tightens. Added 4 Aug 2026 to all three pages and
   to PtNav v3.dc.html. */
@media(max-width:360px){
  #pt-bar{padding-left:14px;padding-right:14px;gap:10px}
  #pt-logo img{height:22px}
  #pt-cta{padding:.6em .82em;font-size:.8rem}
  #pt-burger{width:34px;margin-right:-4px}
}

@media(prefers-reduced-motion:reduce){
  #pt-nav,#pt-nav *{transition:none!important}
}

/*    SITE FOOTER, BUILT IN RATHER THAN PLACED
   PtFooter is its own custom element and is meant to sit once in the
   Wix footer strip, which is what makes it editable in one place for
   every page. It would not load there, so it ships inside this page
   instead. That is a real cost and it should be written down: this
   copy of the footer will not track PtFooter v3.dc.html. Change one
   and the other does not move.

   PtFooter v3.dc.html stays the source of record. If it starts loading
   in Wix again, delete this block and the markup at the foot of the
   page rather than maintaining two.

   Every selector here is pt- prefixed and nothing in the page uses that
   prefix, so the two sheets do not touch.
   ══════════════════════════════════════════════════════════════════ */
/* ═══════════════════════════════════════════════════════════════════
   PARALLAXX · SITE FOOTER · v3  ·  THREE COLUMNS + UTILITY ROW
   -------------------------------------------------------------------
   THE PROBLEM WITH v2
   Twenty-four links in four equal columns. Every one of them the same
   size, the same colour, the same weight. On a site whose entire
   premise is "pick one of two doors", the last thing on the page was
   a sitemap that made twenty-four things look equally important.

   THE FIX IS NOT FEWER LINKS. IT IS HIERARCHY.
   Seven pages on this site are linked from NOWHERE except this footer:
   Blog, both podcasts, Progress Journal, Three Toxic Lies, Identity
   2.0, As Seen In. Delete them from here and they are orphaned:
   unreachable by a human, and invisible to search because nothing
   points at them. So they stay. They just stop shouting.

   WHAT THE VISITOR SEES NOW
     THREE COLUMNS, LARGE   the two doors, then Daniel. nine links.
                            the whole site, as far as anyone arriving
                            cares.
     ONE QUIET ROW, SMALL   everything else, inline, dot-separated,
                            in the register of a footnote rather than
                            a menu. Reachable. Not competing.

   Reading order does the work: doors first at full weight, then the
   row you only look at if you were already looking for something
   specific, then legal. Each tier is quieter than the one above it.

   WHY THERE IS NO BLURB UNDER THE LOGO
   A footer does not need to restate the pitch. Everything above it has
   already spoken, and by the time anyone is down here they are looking
   for a link, not for the argument again.

   WHY THE GIVE IT ALL BANNER IS GONE
   It was a full-width tinted panel with a badge and two lines of copy,
   for a brand that reads as a men's event. Under a footer that serves
   two avatars it was the single loudest thing on the page, and it was
   shouting at half the audience. It is now one gold line in Daniel's
   column, which is the correct size for a sibling brand.

   ───────────────────────────────────────────────────────────────────
   TOKENS shared with GIVE IT ALL:  navy #061938  gold #E8C65F  Montserrat
   TOKENS Parallaxx only:  coral #FF501F  Poppins  cream #F1ECE1

   THE ACCENT RULE. GOLD IS DANIEL. CORAL IS YOU.
   There is NO coral down here, on purpose. Coral marks the reader's
   move, and every ask has already been made: the nav carries a coral
   Contact pill on every page, and the page above closes with its own.
   GIVE IT ALL is gold, because it is his world, not your move.
   ═══════════════════════════════════════════════════════════════════ */
:root{
  --px-navy:#061938;
  --px-navy-deep:#04122A;
  --px-navy-ink:#030C1C;
  --px-gold:#E8C65F;
  --px-gold-lift:#F3DD93;
  --px-coral:#FF501F;
  --px-coral-lift:#FF6A3D;
  --px-cream:#F1ECE1;
  --px-mist:#B1BFD7;
  --px-slate:#7C89A3;
}

#pt-foot,#pt-foot *{box-sizing:border-box}
#pt-foot{
  background:#030C1C;
  border-top:1px solid rgba(232,198,95,.16);
  font-family:'Montserrat',system-ui,-apple-system,sans-serif;
  color:#B1BFD7;-webkit-font-smoothing:antialiased}
#pt-foot-inner{max-width:1360px;margin:0 auto;
  padding:clamp(34px,3.6vw,46px) clamp(20px,4vw,52px) 24px}

/* ═══ TIER 1 · IDENTITY + THE THREE COLUMNS ═══════════════════════
   Two doors and Daniel. The doors are the reader's two routes in;
   the third is everywhere Daniel himself shows up, which is what the
   GIVE IT ALL bar used to be doing at ten times the size. */
#pt-foot-top{
  display:grid;
  grid-template-columns:minmax(260px,1fr) repeat(3,minmax(0,.72fr));
  gap:clamp(30px,3.4vw,52px);
  align-items:start;
  margin-bottom:clamp(28px,3vw,36px)}
/* Identity spans the full width once the columns need the room. */
@media(max-width:1080px){#pt-foot-top{grid-template-columns:repeat(3,minmax(0,1fr));gap:38px 30px}
  #pt-ident{grid-column:1/-1}}
/* THREE COLUMNS ALL THE WAY DOWN. This used to fall to two at 680 and to
   one at 440, which on a 390px phone made the footer 878px tall, taller
   than most of the sections above it and by a long way the tallest thing
   nobody came for. Held at three it is 563px, a third shorter, and the
   two-up version was the worst of both: it put Daniel alone on a row and
   left half of it empty.

   Holding three also keeps the footer the same object it is on desktop.
   Three doors, three columns, whatever the device. The type comes down
   at the bottom breakpoint to buy the width, which is the right trade
   for a block that is scanned rather than read. */
@media(max-width:680px){#pt-foot-top{gap:30px 20px}}
@media(max-width:440px){
  #pt-foot-top{gap:22px 12px}
  .pt-door h4{font-size:.6rem;letter-spacing:.12em;margin-bottom:10px;padding-bottom:8px}
  .pt-door a{font-size:.78rem;line-height:1.28;padding:4px 0}
}

#pt-foot-logo{display:inline-block;line-height:0;margin-bottom:14px;text-decoration:none}
#pt-foot-logo img{height:30px;width:auto;display:block;
  font-size:.8rem;font-weight:700;color:#F1ECE1}

#pt-social{display:flex;gap:18px;flex-wrap:wrap;margin-top:16px}
#pt-social a{font-size:.85rem;font-weight:600;color:#B1BFD7;
  text-decoration:none;transition:color .2s ease}
#pt-social a:hover,#pt-social a:focus-visible{color:#E8C65F;outline:none}

/* ── THE DOORS. Deliberately larger than anything else down here. ── */
.pt-door h4{
  font-size:.68rem;letter-spacing:.18em;text-transform:uppercase;
  font-weight:800;color:#A88F4E;margin:0 0 12px;
  padding-bottom:9px;border-bottom:1px solid rgba(232,198,95,.18)}
/* THE WHOLE BLOCK IS DELIBERATELY SHALLOW. Nothing down here is being
   sold. It exists so that seven otherwise-orphaned pages are reachable
   and so somebody hunting for terms or a podcast can find them. Every
   vertical value in this file was cut roughly a third for that reason,
   and the type went with it. If it starts feeling like a section again,
   it has grown.

   .92rem, not 1.02. At 1.02 these matched the page's body copy exactly,
   which made the footer read as another content section rather than as
   the foot of the page. They are still the largest thing down here, and
   still clearly larger than the utility row at .82, so the hierarchy the
   note above describes is intact. The size came off the type and went
   into padding instead, so the tap target grew rather than shrank. */
.pt-door a{
  display:block;color:#D7DEEA;font-size:.92rem;font-weight:500;
  line-height:1.3;padding:5px 0;margin-bottom:1px;text-decoration:none;
  border-radius:3px;transition:color .2s ease}
.pt-door a:first-of-type{padding-top:0}
.pt-door a:last-child{margin-bottom:0}
.pt-door a:hover,.pt-door a:focus-visible{color:#E8C65F;outline:none}

/* THE SIBLING BRAND, AS A LINE RATHER THAN A BANNER.
   It stays GOLD, because gold is Daniel and GIVE IT ALL is his room.
   That single colour is now the whole signal — it used to be a
   42px badge, a border, a tinted panel and two lines of body copy,
   which made a men's-retreat brand the loudest thing in a footer
   serving two avatars. */
.pt-door a.ext{color:#E8C65F;font-weight:600}
.pt-door a.ext:hover,.pt-door a.ext:focus-visible{color:#F3DD93}
.pt-door a.ext .mk{font-size:.8em;margin-left:.35em;opacity:.8}

/* ═══ TIER 2 · THE UTILITY ROW ════════════════════════════════════
   Everything the site has that is not a door. Small, inline, dot
   separated. This is the register of a footnote, and that is the
   point: it is here for the person who came looking for it, and
   invisible to the person who did not. */
#pt-util{
  display:flex;flex-wrap:wrap;align-items:center;
  gap:7px 0;
  padding-top:18px;border-top:1px solid rgba(241,236,225,.1);
  margin-bottom:14px}
#pt-util a{
  color:#6E7B94;font-size:.82rem;text-decoration:none;
  padding:3px 0;border-radius:3px;white-space:nowrap;
  transition:color .2s ease}
#pt-util a:hover,#pt-util a:focus-visible{color:#E8C65F;outline:none}
/* Separator TRAILS its link rather than leading the next one. With
   ::before, every line the row wraps onto opens with an orphaned dot.
   Trailing means a wrapped line starts on a word, which is what the
   eye expects, and the dot left at a line end reads as continuation. */
#pt-util a:not(:last-child)::after{
  content:"·";color:#3E4A63;margin:0 11px;display:inline-block}

/* ═══ TIER 3 · LEGAL ══════════════════════════════════════════════ */
#pt-legal{
  display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;
  color:#5E6B85;font-size:.8rem;line-height:1.6}
#pt-legal .links{display:inline-flex;gap:18px;flex-wrap:wrap}
#pt-legal a{color:inherit;text-decoration:none;
  border-bottom:1px solid rgba(232,198,95,.4);padding-bottom:1px;
  transition:color .2s ease,border-color .2s ease}
#pt-legal a:hover,#pt-legal a:focus-visible{
  color:#B1BFD7;border-bottom-color:#E8C65F;outline:none}

#pt-foot a:focus-visible{outline:2px solid rgba(232,198,95,.7);outline-offset:3px}
@media(prefers-reduced-motion:reduce){#pt-foot,#pt-foot *{transition:none!important}}`;

  var HTML = `<div id="px-root">

<header id="pt-nav">
  <div id="pt-bar">

    <!-- ══ LOGO = HOME. No text "Home" item; the mark is the link. ══ -->
    <a id="pt-logo" href="https://www.parallaxxtransformations.com" aria-label="Parallaxx Transformations — home">
      <img src="https://static.wixstatic.com/media/e1784d_fe3c841c471f47d088f0cd631a89d883~mv2.png"
           alt="Parallaxx Transformations">
    </a>

    <nav id="pt-links" aria-label="Primary">

      <!-- ══ FOR MEN ══ parent is a real link to the men's page ══ -->
      <div class="pt-item pt-has-drop" data-nav="men">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/men">For Men</a>
        <button class="pt-caret" type="button" aria-label="Show For Men menu" aria-expanded="false" aria-controls="pt-menu-men">&#9662;</button>
        <div class="pt-menu" id="pt-menu-men">
          <a href="https://www.parallaxxtransformations.com/men">Start Here</a>
          <a href="https://www.parallaxxtransformations.com/the-reconnected-man">The Reconnected Man</a>
        </div>
      </div>

      <!-- ══ FOR WOMEN ══ -->
      <div class="pt-item pt-has-drop" data-nav="women">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/women">For Women</a>
        <button class="pt-caret" type="button" aria-label="Show For Women menu" aria-expanded="false" aria-controls="pt-menu-women">&#9662;</button>
        <div class="pt-menu" id="pt-menu-women">
          <a href="https://www.parallaxxtransformations.com/women">Start Here</a>
          <a href="https://www.parallaxxtransformations.com/the-reconnected-woman">The Reconnected Woman</a>
        </div>
      </div>

      <div class="pt-item" data-nav="about">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/about-daniel-lawson">About</a>
      </div>

      <div class="pt-item" data-nav="testimonials">
        <a class="pt-link" href="https://www.parallaxxtransformations.com/testimonials-daniel-lawson">Testimonials</a>
      </div>

    </nav>

    <div id="pt-cta-wrap">
      <!-- CONTACT. Coral pill — Parallaxx-only accent. GIA uses a gold
           pill in this exact position: same shape, different colour.
           That is the whole family/identity trick. -->
      <a id="pt-cta" data-nav="contact" href="https://www.parallaxxtransformations.com/contact-daniel-lawson">
        Contact<span class="cta-long">&nbsp;</span><span class="arrow" aria-hidden="true">&#8594;</span>
      </a>
      <button id="pt-burger" type="button" aria-label="Menu" aria-expanded="false" aria-controls="pt-links">
        <span></span><span></span><span></span>
      </button>
    </div>

  </div>
</header>

<!-- ══════════════ 01 · THE FRAME ══════════════
     PLAIN. It names the CATEGORY (coaching), who it is for, and who runs it,
     in twenty-five words, and it diagnoses nobody, because a diagnosis has to
     pick an avatar and we have not met them yet.

     "handle it all on their own" is the clients' own language on BOTH sides,
     which is why it can carry a general sentence:
       men's hero   "You handled it all yourself. That's the distance."
       men's mirror "I kept it all internally."
       Gena K       "I was trying to figure it out by myself."
       Ana R        "I couldn't break through them alone."

     THE SUBLINE IS THE CONTINUATION. The headline says who this is for in
     the third person, which is how a category line has to work. The subline
     turns it on the reader, and it does it with the two pages' OWN answers
     to the same question:
       men's mirror    "How're you doing?"    -> "Good. Fine. Yeah, not too bad."
       women's mirror  "How's it all going?"  -> "Busy. Good busy."
     Fine is his word and busy is hers, both verbatim, and neither one genders
     the sentence. That question is also the one place the two avatar pages
     are supposed to rhyme, so the home page is now the third instance of a
     deliberate echo rather than a repeat.

     CUT, 3 Aug: "Take the one that's closer to true." Next to two doors
     labelled for men and for women, "closer to true" reads as a question
     about which one you are. Nothing on this page should invite that.

     ALSO REPLACED EARLIER: "I hold rooms for people who are used to holding
     them", over a three-sentence subline. Daniel does not describe what he
     does as holding rooms. ══════════════ -->
<section class="px-sec" id="px-top">
  <div class="grid">
    <div>
      <span class="eyebrow px-hand px-rise px-d1">which is you</span>
      <h1 class="px-serif px-rise px-d2">Coaching for people who handle it all on their own.</h1>
      <p class="sub px-rise px-d3">Ask how you&rsquo;re doing and you say fine.<br> Or busy. Same answer for years.</p>
    </div>
    <!-- [DANIEL] Replace with the Wix Media URL for daniel-clear.jpg.
         Real, straight on, not a stage shot and not a headshot. -->
    <figure class="px-portrait px-rise px-d3" style="margin:0">
      <img src="https://static.wixstatic.com/media/111174_1c14cd1cd5e5427dbd6cd38ac773a70a~mv2.jpg" alt="Daniel Lawson" loading="eager" fetchpriority="high">
      <!-- NO CAPTION. "No glass between us." belongs to the men's page portrait
           and cannot be reused here. Anything written to replace it was decorating
           a photograph that already says what it needs to: this is the man, and
           there is nothing in front of him. -->
    </figure>
  </div>
</section>

<!-- ══════════════ 02 · THE DOORS ══════════════
     BOTH HEADINGS ARE SECOND PERSON, and that is load bearing rather than
     stylistic. When the men's door was third person ("A man who carries it
     all...") and the women's was second ("You've hit every target..."), the
     page put a HE beside a SHE and readers assembled them into a couple:
     two characters in one relationship rather than two strangers who would
     never meet. Second person creates no character, so there is nobody to
     pair her with. Do not flip either one back on its own.

     Both headings are verbatim from their own built hero. "A man who
     carries it all. And a partner she never feels." now sits in the body,
     one level down, where it is a detail rather than the frame -- and it is
     still the line a WIFE recognises her husband in, which is how she gets
     him to the right page without the site asking her which gender she is.

     NOT USED, deliberately: "Twenty years in, and she's told you something
     is missing." Hotter, but it needs his wife to have actually had that
     conversation and plenty have not. A door is a filter for a whole
     avatar, so it takes the safe version.

     Women's heading and body are both LIFTED VERBATIM from the built
     women's hero, which moved past its spec document and is better than
     it. A door has to carry the hook of the page it opens or the click
     reads as a bait.

     The women's built hero carries NO qualifier strip, so the one below
     is the only line on either door that is not quoting its own page.
     Either it goes on her hero or it comes off both doors.
     See HOME PAGE - Alignment Audit.md C1. ══════════════ -->
<section class="px-sec">
  <div id="px-doors">

    <a class="px-door px-rise px-d3" href="https://www.parallaxxtransformations.com/men">
      <span class="tag">For men</span>
      <h2>You handled it all yourself. That&rsquo;s where the distance came from.</h2>
      <p>A man who carries it all. And a partner she never feels.</p>
      <div class="qual">Relationship &middot; Years in &middot; Care about her</div>
      <span class="go">This is me <span aria-hidden="true">&#8594;</span></span>
    </a>

    <a class="px-door px-rise px-d4" href="https://www.parallaxxtransformations.com/women">
      <span class="tag">For women</span>
      <h2>You&rsquo;ve hit every target. And you&rsquo;re still behind.</h2>
      <p>&ldquo;Everything is a priority right now.&rdquo; And it has been for six years.</p>
      <div class="qual">Independent &middot; Capable &middot; Successful</div>
      <span class="go">This is me <span aria-hidden="true">&#8594;</span></span>
    </a>

  </div>
</section>

<!-- ══════════════ 03 · THE ONE THING BOTH OF THEM DO ══════════════
     The only general sentence allowed on this site, and the reason the
     page does not read as two unrelated businesses sharing a logo.

     WRITTEN AS "YOU ... OR YOU", NOT "HE ... SHE". The he/she version put
     a man and a woman in consecutive clauses and the page read as a couple.
     Second person addresses one reader at a time and the pairing has
     nothing to attach to. Same sources either way: the first clause is
     [CLIENT], the second is [S, Christine] as her page now states it, and
     the shrinking is [CLIENT + F-V].

     The last line is [D-LIVED] and it is the confession that earns the
     rest of the page. ══════════════ -->
<section class="px-sec" id="px-shared">
  <div class="px-wrap">
    <span class="eyebrow px-hand px-rise px-d1">it starts the same way</span>
    <h2 class="px-serif px-rise px-d2">Completely different circumstances. The same patterns within.</h2>
    <p class="px-rise px-d3">You handled it on your own so you&rsquo;d never be a burden on anyone. You do still have expectations but keep them to yourself, so nobody ever gets the chance to turn you down.</p>

    <!-- REWRITTEN 3 Aug. Was "the want got smaller until it couldn't be
         refused", which read as though the asking WORKED. The point is the
         opposite: the ask gets shaved down to the bare minimum, so it is
         safe and it is also barely worth having. Both halves have to be in
         the sentence or it reads as a win. -->
    <p class="px-rise px-d3">So you trim what you ask for. Small enough that it can&rsquo;t be refused, and small enough that getting it changes nothing.</p>

    <!-- REWRITTEN 3 Aug. Was "You didn't start it, and you can't see it from
         the inside. That is the bit nobody gets to work on alone." Too
         compressed to land. It is carrying two separate ideas and this is
         the block where they have to be clear, because together they ARE
         the argument for the offer:
           1. nobody chose this, it was worked out young and it worked
              -- men's page: "A boy works out what gets his needs met.
              Yours worked then, so you never replaced them."
           2. it is invisible from inside, AND effort is not the missing
              ingredient. Both clauses are verbatim off the men's page:
              "But you were never shown what you couldn't see" and
              "Effort was never what was missing."

         CONSIDERED AND NOT USED: "you can't see the label when you're inside
         the jar." Two problems. The site already owns a container metaphor
         made of glass -- the film, the pane, "I was the man behind the
         glass" -- and a jar is also glass, so it half-rhymes with the real
         metaphor instead of matching it or standing clear of it. And it is
         a coaching-circuit aphorism, which is the register this page spends
         its whole length staying out of. -->
    <p class="px-rise px-d3">You worked this out young. It worked, so you never replaced it. But you were never shown what you couldn&rsquo;t see, so more effort hasn&rsquo;t changed it. Because effort isn&rsquo;t what was missing.</p>
    <p class="mine px-rise px-d4">I did it too. I built things people needed so I&rsquo;d never have to ask to be included. Worked fine for about thirty years.</p>
  </div>
</section>

<!-- ══════════════ 04 · ME, AND THE RECORD ══════════════
     NO ORIGIN STORY. There are two of them and they are avatar-specific:
     the stages and the half-ask are his, the number that moved is hers.
     Running either one here picks a side before anybody has walked
     through a door. The record is neutral, true, and needs nothing
     captured first, which is why it is the safest evidence on the site.

     [DANIEL] STILL NEEDED: countries, rooms held, people worked with,
     and the as-seen-in logos. One line of numbers under the credential
     sentence is the cheapest win available on this page. ══════════════ -->
<section class="px-sec" id="px-me">
  <!-- [DANIEL] Replace with the Wix Media URL. Source: gallery3onstage.jpg
       from the GIVE IT ALL build. 2000px wide, q74, 230KB. -->
  <div class="px-plate" aria-hidden="true"><img src="https://static.wixstatic.com/media/111174_ad3e5fa47d294ff890516b996bbd2d3c~mv2.jpg" alt="" loading="lazy" decoding="async"></div>
  <div class="px-veil" aria-hidden="true"></div>
  <div class="px-wrap">
    <!-- HAND LINE. "and now me." is the hand line on BOTH avatar pages, so it
         cannot open this block. This one only works at the top of the funnel,
         and it answers the H1 rather than repeating it. -->
    <span class="hand px-hand px-rise px-d1">who&rsquo;s holding it</span>
    <p class="cred px-rise px-d2">I&rsquo;m <strong>Daniel Lawson</strong>. Credentialled through the <strong>International Coach Guild</strong>, qualified through over half a decade of client results, and the founder of <strong>GIVE IT ALL</strong> world of experiences.</p>

    <!-- THE RECORD. Numbers ruled 3 Aug 2026: 6+ years, 9 countries. The men's
         page still carried 5+ / 7 and has been corrected to match.
         Spelling follows the avatar pages: "Int'l Coach Guild", not
         "International". The media strip (ABC News, Wanderlust, Brainz,
         Solarcon) is deliberately NOT here: it runs at the foot of both avatar
         pages and it would cost this page more than it pays on a router. -->
    <dl class="px-record px-rise px-d3">
      <div><dt>1000+</dt><dd>lives changed</dd></div>
      <div><dt>9</dt><dd>countries</dd></div>
      <div><dt>6+</dt><dd>years facilitating</dd></div>
    </dl>

    <!-- NO GUIDE POSITION HERE, and that is the point. The two avatar pages
         take OPPOSITE positions and both are correct:
           /men   "I haven't been married for 10 years+ (yet). But we're not
                  too dissimilar."   Peer. It has to be, because a finished man
                  who never did the thing is a fraud, and the page admits the
                  not-married fact out loud.
           /women "I did not just get out of it. I got me back."   Completed.
                  It has to be, because peer is the fatal reading on her side,
                  and her fear is that stopping means being passed over.
         The guide position is a SALES argument. A router does not need it, and
         whichever one it picked it would half-contradict the other page four
         seconds later.

         The page's human claim is already made, once, in block 03: "I did it
         too. I built things people needed so I'd never have to ask to be
         included." That is a scene rather than a claim and it commits to
         nothing about how far out he is. This link is now the promise that the
         rest of the story exists, read in whichever register belongs to the
         reader. See HOME PAGE - Alignment Audit.md A3. -->
    <a class="more px-rise px-d4" href="https://www.parallaxxtransformations.com/about-daniel-lawson">How I got here <span aria-hidden="true">&#8594;</span></a>
  </div>
</section>

<!-- ══════════════ 05 · NEITHER OF THOSE ══════════════ -->
<section class="px-sec" id="px-else">
  <div class="px-wrap">
    <span class="lab">Here for something else?</span>
    <div class="row">
      <a href="https://giveitallevent.com">GIVE IT ALL experiences</a>
      <a href="https://www.parallaxxtransformations.com/daniel-lawson-speaking">Speaking</a>
      <a href="https://www.parallaxxtransformations.com/parallaxx-perspectives-podcast">The podcast</a>
      <a href="https://www.parallaxxtransformations.com/ptjournal">The journal</a>
    </div>
  </div>
</section>

<!-- ══════════════ 06 · THE CLOSE ══════════════
     The doors again, nothing new, and no second call to action competing
     with them. ══════════════ -->
<section class="px-sec" id="px-close">
  <!-- The line for somebody who read the whole page and still has not clicked.
       Note this is the only hand line on the site in title case; every other
       one, here and on both avatar pages, is lowercase. Deliberate or not, it
       is a one-word change. -->
  <span class="hand px-hand px-rise px-d1">Choose Your Path</span>
  <div class="pair">
    <a class="px-mini px-rise px-d2" href="https://www.parallaxxtransformations.com/men">
      <span class="tag">For men</span>
      <span class="line">You handled it all yourself. That&rsquo;s where the distance came from.</span>
      <span class="go">This is me <span aria-hidden="true">&#8594;</span></span>
    </a>
    <a class="px-mini px-rise px-d3" href="https://www.parallaxxtransformations.com/women">
      <span class="tag">For women</span>
      <span class="line">You&rsquo;ve hit every target. And you&rsquo;re still behind.</span>
      <span class="go">This is me <span aria-hidden="true">&#8594;</span></span>
    </a>
  </div>
</section>

<footer id="pt-foot">
  <div id="pt-foot-inner">

    <div id="pt-foot-top">

      <!-- ══ IDENTITY ══ The mark and the four places he posts. No
           paragraph, no CTA: both were cut, and the column is better
           for it. ══ -->
      <div id="pt-ident">
        <a id="pt-foot-logo" href="https://www.parallaxxtransformations.com" aria-label="Parallaxx Transformations — home">
          <img src="https://static.wixstatic.com/media/e1784d_fe3c841c471f47d088f0cd631a89d883~mv2.png"
               alt="Parallaxx Transformations" loading="lazy">
        </a>
        <nav id="pt-social" aria-label="Social">
          <a href="https://www.youtube.com/@ReconnectYou1/featured" target="_blank" rel="noopener">YouTube</a>
          <a href="https://www.linkedin.com/in/daniel-reconnect-you/" target="_blank" rel="noopener">LinkedIn</a>
          <a href="https://www.instagram.com/daniel.lawson__/" target="_blank" rel="noopener">Instagram</a>
          <a href="https://www.facebook.com/Kiwi.Daniel" target="_blank" rel="noopener">Facebook</a>
        </nav>
      </div>

      <!-- ══ THE TWO DOORS ══ Same names, same order as the nav. ══ -->
      <nav class="pt-door" aria-label="For men">
        <h4>For Men</h4>
        <a href="https://www.parallaxxtransformations.com/men">Start here</a>
        <a href="https://www.parallaxxtransformations.com/the-reconnected-man">The Reconnected Man</a>
        <!-- /reconnect is the five-archetype quiz, not a programme.
             It is his free way in, so it belongs beside the door. -->
        <a href="https://www.parallaxxtransformations.com/reconnect">The Archetype Quiz</a>
      </nav>

      <nav class="pt-door" aria-label="For women">
        <h4>For Women</h4>
        <a href="https://www.parallaxxtransformations.com/women">Start here</a>
        <a href="https://www.parallaxxtransformations.com/the-reconnected-woman">The Reconnected Woman</a>
        <!-- [CLIENT] /priority-audit is the URL the women's home page
             CTA uses. Confirm the page is live before publishing. -->
        <a href="https://www.parallaxxtransformations.com/priority-audit">The Priority Audit</a>
      </nav>

      <!-- ══ DANIEL ══ Not a door. The three places he shows up in
           person, smallest commitment first. GIVE IT ALL is the last
           of them rather than a banner of its own. ══ -->
      <nav class="pt-door" aria-label="Daniel">
        <h4>Daniel</h4>
        <a href="https://www.parallaxxtransformations.com/about-daniel-lawson">About</a>
        <a href="https://www.parallaxxtransformations.com/daniel-lawson-speaking">Speaking</a>
        <!-- [CLIENT] No facilitating page exists on the site yet. This
             URL is a guess and must be confirmed or repointed. -->
        <a href="https://www.parallaxxtransformations.com/facilitating">Facilitating</a>
        <a class="ext" href="https://giveitallevent.com" target="_blank" rel="noopener">GIVE IT ALL<span class="mk" aria-hidden="true">&#8599;</span></a>
      </nav>

    </div>

    <!-- ══ THE UTILITY ROW ══
         Ordered by who asks for it: the person, then the work he makes,
         then the proof. Seven of these are linked from nowhere else on
         the site, which is exactly why the row exists. ══ -->
    <nav id="pt-util" aria-label="More">
      <a href="https://www.parallaxxtransformations.com/contact-daniel-lawson">Contact</a>
      <a href="https://www.parallaxxtransformations.com/book-a-call-with-daniel-lawson">Book a Call</a>
      <a href="https://www.parallaxxtransformations.com/reconnect-you-podcast-with-daniel-lawson">Reconnect You Podcast</a>
      <a href="https://www.parallaxxtransformations.com/parallaxx-perspectives-podcast">Perspectives Podcast</a>
      <a href="https://www.parallaxxtransformations.com/blog">Blog</a>
      <a href="https://www.parallaxxtransformations.com/ptjournal">Progress Journal</a>
      <a href="https://www.parallaxxtransformations.com/three-toxic-lies">Three Toxic Lies</a>
      <!-- [CLIENT] If Identity 2.0 is aimed at one avatar, promote it
           into that door's column instead of leaving it here. -->
      <a href="https://www.parallaxxtransformations.com/your-identity-challenge">Your Identity 2.0 Challenge</a>
      <a href="https://www.parallaxxtransformations.com/testimonials-daniel-lawson">Testimonials</a>
      <a href="https://www.parallaxxtransformations.com/daniel-lawson-as-seen-in">As Seen In</a>
    </nav>

    <div id="pt-legal">
      <span>&copy; <span id="pt-year">2026</span> Parallaxx Transformations &middot; Daniel Lawson</span>
      <span class="links">
        <a href="https://www.parallaxxtransformations.com/terms-of-use">Terms of Service</a>
        <a href="https://www.parallaxxtransformations.com/privacy-policy">Privacy Policy</a>
      </span>
    </div>

  </div>
</footer>

</div>`;

  function addFonts(){
    if (document.getElementById('px-fonts')) return;
    var p1=document.createElement('link'); p1.rel='preconnect'; p1.href='https://fonts.googleapis.com'; document.head.appendChild(p1);
    var p2=document.createElement('link'); p2.rel='preconnect'; p2.href='https://fonts.gstatic.com'; p2.crossOrigin=''; document.head.appendChild(p2);
    var f0=document.createElement('link'); f0.rel='stylesheet'; f0.href='https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&display=swap'; document.head.appendChild(f0);
    var f1=document.createElement('link'); f1.rel='stylesheet'; f1.href='https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap'; document.head.appendChild(f1);
    /* @font-face has to live in the DOCUMENT, not the shadow root. Chrome
       ignores font-face rules declared inside a shadow tree. */
    var ff=document.createElement('style'); ff.id='px-fonts'; ff.textContent=`/* LUMIOS MARKER is not on Google Fonts. Upload the .woff2 to Wix Media and drop
   the URL in below. Until then the stack falls through to Permanent Marker. */
@font-face{font-family:'Lumios Marker';font-display:swap;
  src:url('LUMIOS_MARKER_WOFF2_URL') format('woff2');}`; document.head.appendChild(ff);
  }

  function loadScript(src){
    return new Promise(function(res,rej){
      var ex=document.querySelector('script[data-px="'+src+'"]');
      if(ex){ if(ex.getAttribute('data-loaded')){res();} else { ex.addEventListener('load',function(){res();}); ex.addEventListener('error',rej);} return; }
      var s=document.createElement('script'); s.src=src; s.async=false; s.setAttribute('data-px',src);
      s.addEventListener('load',function(){ s.setAttribute('data-loaded','1'); res(); });
      s.addEventListener('error',rej);
      document.head.appendChild(s);
    });
  }

  function loadLibs(){
    var g=loadScript('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js')
      .then(function(){ return loadScript('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js'); });
    var l=loadScript('https://unpkg.com/lenis@1.1.13/dist/lenis.min.js');
    return Promise.all([ g.catch(function(){}), l.catch(function(){}) ]);
  }

  /* ══════════════ ANCESTOR COLLAPSE ══════════════
     Wix wraps a custom element in containers with fixed heights, so the page
     renders inside a short box with its own scrollbar. This walks up and
     releases them.

     IT MUST ONLY EVER RUN ONCE PER ELEMENT. The first version re-ran on
     every resize and called ScrollTrigger.refresh() whenever it changed
     anything. If Wix re-applied its own height after we set auto -- which it
     does -- "changed" was true on every pass, so:
         resize -> collapse -> refresh -> layout mutates -> resize -> ...
     That loop grew the document until Chrome clamped it at 2^24, which is
     16,777,216px of empty scroll. A WeakSet makes each element a one-shot,
     which is enough on its own to break the cycle.

     Three further belts, because a runaway here is invisible in the editor
     and catastrophic on the live page:
       - resize is debounced, so a drag is one pass and not sixty
       - refreshes are capped
       - a sanity check bails out entirely if the document is already absurd,
         so a loop that starts for some other reason cannot be fed by us
     ══════════════════════════════════════════════ */
  var PX_SANE_MAX = 200000;              // taller than any real page here
  var pxCollapsed = new WeakSet();
  var pxRefreshes = 0;

  function collapseAncestors(host){
    var changed = false;
    try{
      if (document.documentElement.scrollHeight > PX_SANE_MAX) return false;
      var h = host.getBoundingClientRect().height;
      if (h < 50) return false;
      var n = host.parentElement, guard = 0;
      while(n && n !== document.body && guard++ < 14){
        if(!pxCollapsed.has(n) && n.getBoundingClientRect().height > h + 600){
          pxCollapsed.add(n);            // one shot, whatever Wix does next
          n.style.height = 'auto';
          n.style.minHeight = '0px';
          changed = true;
        }
        n = n.parentElement;
      }
    }catch(e){}
    return changed;
  }

  function collapseAndRefresh(host){
    if (!collapseAncestors(host)) return;
    if (pxRefreshes >= 4) return;
    pxRefreshes++;
    if (window.ScrollTrigger) { try{ window.ScrollTrigger.refresh(); }catch(e){} }
  }

  function boot(root){
    if(!root || !root.getElementById('px-root')) return;


    /* THE ONLY SCRIPT ON THE PAGE, AND NOTHING DEPENDS ON IT.
       Every word above is already visible before this runs. All it does is
       cancel the entrance for anybody arriving already scrolled, so a deep
       link or a restored scroll position does not replay an animation the
       visitor has effectively already watched. */
  /* ══════════════ SITE NAV ══════════════
     PtNav is built into this page rather than placed in the Wix header
     strip, for the same reason as the footer: the strip would not load it.
     PtNav v3.dc.html stays the source of record and this copy will not
     track it. Change one and the other does not move.

     Two things had to change coming in. The active prop is gone, because
     there is no Wix instance to set one, so the section is worked out from
     the URL and nothing else. And every lookup goes through root, which is
     the shadow root once this is bundled.

     document.addEventListener is deliberately left alone below: the
     outside-click and Escape handlers have to hear events that never reach
     the shadow root. */
  (function siteNav(){

    const nav = root.getElementById('pt-nav');
    if(!nav) return;
    const links  = root.getElementById('pt-links');
    const burger = root.getElementById('pt-burger');
    const items  = [...nav.querySelectorAll('.pt-has-drop')];
    const MOBILE = () => window.innerWidth < 1024;

    /* ── WHERE YOU ARE ──────────────────────────────────────────────
       Worked out from the URL, because this element lives ONCE in the
       site's header strip and therefore serves every page from a single
       instance. A per-page the active prop cannot do that: one instance
       carries one value, so "For Women" would sit underlined on the
       men's page too.

       The prop still wins when it is set, for the Wix editor preview
       and for any page whose path does not match the table below. */
    const PATHS = [
      [/^\/(men|the-reconnected-man|the-archetype-quiz)\b/,      'men'],
      [/^\/(women|the-reconnected-woman|priority-audit)\b/,      'women'],
      [/^\/about-daniel-lawson\b/,                              'about'],
      [/^\/(daniel-lawson-speaking|facilitating)\b/,             'about'],
      [/^\/testimonials-daniel-lawson\b/,                       'testimonials'],
      [/^\/(contact-daniel-lawson|book-a-call)/,                 'contact']
    ];
    const fromPath = () => {
      const p = (location.pathname || '').replace(/\/+$/, '').toLowerCase() || '/';
      for(const [re, key] of PATHS) if(re.test(p)) return key;
      return '';
    };
    const active = fromPath();
    if(active){
      const el = nav.querySelector('[data-nav="'+active+'"]');
      if(el) el.classList.add('is-active');
    }

    /* ── NAVY ON SCROLL ─────────────────────────────────────────── */
    let ticking = false;
    const onScroll = () => {
      if(ticking) return; ticking = true;
      requestAnimationFrame(() => {
        nav.classList.toggle('is-stuck', window.scrollY > 40);
        ticking = false;
      });
    };
    window.addEventListener('scroll', onScroll, {passive:true});
    onScroll();

    /* ── MOBILE PANEL ───────────────────────────────────────────── */
    const closeMenu = () => {
      nav.classList.remove('menu-open');
      burger.setAttribute('aria-expanded','false');
      items.forEach(closeDrop);
    };
    burger.addEventListener('click', () => {
      const open = !nav.classList.contains('menu-open');
      nav.classList.toggle('menu-open', open);
      burger.setAttribute('aria-expanded', String(open));
      if(!open) items.forEach(closeDrop);
    });

    /* ── SUBMENUS ───────────────────────────────────────────────────
       Desktop hover and keyboard focus are pure CSS. The caret only
       exists for pointers that cannot hover, and for anyone who would
       rather tap the arrow than the word. */
    function closeDrop(it){
      it.classList.remove('is-open');
      const c = it.querySelector('.pt-caret');
      if(c) c.setAttribute('aria-expanded','false');
    }
    items.forEach(it => {
      const caret = it.querySelector('.pt-caret');
      caret.addEventListener('click', e => {
        e.preventDefault(); e.stopPropagation();
        const open = !it.classList.contains('is-open');
        items.forEach(closeDrop);
        it.classList.toggle('is-open', open);
        caret.setAttribute('aria-expanded', String(open));
      });
    });

    /* ── DISMISSAL ──────────────────────────────────────────────── */
    links.querySelectorAll('a').forEach(a =>
      a.addEventListener('click', () => { if(MOBILE()) closeMenu(); }));

    /* composedPath, not e.target. A click inside a shadow root is RETARGETED
       by the time it reaches the document: e.target becomes the host element,
       so nav.contains(e.target) is false for a click on the burger itself and
       this handler closed the panel in the same tick the burger opened it.
       The menu looked completely dead. composedPath() reports the real path
       through the shadow tree, and in the light DOM it still contains nav, so
       one line covers both runtimes. */
    document.addEventListener('click', e => {
      const path = e.composedPath ? e.composedPath() : [e.target];
      if(path.indexOf(nav) === -1){ items.forEach(closeDrop); if(MOBILE()) closeMenu(); }
    });

    document.addEventListener('keydown', e => {
      if(e.key !== 'Escape') return;
      items.forEach(closeDrop);
      if(nav.classList.contains('menu-open')){ closeMenu(); burger.focus(); }
    });

    /* Crossing the breakpoint with the phone panel open would leave a
       stranded overlay on the desktop layout. */
    let wasMobile = MOBILE();
    window.addEventListener('resize', () => {
      const now = MOBILE();
      if(now !== wasMobile){ wasMobile = now; closeMenu(); }
    });
  })();

    /* ══ FOOTER YEAR ══
       The footer is built into this page rather than placed as its own
       element, same as the women's page. This is the only line of script it
       has: a stale copyright year is the one thing in a footer nobody
       remembers to update, and it is what makes a site look abandoned.
       Runs BEFORE the reduced-motion return so it happens either way. */
    const year = root.getElementById('pt-year');
    if (year) year.textContent = String(new Date().getFullYear());

    const reduce = window.matchMedia('(prefers-reduced-motion:reduce)').matches;
    if(reduce) return;

    if(window.scrollY > 40){
      root.querySelectorAll('.px-rise').forEach(el=>{ el.style.animation = 'none'; });
    }
  }

  class ParallaxxHome extends HTMLElement {
    connectedCallback(){
      if (this._mounted) return; this._mounted = true;
      addFonts();
      var shadow = this.attachShadow({mode:'open'});
      shadow.innerHTML = '<style>'+CSS+'</style>'+HTML;
      var host = this;
      /* THE HOST ITSELF, NOT JUST ITS ANCESTORS.
         collapseAndRefresh only walks upward. If the Wix editor has given
         the widget its own fixed height -- which it does by default -- the
         element keeps it and the surplus renders as empty page background
         under the content. Clearing it here is the difference between a
         page and a page followed by a white cliff. Added 4 Aug 2026. */
      try{ host.style.height='auto'; host.style.minHeight='0px'; }catch(e){}
      loadLibs().then(function(){ try{ boot(shadow); }catch(e){ console.error('[px] boot failed:', e); } })
        .catch(function(){ try{ boot(shadow); }catch(e){} });
      requestAnimationFrame(function(){ collapseAndRefresh(host); });
      [400,1200,2500].forEach(function(t){ setTimeout(function(){ collapseAndRefresh(host); }, t); });
      var pxRT;
      window.addEventListener('resize', function(){
        clearTimeout(pxRT);
        pxRT = setTimeout(function(){ collapseAndRefresh(host); }, 250);
      }, {passive:true});
    }
  }
  customElements.define('parallaxx-home', ParallaxxHome);
})();
